//! Packaging output: the `package.json` manifest, the generated-source README
//! with its boundary-convention notes and API reference, and the packaged
//! README describing the bundled artifact.
//!
//! The manifest is built with [`manifest::JsonObject`]
//! (`weaveffi_core::manifest`) so quoting and escaping are centralized; user
//! strings (name, description, license, author, homepage) can't corrupt the
//! JSON.

use std::collections::HashMap;

use camino::Utf8PathBuf;
use weaveffi_core::cache::CLI_VERSION;
use weaveffi_core::errors::ERROR_BRAND;
use weaveffi_core::manifest::{JsonObject, JsonValue};
use weaveffi_core::model::{
    BindingModel, CallbackInterfaceBinding, EnumBinding, ErrorBinding, FnBinding, InterfaceBinding,
    ModuleBinding, StructBinding,
};
use weaveffi_core::pkg::ResolvedPackage;
use weaveffi_core::utils::{render_prelude, render_trailer, CommentStyle};
use weaveffi_ir::ir::Api;

use crate::types::{
    js_cb_method_name, js_code_class_name, ts_type_for, type_display, wasm_type, wasm_type_note,
};

/// The prebuilt `wasm32-unknown-unknown` binary a package bundles: the
/// filename it's shipped under (next to the loader) and where to copy it from.
pub(crate) struct PackagedBinary {
    /// The bundled filename, `<lib_name>.wasm`.
    pub(crate) filename: String,
    /// The on-disk source the binary is copied from.
    pub(crate) source: Utf8PathBuf,
}

/// Prepend the generated-file prelude entries (`//`, `//warning`,
/// `//regenerate`) npm tolerates at the top of `package.json`. Mirrors
/// [`render_json_prelude`](weaveffi_core::utils::render_json_prelude), whose
/// version constant ([`CLI_VERSION`]) it shares.
fn json_prelude_entries(obj: JsonObject, input_basename: &str) -> JsonObject {
    obj.str_entry(
        "//",
        format!("Generated by WeaveFFI {CLI_VERSION} from {input_basename}"),
    )
    .str_entry(
        "//warning",
        "DO NOT EDIT. Your changes will be overwritten.",
    )
    .str_entry(
        "//regenerate",
        format!("To regenerate: weaveffi generate {input_basename} -o <out>"),
    )
}

/// Render the `package.json` manifest: prelude comment entries, npm metadata
/// from the resolved package (optional fields only when present), the fixed
/// ES-module entry points for the loader and its declarations, and, when a
/// binary is bundled, an explicit `files` list so npm publishes exactly the
/// loader, declarations, and `.wasm` (the README is always included by npm).
pub(crate) fn render_wasm_package_json(
    package: &ResolvedPackage,
    js_filename: &str,
    dts_filename: &str,
    wasm_filename: Option<&str>,
    input_basename: &str,
) -> String {
    let mut obj = json_prelude_entries(JsonObject::new(), input_basename)
        .str_entry("name", &package.name)
        .str_entry("version", &package.version)
        .str_entry("description", package.description_or_default())
        .opt_str_entry("license", package.license.as_deref());
    if let Some(author) = package.authors.first() {
        obj = obj.str_entry("author", author);
    }
    obj = obj
        .opt_str_entry("homepage", package.homepage.as_deref())
        .str_entry("type", "module")
        .str_entry("main", js_filename)
        .str_entry("types", dts_filename);
    if let Some(wasm) = wasm_filename {
        obj = obj.entry(
            "files",
            JsonValue::Array(
                [js_filename, dts_filename, wasm]
                    .into_iter()
                    .map(JsonValue::str)
                    .collect(),
            ),
        );
    }
    obj.render()
}

/// README for a packaged Wasm artifact: what the package contains, how to
/// load it from the bundled `.wasm` (or, without one, where the binary has to
/// come from), and the lifetime rules a consumer must follow.
pub(crate) fn render_packaged_readme(
    package: &ResolvedPackage,
    module_name: &str,
    js_filename: &str,
    binary: Option<&PackagedBinary>,
    input_basename: &str,
    emscripten: bool,
) -> String {
    use heck::ToUpperCamelCase;
    let load_fn = format!("load{}", module_name.to_upper_camel_case());
    let name = &package.name;
    let mut out = render_prelude(CommentStyle::Xml, input_basename);
    out.push_str(&format!("# {name} (WebAssembly)\n\n"));
    if emscripten {
        out.push_str(
            "Auto-generated JavaScript glue and TypeScript declarations for an Emscripten \
             build of this library. The package carries no binary: build the Emscripten \
             module yourself (so you control options like `locateFile`) and hand it to \
             the loader.\n\n",
        );
        out.push_str("```js\n");
        out.push_str("import Module from './your_library.js';\n");
        out.push_str(&format!("import {{ {load_fn} }} from '{name}';\n\n"));
        out.push_str(&format!("const api = await {load_fn}(Module());\n"));
        out.push_str("```\n\n");
        out.push_str(
            "Async functions and callback interfaces are not supported in Emscripten \
             mode: each affected entry point throws at call time and is omitted from the \
             TypeScript declarations.\n\n",
        );
    } else if let Some(b) = binary {
        out.push_str(&format!(
            "Auto-generated JavaScript loader and TypeScript declarations with the \
             prebuilt `wasm32-unknown-unknown` module bundled as `{}`. No toolchain is \
             needed: fetch the bundled file (or read it in Node) and hand it to the \
             loader.\n\n",
            b.filename
        ));
        out.push_str("```js\n");
        out.push_str(&format!("import {{ {load_fn} }} from '{name}';\n\n"));
        out.push_str("// Browsers and bundlers: resolve the bundled file's URL.\n");
        out.push_str(&format!(
            "const api = await {load_fn}(new URL('./{}', import.meta.url));\n\n",
            b.filename
        ));
        out.push_str("// Node: pass the bytes instead of fetching.\n");
        out.push_str("import { readFile } from 'node:fs/promises';\n");
        out.push_str(&format!(
            "const api2 = await {load_fn}(await readFile(new URL('./{}', import.meta.url)));\n",
            b.filename
        ));
        out.push_str("```\n\n");
    } else {
        out.push_str(
            "Auto-generated JavaScript loader and TypeScript declarations for a \
             `wasm32-unknown-unknown` build of this library. No `wasm32` binary was \
             supplied when this package was assembled, so it ships without one: build \
             the library with `cargo build --target wasm32-unknown-unknown --release` \
             and pass the resulting `.wasm` (a URL, its bytes, or a compiled \
             `WebAssembly.Module`) to the loader.\n\n",
        );
        out.push_str("```js\n");
        out.push_str(&format!("import {{ {load_fn} }} from '{name}';\n\n"));
        out.push_str(&format!(
            "const api = await {load_fn}('your_library.wasm');\n"
        ));
        out.push_str("```\n\n");
    }
    out.push_str(&format!(
        "`{js_filename}` is an ES module; the package is `\"type\": \"module\"`.\n\n"
    ));
    out.push_str("## Object lifetimes\n\n");
    out.push_str(
        "Interface values are wrapper classes holding one reference to a producer \
         object. Call `close()` (or bind the wrapper with `using`, which calls \
         `Symbol.dispose`) when you're done; a wrapper that is garbage collected \
         unclosed is released by a `FinalizationRegistry` backstop where the runtime \
         provides one. Passing a wrapper to a function lends its reference for the \
         duration of the call; a wrapper returned to you is yours to close.\n\n",
    );
    out.push_str(&render_trailer(CommentStyle::Xml, "README.md"));
    out
}

/// Render the `README.md`: build and load instructions for the configured
/// mode, the boundary conventions for every complex type family, the error
/// contract, and (for a non-empty API) the generated ABI-level reference.
pub(crate) fn render_wasm_readme(
    api: &Api,
    model: &BindingModel,
    prefix: &str,
    input_basename: &str,
    emscripten: bool,
) -> String {
    let mut out = render_prelude(CommentStyle::Xml, input_basename);
    out.push_str("# WeaveFFI Wasm (experimental)\n\n");
    if emscripten {
        out.push_str("This folder contains a minimal stub to help you load an Emscripten build of your WeaveFFI library.\n\n");
        out.push_str("Build (example):\n\n");
        out.push_str("```bash\n");
        out.push_str("emcc your_library.c -o your_library.js \\\n");
        out.push_str("  -sMODULARIZE=1 -sEXPORT_ES6=1 \\\n");
        out.push_str("  -sEXPORTED_RUNTIME_METHODS=HEAPU8 \\\n");
        out.push_str("  -sALLOW_MEMORY_GROWTH=1\n");
        out.push_str("```\n\n");
        out.push_str(&format!(
            "The `{prefix}_*` symbols are kept alive and exported automatically: the \
             generated header tags them with `{}_API`, which expands to \
             `__attribute__((used, visibility(\"default\")))` under Emscripten.\n\n",
            prefix.to_uppercase()
        ));
        out.push_str("Then construct the Emscripten module yourself (so you control options like `locateFile`) and pass it to the loader:\n\n");
        out.push_str("```js\n");
        out.push_str("import Module from './your_library.js';\n");
        out.push_str("import { loadWeaveffiWasm } from './weaveffi_wasm.js';\n\n");
        out.push_str("const api = await loadWeaveffiWasm(Module());\n");
        out.push_str("```\n\n");
        if model.has_async() {
            out.push_str("## Async Functions\n\n");
            out.push_str(
                "Async functions are not supported in Emscripten mode. Each one is \
                 generated as an explicit stub that throws at call time and is omitted \
                 from the TypeScript declarations. Use the standard \
                 `wasm32-unknown-unknown` loader or a native target when you need \
                 them.\n\n",
            );
        }
        if model.has_callback_interfaces() {
            out.push_str("## Callback Interfaces\n\n");
            out.push_str(
                "Callback interfaces are not supported in Emscripten mode: their \
                 trampolines rely on `WebAssembly.Function` and a growable \
                 `__indirect_function_table`, neither of which an Emscripten module \
                 exposes portably. Each function taking a callback interface is \
                 generated as an explicit stub that throws at call time and is omitted \
                 from the TypeScript declarations, along with the interface shapes \
                 themselves. Use the standard `wasm32-unknown-unknown` loader or a \
                 native target when you need them.\n\n",
            );
        }
    } else {
        out.push_str("This folder contains a minimal stub to help you load a `wasm32-unknown-unknown` build of your WeaveFFI library.\n\n");
        out.push_str("Build (example):\n\n");
        out.push_str("```bash\n");
        out.push_str("cargo build --target wasm32-unknown-unknown --release\n");
        out.push_str("```\n\n");
        out.push_str(
            "Then serve the `.wasm` and use `weaveffi_wasm.js` to load it: the loader \
             accepts a URL to fetch, the module's bytes (for Node, where `fetch` cannot \
             read files), or an already compiled `WebAssembly.Module`.\n\n",
        );
    }
    out.push_str("## Complex Type Handling\n\n");
    out.push_str("Wasm only supports numeric types natively (`i32`, `i64`, `f32`, `f64`). ");
    out.push_str("Complex types are encoded at the boundary as follows:\n\n");
    out.push_str("### Records\n\n");
    out.push_str("Records are **plain JavaScript objects**. A record crosses the boundary ");
    out.push_str("serialized in the WeaveFFI value-buffer format as one pointer + length ");
    out.push_str("pair in linear memory; the glue packs and unpacks it automatically, so ");
    out.push_str("there are no handles, no accessor functions, and nothing to free.\n\n");
    out.push_str("### Enums\n\n");
    out.push_str("C-style enums are passed as **`i32` values** corresponding to the variant's integer discriminant. ");
    out.push_str("Rich (algebraic) enums are plain objects tagged by variant name ");
    out.push_str("(`{ tag: \"Circle\", radius: 2 }`) and cross the boundary serialized in a ");
    out.push_str("value buffer, exactly like records.\n\n");
    out.push_str("### Objects\n\n");
    out.push_str("Interfaces are **wrapper classes** holding one reference to a producer ");
    out.push_str("object (an `i32` pointer into linear memory). A wrapper you receive is ");
    out.push_str("yours: release it with `close()` (or bind it with `using`, which calls ");
    out.push_str("`Symbol.dispose`); a wrapper collected unclosed is released by a ");
    out.push_str("`FinalizationRegistry` backstop where the runtime provides one, and ");
    out.push_str("destroy runs exactly once either way. Passing a wrapper to a function lends ");
    out.push_str("its reference for the duration of the call. Inside a value buffer an object ");
    out.push_str("crosses as a `u64` token carrying one reference: the writer clones the ");
    out.push_str("wrapper's reference and the reader adopts the token into a new wrapper.\n\n");
    out.push_str("### 64-bit Integers\n\n");
    out.push_str("`i64` and `u64` are JavaScript **`bigint`** values everywhere: as arguments, ");
    out.push_str("returns, record fields, and callback parameters. Map keys of these types ");
    out.push_str("become string property names on the decoded object. A `number` is accepted ");
    out.push_str("where a `bigint` is expected (it's widened with `BigInt(v)`, so a fractional ");
    out.push_str("value throws a `RangeError`). Values crossing by value follow the wasm ");
    out.push_str("calling convention: an out-of-range `bigint` wraps modulo 2^64 rather than ");
    out.push_str("throwing, and unsigned results are read back as unsigned (`u64` via ");
    out.push_str("`BigInt.asUintN`, `u32` via `>>> 0`).\n\n");
    out.push_str("### Optionals\n\n");
    out.push_str("Optional values map to **`null`** for the absent case. An optional crosses ");
    out.push_str("the boundary inside a value buffer as a one-byte presence flag followed by ");
    out.push_str("the value when present. The one exception is an optional interface, which ");
    out.push_str(
        "stays a nullable object pointer (`0` = absent) and maps to `Wrapper | null`.\n\n",
    );
    out.push_str("### Lists and Maps\n\n");
    out.push_str("Lists are JS arrays; maps are plain objects (a `Map` instance is also ");
    out.push_str("accepted on input). Both cross the boundary serialized in a value buffer ");
    out.push_str("as one pointer + length pair, recursing through element types.\n\n");
    out.push_str("### Iterators\n\n");
    out.push_str("`iter<T>` functions return a **lazy JS iterator** (typed ");
    out.push_str("`IterableIterator<T>`): each `next()` issues exactly one producer call, so ");
    out.push_str("iteration streams in constant memory. The producer handle is destroyed ");
    out.push_str("exactly once, on exhaustion or via `return()` when iteration stops early ");
    out.push_str("(a `for...of` loop calls `return()` automatically on `break` or `throw`). ");
    out.push_str("Abandoning an iterator without exhausting or closing it leaks the handle.\n");
    if !emscripten && model.has_async() {
        out.push_str("\n### Async Functions\n\n");
        out.push_str(
            "`async` functions return a **`Promise`**. `wasm32-unknown-unknown` has no \
             threads, so the producer's default spawner drives each future to completion \
             inline, inside the launch call: the completion callback fires (through a \
             function-table trampoline) before the wrapper returns, and the Promise is \
             already settled when you `await` it. There is nothing to pump or poll from \
             JS. A future that returns `Pending` can't be woken on this target with the \
             default spawner; a producer whose futures wait on external events needs its \
             own spawner (`weaveffi::set_spawner`), and driving that executor is then the \
             producer's responsibility, not the glue's. A typed error rejects the Promise \
             with the same class the synchronous wrapper would throw.\n",
        );
    }
    if !emscripten && model.has_callback_interfaces() {
        out.push_str("\n### Callback Interfaces\n\n");
        out.push_str(
            "A callback interface is a TypeScript `interface`; pass any object with the \
             matching methods where a parameter of that type is expected. The loader \
             keeps one **static vtable per interface** in linear memory, filled with \
             function-table indices of long-lived trampolines, and passes a small \
             integer context key with it; the producer calls `free(ctx)` when it drops \
             the callback, which releases your object. Delivery is **synchronous and \
             same-thread**: `wasm32-unknown-unknown` is single-threaded, so a method \
             runs only while a call into the module is on the stack. A producer that \
             calls back from a spawned thread cannot run on this target at all.\n\n",
        );
        out.push_str(
            "Method arguments that are strings, bytes, or buffered values are \
             **borrowed for the duration of the call**: they're copied or decoded into \
             JS values before your method runs. Object arguments transfer one reference \
             to you: `close()` the wrapper when you're done with it. An exception thrown \
             from a method is reported to the producer as error code `-4` (with the \
             exception's message) and the method's default value is returned in its \
             place; the producer then aborts the call it was making, and the original \
             caller sees a `WeaveFFIError` with code `-4` carrying your message (see \
             *Traps* below for how that abort reaches the caller on this target).\n",
        );
    }
    out.push_str("\n### Error Handling\n\n");
    out.push_str("The generated JS wrappers automatically handle errors by passing an error\n");
    out.push_str("pointer as the last argument to each Wasm function. The error struct is\n");
    out.push_str("16 bytes on wasm32: `{ i32 code, char* message, uint8_t* payload_ptr,\n");
    out.push_str("size_t payload_len }`. Your Wasm module must export the following\n");
    out.push_str("functions:\n\n");
    out.push_str("- `weaveffi_abi_version() -> i32`: the ABI revision the module implements; the loader refuses a mismatch\n");
    out.push_str("- `weaveffi_alloc(size: i32) -> i32`: allocate `size` bytes in linear memory\n");
    out.push_str("- `weaveffi_dealloc(ptr: i32, size: i32)`: release a `weaveffi_alloc` block\n");
    out.push_str("- `weaveffi_error_clear(err_ptr: i32)`: clear and free error resources\n");
    out.push_str("- `weaveffi_error_set(err_ptr: i32, code: i32, msg: i32)`: fill an error slot (used to report callback exceptions)\n");
    out.push_str("- `weaveffi_free_string(ptr: i32)`: free a producer-returned C string\n");
    out.push_str("- `weaveffi_free_bytes(ptr: i32, len: i32)`: free a producer-returned buffer\n");
    out.push_str("\nWrappers of functions declared `throws` raise the declaring module's typed\n");
    out.push_str("error class (a `WeaveFFIError` subclass with a per-code subclass, such as\n");
    out.push_str("`KeyNotFound`); every other wrapper raises the generic `WeaveFFIError` only\n");
    out.push_str("for producer panics, marshalling failures, and callback exceptions\n");
    out.push_str("(code `-4`). When the matched error code declares payload fields, the\n");
    out.push_str("wrapper decodes them from the error's value buffer and attaches them as\n");
    out.push_str("properties on the thrown error.\n");
    if !emscripten {
        out.push_str("\n#### Callback failures without unwinding\n\n");
        out.push_str(
            "`wasm32-unknown-unknown` builds with `panic = \"abort\"`, so when a callback \
             interface method throws, the producer can't unwind out of the call the way \
             native targets do. Instead the runtime records the failure, the producer's \
             code runs to completion on the method's default return value (`0`, `0n`, \
             or `false`), and the thunk then reports code `-4` with the exception's \
             message in place of the result, so the wrapper throws (or the Promise \
             rejects with) the same `WeaveFFIError` a native build would produce. While \
             that producer call is still on the stack, the glue refuses every further \
             callback invocation with the same error rather than calling your \
             implementation again, so your code observes the failure exactly as it would \
             under unwinding. Producers must tolerate a callback returning its default \
             once (a well-behaved producer already does, because a consumer could return \
             that value on purpose).\n",
        );
        out.push_str("\n#### Traps\n\n");
        out.push_str(
            "A producer panic can't be caught on the Rust side either: it executes \
             `unreachable`, and the engine throws a `WebAssembly.RuntimeError` out of \
             the call. The glue translates that trap for you: the wrapper throws (or the \
             Promise rejects with) a `WeaveFFIError` with code `-2` (`producer \
             panicked`), or code `-4` if a callback method had already failed during \
             the call. The error slot and every staged argument are released either \
             way. The producer frames between the trap and the call are *not* unwound, \
             so their cleanup does not run: a lock held across the panic stays locked, \
             and allocations those frames owned leak.\n",
        );
    }

    if !api.modules.is_empty() {
        render_api_reference(&mut out, api, model);
    }

    out.push('\n');
    out.push_str(&render_trailer(CommentStyle::Xml, "README.md"));
    out
}

/// Append the README's ABI-level API reference: one section per top-level
/// module covering its error domain, functions, interfaces, structs, and
/// enums.
fn render_api_reference(out: &mut String, api: &Api, model: &BindingModel) {
    let by_path: HashMap<&str, &ModuleBinding> =
        model.modules.iter().map(|m| (m.path.as_str(), m)).collect();
    out.push_str("\n## API Reference\n");
    for module in &api.modules {
        out.push_str(&format!("\n### Module: `{}`\n", module.name));
        let mb = by_path[module.name.as_str()];

        if let Some(eb) = mb.error.as_ref().filter(|eb| eb.declared_here) {
            render_error_ref(out, eb);
        }

        if !mb.functions.is_empty() {
            out.push_str("\n#### Functions\n");
            for f in &mb.functions {
                render_function_ref(out, f);
            }
        }

        if !mb.interfaces.is_empty() {
            out.push_str("\n#### Interfaces\n");
            for i in &mb.interfaces {
                render_interface_ref(out, i);
            }
        }

        if !mb.callback_interfaces.is_empty() {
            out.push_str("\n#### Callback Interfaces\n");
            for cb in &mb.callback_interfaces {
                render_callback_interface_ref(out, cb);
            }
        }

        if !mb.structs.is_empty() {
            out.push_str("\n#### Structs\n");
            for s in &mb.structs {
                render_struct_ref(out, s);
            }
        }

        if !mb.enums.is_empty() {
            out.push_str("\n#### Enums\n");
            for e in &mb.enums {
                render_enum_ref(out, e);
            }
        }
    }
}

/// Document a module's declared error domain: the JS class hierarchy it
/// generates, the stable ABI code of each subclass, and any structured
/// payload fields a code attaches to the thrown error.
fn render_error_ref(out: &mut String, eb: &ErrorBinding) {
    out.push_str(&format!("\n#### Error Domain: `{}`\n\n", eb.type_name));
    out.push_str(&format!(
        "Throwing wrappers in this module raise `{}` (a `{ERROR_BRAND}` subclass); \
         each code below is its own subclass carrying the stable `code`. Payload \
         fields are decoded from the error's value buffer and attached as \
         properties on the thrown error.\n\n",
        eb.type_name
    ));
    out.push_str("| Class | Code | Default Message | Payload Fields |\n");
    out.push_str("|-------|------|-----------------|----------------|\n");
    for c in &eb.codes {
        let fields = if c.fields.is_empty() {
            "(none)".to_string()
        } else {
            c.fields
                .iter()
                .map(|f| format!("`{}: {}`", f.name, type_display(&f.ty)))
                .collect::<Vec<_>>()
                .join(", ")
        };
        out.push_str(&format!(
            "| `{}` | `{}` | {} | {} |\n",
            js_code_class_name(&c.name),
            c.value,
            c.message,
            fields
        ));
    }
}

/// Document one interface: an object pointer wrapped by a JS class, with the
/// member entry points listed at the ABI level like free functions.
fn render_interface_ref(out: &mut String, i: &InterfaceBinding) {
    out.push_str(&format!("\n##### `{}`\n\n", i.name));
    if let Some(doc) = &i.doc {
        out.push_str(doc);
        out.push_str("\n\n");
    }
    out.push_str(
        "Passed as an **object pointer** (`i32`), wrapped by a JS class holding one \
         reference. Constructors return an owned reference; methods lend the pointer \
         as the implicit leading `self` argument; `close()` (or `Symbol.dispose`) \
         releases the reference via the destroy symbol exactly once.\n",
    );
    for f in i
        .constructors
        .iter()
        .chain(i.methods.iter())
        .chain(i.statics.iter())
    {
        render_function_ref(out, f);
    }
    out.push_str(&format!(
        "\n##### `{}`\n\nReturns a second reference to the same object. Used when the \
         wrapper is encoded as an object token inside a value buffer.\n",
        i.clone_symbol
    ));
    out.push_str(&format!(
        "\n##### `{}`\n\nReleases one object reference. Called by the wrapper's `close()` \
         (and by the finalizer backstop).\n",
        i.destroy_symbol
    ));
}

/// Document one callback interface: the TS shape a consumer implements, its
/// vtable layout, and each method's parameters at the API level.
fn render_callback_interface_ref(out: &mut String, cb: &CallbackInterfaceBinding) {
    out.push_str(&format!("\n##### `{}`\n\n", cb.name));
    if let Some(doc) = &cb.doc {
        out.push_str(doc);
        out.push_str("\n\n");
    }
    if let Some(msg) = &cb.deprecated {
        out.push_str(&format!("**Deprecated:** {msg}\n\n"));
    }
    out.push_str(&format!(
        "Implemented in JS as an object with the methods below. Passed as an `i32` \
         context key plus an `i32` pointer to the static `{}` vtable; the vtable's \
         trailing `free(ctx)` entry releases the JS object.\n\n",
        cb.vtable_tag
    ));
    out.push_str("| Method | Parameters | Returns |\n");
    out.push_str("|--------|------------|---------|\n");
    for m in &cb.methods {
        let params = if m.params.is_empty() {
            "(none)".to_string()
        } else {
            m.params
                .iter()
                .map(|p| format!("`{}: {}`", p.name, ts_type_for(&p.ty)))
                .collect::<Vec<_>>()
                .join(", ")
        };
        let ret = m
            .ret
            .as_ref()
            .map_or_else(|| "`void`".to_string(), |t| format!("`{}`", ts_type_for(t)));
        out.push_str(&format!(
            "| `{}` | {params} | {ret} |\n",
            js_cb_method_name(&m.name)
        ));
    }
}

/// Document one callable at the ABI level: its C signature in wasm value
/// types and a per-parameter table of API type, wasm slot type, and boundary
/// note.
fn render_function_ref(out: &mut String, f: &FnBinding) {
    let abi_name = &f.c_base;
    out.push_str(&format!("\n##### `{abi_name}`\n\n"));

    if let Some(doc) = &f.doc {
        out.push_str(doc);
        out.push_str("\n\n");
    }

    if let Some(msg) = &f.deprecated {
        out.push_str(&format!("**Deprecated:** {msg}\n\n"));
    }

    let params_sig: Vec<String> = f
        .params
        .iter()
        .map(|p| format!("{}: {}", p.name, wasm_type(&p.ty)))
        .collect();
    let ret_sig = f.ret.as_ref().map_or("void", wasm_type);
    out.push_str(&format!(
        "`{abi_name}({}) -> {ret_sig}`\n\n",
        params_sig.join(", ")
    ));

    out.push_str("| Param | API Type | Wasm | Notes |\n");
    out.push_str("|-------|----------|------|-------|\n");
    for param in &f.params {
        out.push_str(&format!(
            "| `{}` | `{}` | `{}` | {} |\n",
            param.name,
            type_display(&param.ty),
            wasm_type(&param.ty),
            wasm_type_note(&param.ty)
        ));
    }
    if let Some(ret) = &f.ret {
        out.push_str(&format!(
            "| _returns_ | `{}` | `{}` | {} |\n",
            type_display(ret),
            wasm_type(ret),
            wasm_type_note(ret)
        ));
    }
}

/// Document one record: a plain JS object serialized in a value buffer, with
/// its field schema in declaration (wire) order.
fn render_struct_ref(out: &mut String, s: &StructBinding) {
    out.push_str(&format!("\n##### `{}`\n\n", s.name));

    if let Some(doc) = &s.doc {
        out.push_str(doc);
        out.push_str("\n\n");
    }

    out.push_str(
        "A plain JS object, serialized in a value buffer (`i32` ptr + `i32` len) at \
         the boundary. Fields in declaration (wire) order:\n\n",
    );

    if !s.fields.is_empty() {
        out.push_str("| Field | Type |\n");
        out.push_str("|-------|------|\n");
        for field in &s.fields {
            out.push_str(&format!(
                "| `{}` | `{}` |\n",
                field.name,
                type_display(&field.ty)
            ));
        }
    }
}

/// Document one enum: a variant/value table for a C-style enum, or the
/// tagged-object union shape for a rich one.
fn render_enum_ref(out: &mut String, e: &EnumBinding) {
    out.push_str(&format!("\n##### `{}`\n\n", e.name));

    if let Some(doc) = &e.doc {
        out.push_str(doc);
        out.push_str("\n\n");
    }

    if e.is_rich() {
        render_rich_enum_ref(out, e);
        return;
    }

    out.push_str("Passed as `i32` discriminant.\n\n");
    out.push_str("| Variant | Value |\n");
    out.push_str("|---------|-------|\n");
    for v in &e.variants {
        out.push_str(&format!("| `{}` | `{}` |\n", v.name, v.value));
    }
}

/// Document a rich (algebraic) enum: a plain tagged object serialized in a
/// value buffer as an `i32` tag followed by the active variant's fields, not
/// a by-value `i32` discriminant like a plain enum.
fn render_rich_enum_ref(out: &mut String, e: &EnumBinding) {
    out.push_str(
        "Rich (algebraic) enum: a plain tagged object (`{ tag: \"Variant\", ...fields }`) \
         serialized in a value buffer as an `i32` tag followed by the active variant's \
         fields in declaration order.\n\n",
    );
    out.push_str("| Variant | Tag | Fields |\n");
    out.push_str("|---------|-----|--------|\n");
    for v in &e.variants {
        let fields = if v.fields.is_empty() {
            "(none)".to_string()
        } else {
            v.fields
                .iter()
                .map(|f| format!("`{}: {}`", f.name, type_display(&f.ty)))
                .collect::<Vec<_>>()
                .join(", ")
        };
        out.push_str(&format!("| `{}` | `{}` | {} |\n", v.name, v.value, fields));
    }
}
