//! Packaging output: the `package.json` manifest and the README with its
//! boundary-convention notes and generated API reference.
//!
//! The manifest is built with [`manifest::JsonObject`]
//! (`weaveffi_core::manifest`) so quoting and escaping are centralized; user
//! strings (name, description, license, author, homepage) can't corrupt the
//! JSON.

use std::collections::HashMap;

use weaveffi_core::cache::CLI_VERSION;
use weaveffi_core::codegen::common::walk_modules;
use weaveffi_core::errors::ERROR_BRAND;
use weaveffi_core::manifest::JsonObject;
use weaveffi_core::model::{
    BindingModel, EnumBinding, ErrorBinding, FnBinding, InterfaceBinding, ModuleBinding,
    StructBinding,
};
use weaveffi_core::pkg::ResolvedPackage;
use weaveffi_core::utils::{render_prelude, render_trailer, CommentStyle};
use weaveffi_ir::ir::Api;

use crate::types::{js_code_class_name, type_display, wasm_type, wasm_type_note};

/// Prepend the generated-file prelude entries (`//`, `//warning`,
/// `//regenerate`) npm tolerates at the top of `package.json`. Mirrors
/// [`render_json_prelude`](weaveffi_core::utils::render_json_prelude), whose
/// version constant ([`CLI_VERSION`]) it shares.
fn json_prelude_entries(obj: JsonObject, input_basename: &str) -> JsonObject {
    obj.str_entry(
        "//",
        format!("Generated by WeaveFFI {CLI_VERSION} from {input_basename}"),
    )
    .str_entry(
        "//warning",
        "DO NOT EDIT. Your changes will be overwritten.",
    )
    .str_entry(
        "//regenerate",
        format!("To regenerate: weaveffi generate {input_basename} -o <out>"),
    )
}

/// Render the `package.json` manifest: prelude comment entries, npm metadata
/// from the resolved package (optional fields only when present), and the
/// fixed ES-module entry points for the loader and its declarations.
pub(crate) fn render_wasm_package_json(
    package: &ResolvedPackage,
    js_filename: &str,
    dts_filename: &str,
    input_basename: &str,
) -> String {
    let mut obj = json_prelude_entries(JsonObject::new(), input_basename)
        .str_entry("name", &package.name)
        .str_entry("version", &package.version)
        .str_entry("description", package.description_or_default())
        .opt_str_entry("license", package.license.as_deref());
    if let Some(author) = package.authors.first() {
        obj = obj.str_entry("author", author);
    }
    obj.opt_str_entry("homepage", package.homepage.as_deref())
        .str_entry("type", "module")
        .str_entry("main", js_filename)
        .str_entry("types", dts_filename)
        .render()
}

/// Render the `README.md`: build and load instructions for the configured
/// mode, the boundary conventions for every complex type family, the error
/// contract, and (for a non-empty API) the generated ABI-level reference.
pub(crate) fn render_wasm_readme(
    api: &Api,
    model: &BindingModel,
    prefix: &str,
    input_basename: &str,
    emscripten: bool,
) -> String {
    let mut out = render_prelude(CommentStyle::Xml, input_basename);
    out.push_str("# WeaveFFI Wasm (experimental)\n\n");
    if emscripten {
        out.push_str("This folder contains a minimal stub to help you load an Emscripten build of your WeaveFFI library.\n\n");
        out.push_str("Build (example):\n\n");
        out.push_str("```bash\n");
        out.push_str("emcc your_library.c -o your_library.js \\\n");
        out.push_str("  -sMODULARIZE=1 -sEXPORT_ES6=1 \\\n");
        out.push_str("  -sEXPORTED_RUNTIME_METHODS=HEAPU8 \\\n");
        out.push_str("  -sALLOW_MEMORY_GROWTH=1\n");
        out.push_str("```\n\n");
        out.push_str(&format!(
            "The `{prefix}_*` symbols are kept alive and exported automatically: the \
             generated header tags them with `{}_API`, which expands to \
             `__attribute__((used, visibility(\"default\")))` under Emscripten.\n\n",
            prefix.to_uppercase()
        ));
        out.push_str("Then construct the Emscripten module yourself (so you control options like `locateFile`) and pass it to the loader:\n\n");
        out.push_str("```js\n");
        out.push_str("import Module from './your_library.js';\n");
        out.push_str("import { loadWeaveffiWasm } from './weaveffi_wasm.js';\n\n");
        out.push_str("const api = await loadWeaveffiWasm(Module());\n");
        out.push_str("```\n\n");
        if walk_modules(&api.modules).any(|m| m.functions.iter().any(|f| f.r#async)) {
            out.push_str("## Async Functions\n\n");
            out.push_str(
                "Async functions are not supported in Emscripten mode. Each one is \
                 generated as an explicit stub that throws at call time and is omitted \
                 from the TypeScript declarations. Use the standard \
                 `wasm32-unknown-unknown` loader or a native target when you need \
                 them.\n\n",
            );
        }
        if walk_modules(&api.modules).any(|m| !m.listeners.is_empty()) {
            out.push_str("## Callbacks and Listeners\n\n");
            out.push_str(
                "Callbacks and listeners are not supported in Emscripten mode: their \
                 trampolines rely on `WebAssembly.Function` and a growable \
                 `__indirect_function_table`, neither of which an Emscripten module \
                 exposes portably. Each register/unregister entry point is generated \
                 as an explicit stub that throws at call time and is omitted from the \
                 TypeScript declarations. Use the standard `wasm32-unknown-unknown` \
                 loader or a native target when you need them.\n\n",
            );
        }
    } else {
        out.push_str("This folder contains a minimal stub to help you load a `wasm32-unknown-unknown` build of your WeaveFFI library.\n\n");
        out.push_str("Build (example):\n\n");
        out.push_str("```bash\n");
        out.push_str("cargo build --target wasm32-unknown-unknown --release\n");
        out.push_str("```\n\n");
        out.push_str("Then serve the `.wasm` and use `weaveffi_wasm.js` to load it.\n\n");
    }
    out.push_str("## Complex Type Handling\n\n");
    out.push_str("Wasm only supports numeric types natively (`i32`, `i64`, `f32`, `f64`). ");
    out.push_str("Complex types are encoded at the boundary as follows:\n\n");
    out.push_str("### Records\n\n");
    out.push_str("Records are **plain JavaScript objects**. A record crosses the boundary ");
    out.push_str("serialized in the WeaveFFI value-buffer format as one pointer + length ");
    out.push_str("pair in linear memory; the glue packs and unpacks it automatically, so ");
    out.push_str("there are no handles, no accessor functions, and nothing to free.\n\n");
    out.push_str("### Enums\n\n");
    out.push_str("C-style enums are passed as **`i32` values** corresponding to the variant's integer discriminant. ");
    out.push_str("Rich (algebraic) enums are plain objects tagged by variant name ");
    out.push_str("(`{ tag: \"Circle\", radius: 2 }`) and cross the boundary serialized in a ");
    out.push_str("value buffer, exactly like records.\n\n");
    out.push_str("### Optionals\n\n");
    out.push_str("Optional values map to **`null`** for the absent case. An optional crosses ");
    out.push_str("the boundary inside a value buffer as a one-byte presence flag followed by ");
    out.push_str("the value when present. The one exception is an optional interface, which ");
    out.push_str("stays a nullable object pointer (`0` = absent).\n\n");
    out.push_str("### Lists and Maps\n\n");
    out.push_str("Lists are JS arrays; maps are plain objects (a `Map` instance is also ");
    out.push_str("accepted on input). Both cross the boundary serialized in a value buffer ");
    out.push_str("as one pointer + length pair, recursing through element types.\n\n");
    out.push_str("### Iterators\n\n");
    out.push_str("`iter<T>` functions return a **lazy JS iterator** (typed ");
    out.push_str("`IterableIterator<T>`): each `next()` issues exactly one producer call, so ");
    out.push_str("iteration streams in constant memory. The producer handle is destroyed ");
    out.push_str("exactly once, on exhaustion or via `return()` when iteration stops early ");
    out.push_str("(a `for...of` loop calls `return()` automatically on `break` or `throw`). ");
    out.push_str("Abandoning an iterator without exhausting or closing it leaks the handle.\n");
    if !emscripten && walk_modules(&api.modules).any(|m| !m.listeners.is_empty()) {
        out.push_str("\n### Callbacks and Listeners\n\n");
        out.push_str(
            "Each listener surfaces as a `register.../unregister...` pair. `register` \
             takes a plain JS function and returns a numeric subscription id; \
             `unregister` takes that id and stops delivery. Delivery is **synchronous \
             and same-thread**: `wasm32-unknown-unknown` is single-threaded, so events \
             fire only while a call into the module is on the stack (for example, a \
             producer function that emits during its own execution). A producer that \
             emits from a spawned thread cannot run on this target at all.\n\n",
        );
        out.push_str(
            "Callback arguments are **borrowed for the duration of the callback**: \
             strings, byte buffers, and buffered values (records, rich enums, \
             optionals, lists, maps) are copied or decoded into JS values before your \
             function runs, and interface arguments wrap producer-owned objects. Read \
             what you need inside the callback and do not retain an interface wrapper \
             or call `free()` on it.\n",
        );
    }
    out.push_str("\n### Error Handling\n\n");
    out.push_str("The generated JS wrappers automatically handle errors by passing an error\n");
    out.push_str("pointer as the last argument to each Wasm function. The error struct is\n");
    out.push_str("16 bytes on wasm32: `{ i32 code, char* message, uint8_t* payload_ptr,\n");
    out.push_str("size_t payload_len }`. Your Wasm module must export the following\n");
    out.push_str("functions:\n\n");
    out.push_str("- `weaveffi_alloc(size: i32) -> i32`: allocate `size` bytes in linear memory\n");
    out.push_str("- `weaveffi_dealloc(ptr: i32, size: i32)`: release a `weaveffi_alloc` block\n");
    out.push_str("- `weaveffi_error_clear(err_ptr: i32)`: clear and free error resources\n");
    out.push_str("- `weaveffi_free_string(ptr: i32)`: free a producer-returned C string\n");
    out.push_str("- `weaveffi_free_bytes(ptr: i32, len: i32)`: free a producer-returned buffer\n");
    out.push_str("\nWrappers of functions declared `throws` raise the declaring module's typed\n");
    out.push_str("error class (a `WeaveFFIError` subclass with a per-code subclass, such as\n");
    out.push_str("`KeyNotFound`); every other wrapper raises the generic `WeaveFFIError` only\n");
    out.push_str("for producer panics and marshalling failures. When the matched error code\n");
    out.push_str("declares payload fields, the wrapper decodes them from the error's value\n");
    out.push_str("buffer and attaches them as properties on the thrown error.\n");

    if !api.modules.is_empty() {
        render_api_reference(&mut out, api, model);
    }

    out.push('\n');
    out.push_str(&render_trailer(CommentStyle::Xml, "README.md"));
    out
}

/// Append the README's ABI-level API reference: one section per top-level
/// module covering its error domain, functions, interfaces, structs, and
/// enums.
fn render_api_reference(out: &mut String, api: &Api, model: &BindingModel) {
    let by_path: HashMap<&str, &ModuleBinding> =
        model.modules.iter().map(|m| (m.path.as_str(), m)).collect();
    out.push_str("\n## API Reference\n");
    for module in &api.modules {
        out.push_str(&format!("\n### Module: `{}`\n", module.name));
        let mb = by_path[module.name.as_str()];

        if let Some(eb) = mb.error.as_ref().filter(|eb| eb.declared_here) {
            render_error_ref(out, eb);
        }

        if !mb.functions.is_empty() {
            out.push_str("\n#### Functions\n");
            for f in &mb.functions {
                render_function_ref(out, f);
            }
        }

        if !mb.interfaces.is_empty() {
            out.push_str("\n#### Interfaces\n");
            for i in &mb.interfaces {
                render_interface_ref(out, i);
            }
        }

        if !mb.structs.is_empty() {
            out.push_str("\n#### Structs\n");
            for s in &mb.structs {
                render_struct_ref(out, s);
            }
        }

        if !mb.enums.is_empty() {
            out.push_str("\n#### Enums\n");
            for e in &mb.enums {
                render_enum_ref(out, e);
            }
        }
    }
}

/// Document a module's declared error domain: the JS class hierarchy it
/// generates, the stable ABI code of each subclass, and any structured
/// payload fields a code attaches to the thrown error.
fn render_error_ref(out: &mut String, eb: &ErrorBinding) {
    out.push_str(&format!("\n#### Error Domain: `{}`\n\n", eb.type_name));
    out.push_str(&format!(
        "Throwing wrappers in this module raise `{}` (a `{ERROR_BRAND}` subclass); \
         each code below is its own subclass carrying the stable `code`. Payload \
         fields are decoded from the error's value buffer and attached as \
         properties on the thrown error.\n\n",
        eb.type_name
    ));
    out.push_str("| Class | Code | Default Message | Payload Fields |\n");
    out.push_str("|-------|------|-----------------|----------------|\n");
    for c in &eb.codes {
        let fields = if c.fields.is_empty() {
            "(none)".to_string()
        } else {
            c.fields
                .iter()
                .map(|f| format!("`{}: {}`", f.name, type_display(&f.ty)))
                .collect::<Vec<_>>()
                .join(", ")
        };
        out.push_str(&format!(
            "| `{}` | `{}` | {} | {} |\n",
            js_code_class_name(&c.name),
            c.value,
            c.message,
            fields
        ));
    }
}

/// Document one interface: an opaque handle wrapped by a JS class, with the
/// member entry points listed at the ABI level like free functions.
fn render_interface_ref(out: &mut String, i: &InterfaceBinding) {
    out.push_str(&format!("\n##### `{}`\n\n", i.name));
    if let Some(doc) = &i.doc {
        out.push_str(doc);
        out.push_str("\n\n");
    }
    out.push_str(
        "Passed as an **opaque object pointer** (`i32`), wrapped by a JS class. \
         Constructors return an owned handle; methods pass the handle as the implicit \
         leading `self` argument; `free()` releases the handle via the destroy symbol.\n",
    );
    for f in i
        .constructors
        .iter()
        .chain(i.methods.iter())
        .chain(i.statics.iter())
    {
        render_function_ref(out, f);
    }
    out.push_str(&format!(
        "\n##### `{}`\n\nReleases the object reference. Called by the wrapper's `free()`.\n",
        i.destroy_symbol
    ));
}

/// Document one callable at the ABI level: its C signature in wasm value
/// types and a per-parameter table of API type, wasm slot type, and boundary
/// note.
fn render_function_ref(out: &mut String, f: &FnBinding) {
    let abi_name = &f.c_base;
    out.push_str(&format!("\n##### `{abi_name}`\n\n"));

    if let Some(doc) = &f.doc {
        out.push_str(doc);
        out.push_str("\n\n");
    }

    if let Some(msg) = &f.deprecated {
        out.push_str(&format!("**Deprecated:** {msg}\n\n"));
    }

    let params_sig: Vec<String> = f
        .params
        .iter()
        .map(|p| format!("{}: {}", p.name, wasm_type(&p.ty)))
        .collect();
    let ret_sig = f.ret.as_ref().map_or("void", wasm_type);
    out.push_str(&format!(
        "`{abi_name}({}) -> {ret_sig}`\n\n",
        params_sig.join(", ")
    ));

    out.push_str("| Param | API Type | Wasm | Notes |\n");
    out.push_str("|-------|----------|------|-------|\n");
    for param in &f.params {
        out.push_str(&format!(
            "| `{}` | `{}` | `{}` | {} |\n",
            param.name,
            type_display(&param.ty),
            wasm_type(&param.ty),
            wasm_type_note(&param.ty)
        ));
    }
    if let Some(ret) = &f.ret {
        out.push_str(&format!(
            "| _returns_ | `{}` | `{}` | {} |\n",
            type_display(ret),
            wasm_type(ret),
            wasm_type_note(ret)
        ));
    }
}

/// Document one record: a plain JS object serialized in a value buffer, with
/// its field schema in declaration (wire) order.
fn render_struct_ref(out: &mut String, s: &StructBinding) {
    out.push_str(&format!("\n##### `{}`\n\n", s.name));

    if let Some(doc) = &s.doc {
        out.push_str(doc);
        out.push_str("\n\n");
    }

    out.push_str(
        "A plain JS object, serialized in a value buffer (`i32` ptr + `i32` len) at \
         the boundary. Fields in declaration (wire) order:\n\n",
    );

    if !s.fields.is_empty() {
        out.push_str("| Field | Type |\n");
        out.push_str("|-------|------|\n");
        for field in &s.fields {
            out.push_str(&format!(
                "| `{}` | `{}` |\n",
                field.name,
                type_display(&field.ty)
            ));
        }
    }
}

/// Document one enum: a variant/value table for a C-style enum, or the
/// tagged-object union shape for a rich one.
fn render_enum_ref(out: &mut String, e: &EnumBinding) {
    out.push_str(&format!("\n##### `{}`\n\n", e.name));

    if let Some(doc) = &e.doc {
        out.push_str(doc);
        out.push_str("\n\n");
    }

    if e.is_rich() {
        render_rich_enum_ref(out, e);
        return;
    }

    out.push_str("Passed as `i32` discriminant.\n\n");
    out.push_str("| Variant | Value |\n");
    out.push_str("|---------|-------|\n");
    for v in &e.variants {
        out.push_str(&format!("| `{}` | `{}` |\n", v.name, v.value));
    }
}

/// Document a rich (algebraic) enum: a plain tagged object serialized in a
/// value buffer as an `i32` tag followed by the active variant's fields, not
/// a by-value `i32` discriminant like a plain enum.
fn render_rich_enum_ref(out: &mut String, e: &EnumBinding) {
    out.push_str(
        "Rich (algebraic) enum: a plain tagged object (`{ tag: \"Variant\", ...fields }`) \
         serialized in a value buffer as an `i32` tag followed by the active variant's \
         fields in declaration order.\n\n",
    );
    out.push_str("| Variant | Tag | Fields |\n");
    out.push_str("|---------|-----|--------|\n");
    for v in &e.variants {
        let fields = if v.fields.is_empty() {
            "(none)".to_string()
        } else {
            v.fields
                .iter()
                .map(|f| format!("`{}: {}`", f.name, type_display(&f.ty)))
                .collect::<Vec<_>>()
                .join(", ")
        };
        out.push_str(&format!("| `{}` | `{}` | {} |\n", v.name, v.value, fields));
    }
}
