//! Target-specific tests: names derived from the identity and the config,
//! escaping, and the generated-file markers. The `kitchen_sink` snapshot pins
//! the rendered bindings themselves.

use weaveffi_model::model::Model;
use weaveffi_model::pkg::Identity;
use weaveffi_model::validate::validate;

use super::{render_files, GoConfig};

const FIXTURE: &str = r#"
version: "0.12.0"
modules:
  - name: shop
    errors:
      - name: ShopErrors
        codes:
          - { name: out_of_stock, code: 1, message: "out of stock", fields: [{ name: message, type: string }] }
    interfaces:
      - name: Cart
        constructors: [{ name: new, params: [{ name: range, type: string }] }]
        methods:
          - { name: close, params: [] }
          - { name: add, params: [{ name: s, type: i32 }] }
    functions:
      - { name: open_cart, params: [], return: Cart }
      - { name: check, params: [{ name: context, type: i32 }], throws: ShopErrors }
"#;

fn model() -> Model {
    let api = weaveffi_model::parse::parse_api_str(FIXTURE, "yaml").unwrap();
    validate(&api, &Identity::named("shop_kit"), None).unwrap()
}

fn render(config: GoConfig) -> Vec<(String, String)> {
    render_files(&model(), &config)
}

fn file<'a>(files: &'a [(String, String)], name: &str) -> &'a str {
    files
        .iter()
        .find(|(n, _)| n == name)
        .map(|(_, c)| c.as_str())
        .unwrap_or_else(|| panic!("no {name}"))
}

#[track_caller]
fn assert_has(out: &str, needle: &str) {
    assert!(out.contains(needle), "missing {needle:?} in:\n{out}");
}

#[test]
fn names_come_from_the_identity() {
    let files = render(GoConfig::default());
    let names: Vec<&str> = files.iter().map(|(n, _)| n.as_str()).collect();
    assert_eq!(
        names,
        [
            "go.mod",
            "README.md",
            "shop_kit.h",
            "bindings.go",
            "runtime.go",
            "codec.go"
        ]
    );
    assert_has(file(&files, "go.mod"), "module shop_kit\n\ngo 1.24\n");
    let src = file(&files, "bindings.go");
    assert_has(
        src,
        "// Package shopkit binds the shop_kit native library.\n",
    );
    assert_has(src, "\npackage shopkit\n");
    assert_has(src, "#cgo LDFLAGS: -lshop_kit\n");
    assert_has(src, "#include \"shop_kit.h\"\n");
    assert_has(file(&files, "runtime.go"), "\npackage shopkit\n");
    assert_has(file(&files, "codec.go"), "\npackage shopkit\n");
}

#[test]
fn the_config_names_the_module_and_the_package() {
    let files = render(GoConfig {
        name: Some("example.com/shop".into()),
        package: Some("shop".into()),
    });
    assert_has(file(&files, "go.mod"), "module example.com/shop\n");
    assert_has(file(&files, "bindings.go"), "\npackage shop\n");
    assert_has(file(&files, "README.md"), "import \"example.com/shop\"");

    // A keyword is escaped, and blank values fall back to the defaults.
    let files = render(GoConfig {
        name: Some("  ".into()),
        package: Some("select".into()),
    });
    assert_has(file(&files, "go.mod"), "module shop_kit\n");
    assert_has(file(&files, "bindings.go"), "\npackage select_\n");
}

#[test]
fn every_go_file_is_marked_generated() {
    for (name, contents) in render(GoConfig::default()) {
        if !name.ends_with(".go") {
            continue;
        }
        let marker = contents
            .lines()
            .position(|l| l == "// Code generated by WeaveFFI. DO NOT EDIT.")
            .unwrap_or_else(|| panic!("{name} has no generated-code marker"));
        let package = contents
            .lines()
            .position(|l| l.starts_with("package "))
            .unwrap();
        assert!(
            marker < package,
            "{name}: the marker must precede the package clause"
        );
        assert!(!contents.contains("{{"), "{name} has a placeholder");
    }
}

#[test]
fn identifiers_avoid_keywords_and_generated_names() {
    let files = render(GoConfig::default());
    let src = file(&files, "bindings.go");
    // A method named like the wrapper's Close, parameters named like Go
    // keywords or body locals, and a function named like the runtime's
    // Check.
    assert_has(src, "func (s *Cart) Close_() {");
    assert_has(src, "func (s *Cart) Add(s_ int32) {");
    assert_has(src, "func NewCart(range_ string) *Cart {");
    assert_has(src, "func ShopCheck(context_ int32) error {");
    // A payload field named like the error's Message field.
    assert_has(src, "\tMessage_ string\n");
    // The domain takes the shared name; its unknown codes have their own type.
    assert_has(src, "type ShopError interface {");
    assert_has(src, "type UnknownShopError struct {");
    assert_has(src, "type OutOfStockError struct {");
}

#[test]
fn output_is_deterministic() {
    assert_eq!(render(GoConfig::default()), render(GoConfig::default()));
}
