//! .NET-specific rendering tests: project naming and configuration, the
//! spliced runtime, identifier escaping, and runtime-class collisions. The
//! `kitchen_sink` snapshot pins the rest of the generated API.

use crate::package::PackageContext;
use crate::platform::{BinarySet, NativeBinary, Platform};
use crate::targets::Target;
use weaveffi_model::ir::Api;
use weaveffi_model::model::Model;
use weaveffi_model::pkg::Identity;
use weaveffi_model::validate::validate;

use crate::targets::dotnet::{DotnetConfig, DotnetGenerator};

/// A `bus` module whose names collide with what the generated C# declares
/// or reserves: a record field spelled like its record and like synthesized
/// record members, keyword parameters, an interface member spelled like the
/// wrapper's `Dispose`, a code field spelled like `Exception.Message`, and a
/// record named like the runtime's root exception.
const FIXTURE: &str = r#"
version: "0.12.0"
modules:
  - name: bus
    errors:
      - name: BusError
        codes:
          - { name: Closed, code: 1, message: "bus \"closed\"" }
          - { name: Full, code: 2, message: "bus full", fields: [{ name: message, type: string }] }
    structs:
      - name: Token
        fields:
          - { name: token, type: i64 }
          - { name: to_string, type: string }
          - { name: tags, type: "[string]" }
      - name: NativeException
        fields:
          - { name: code, type: i32 }
    interfaces:
      - name: Ticker
        constructors:
          - { name: new, params: [{ name: start, type: i32 }] }
        methods:
          - { name: dispose, params: [{ name: class, type: bool }] }
          - { name: ticker, return: i32 }
    functions:
      - { name: send, params: [{ name: event, type: string }, { name: in, type: "i32?" }], return: Token, throws: BusError }
"#;

fn fixture() -> Model {
    let api: Api = serde_yaml_ng::from_str(FIXTURE).expect("fixture parses");
    validate(&api, &Identity::named("bus-lib"), None).expect("fixture validates")
}

/// Every generated file's text, keyed by file name.
fn render_files(config: &DotnetConfig) -> Vec<(String, String)> {
    DotnetGenerator::from(config.clone())
        .render(&fixture())
        .into_iter()
        .map(|f| (f.path.to_string(), f.contents))
        .collect()
}

fn file(files: &[(String, String)], name: &str) -> String {
    files
        .iter()
        .find(|(n, _)| n == name)
        .unwrap_or_else(|| {
            panic!(
                "no {name} in {:?}",
                files.iter().map(|f| &f.0).collect::<Vec<_>>()
            )
        })
        .1
        .clone()
}

#[track_caller]
fn assert_has(out: &str, needle: &str) {
    assert!(out.contains(needle), "missing `{needle}` in:\n{out}");
}

#[test]
fn names_come_from_the_identity() {
    let files = render_files(&DotnetConfig::default());
    let names: Vec<&str> = files.iter().map(|f| f.0.as_str()).collect();
    assert_eq!(
        names,
        ["BusLib.cs", "Runtime.cs", "BusLib.csproj", "README.md"]
    );
    let runtime = file(&files, "Runtime.cs");
    assert_has(&runtime, "namespace BusLib;");
    assert_has(&runtime, "internal const string LibName = \"bus_lib\";");
    assert_has(
        &runtime,
        "internal const string LibraryEnvVar = \"BUS_LIB_LIBRARY\";",
    );
    assert_has(&runtime, "\"bus_lib_abi_version\"");
    assert_has(&runtime, "public static class BusLibLibrary");
    assert_has(&runtime, "public const uint AbiVersion = 5;");
    assert!(
        !runtime.contains("{{"),
        "unreplaced placeholder:\n{runtime}"
    );
    let csproj = file(&files, "BusLib.csproj");
    assert_has(&csproj, "<AssemblyName>BusLib</AssemblyName>");
    assert_has(&csproj, "<PackageId>BusLib</PackageId>");
    assert_has(&csproj, "<TargetFramework>net8.0</TargetFramework>");
    assert_has(&file(&files, "README.md"), "`BusLibLibrary.Check()`");
    for (name, text) in &files {
        let body: String = text
            .lines()
            .filter(|l| !l.contains("Generated by WeaveFFI") && !l.contains("weaveffi generate"))
            .collect();
        assert!(
            !body.to_lowercase().contains("weaveffi"),
            "{name} is branded:\n{text}"
        );
    }
}

#[test]
fn configured_namespace_wins() {
    let config = DotnetConfig {
        name: Some("Acme.Bus".into()),
    };
    let files = render_files(&config);
    assert_has(&file(&files, "Acme.Bus.cs"), "namespace Acme.Bus;");
    assert_has(
        &file(&files, "Acme.Bus.csproj"),
        "<PackageId>Acme.Bus</PackageId>",
    );
    // The library class takes the namespace's last segment.
    assert_has(
        &file(&files, "Runtime.cs"),
        "public static class BusLibrary",
    );
}

#[test]
fn runtime_classes_step_around_api_types() {
    let files = render_files(&DotnetConfig::default());
    let runtime = file(&files, "Runtime.cs");
    // The API declares a `NativeException` record.
    assert_has(&runtime, "public class BusLibNativeException : Exception");
    assert_has(&runtime, "public sealed class NativeBugException");
    let api = file(&files, "BusLib.cs");
    assert_has(&api, "public sealed record NativeException(int Code)");
    assert_has(&api, "public class BusException : BusLibNativeException");
}

#[test]
fn identifiers_are_escaped() {
    let api = file(&render_files(&DotnetConfig::default()), "BusLib.cs");
    // Record properties never collide with the record or its members.
    assert_has(
        &api,
        "public sealed record Token(long Token_, string ToString_, IReadOnlyList<string> Tags)",
    );
    // Keywords are verbatim identifiers; locals derive from the bare name.
    assert_has(&api, "public static Token Send(string @event, int? @in)");
    assert_has(&api, "using var eventUtf8 = new FfiUtf8(@event);");
    assert_has(&api, "public void Dispose_(bool @class)");
    assert_has(&api, "public int Ticker_()");
    // A code field spelled like `Exception.Message` and a quoted message.
    assert_has(&api, "public string Message_ { get; }");
    assert_has(
        &api,
        "public Full(string message_, string? message = null) : base(ErrorCode, message ?? \"bus full\")",
    );
    assert_has(&api, "message ?? \"bus \\\"closed\\\"\"");
}

#[test]
fn output_is_deterministic() {
    assert_eq!(
        render_files(&DotnetConfig::default()),
        render_files(&DotnetConfig::default())
    );
}

#[test]
fn package_bundles_desktop_runtimes_only() {
    let model = fixture();
    let mut binaries = BinarySet::new("bus_lib");
    for p in Platform::ALL {
        binaries.insert(NativeBinary::new(p, format!("/tmp/{}/lib", p.id())));
    }
    let ctx = PackageContext::new(&binaries);
    let artifacts = DotnetGenerator::from(DotnetConfig::default())
        .package(&model, &ctx)
        .expect("dotnet packages");
    assert_eq!(artifacts.len(), 1);
    assert_eq!(artifacts[0].path, "dotnet/BusLib");
    assert!(artifacts[0].file("BusLib.csproj").is_some());
    let paths: Vec<String> = artifacts[0]
        .files
        .iter()
        .map(|f| f.path.to_string())
        .collect();
    let native: Vec<&String> = paths
        .iter()
        .filter(|p| p.starts_with("runtimes/"))
        .collect();
    assert_eq!(native.len(), Platform::DESKTOP.len(), "{paths:?}");
    for rid in [
        "osx-arm64",
        "osx-x64",
        "linux-x64",
        "linux-arm64",
        "win-x64",
    ] {
        assert!(
            paths
                .iter()
                .any(|p| p.starts_with(&format!("runtimes/{rid}/native/"))),
            "{paths:?}"
        );
    }
    assert!(!paths
        .iter()
        .any(|p| p.contains("android") || p.contains("wasm")));
}
