//! Target-specific unit tests: the gem layout and configuration, the
//! runtime's substitutions, Ruby naming and escaping, the private
//! boundary, and packaging. The `kitchen_sink` snapshot pins everything
//! else.

use weaveffi_model::ir::Api;
use weaveffi_model::model::Model;
use weaveffi_model::pkg::Identity;
use weaveffi_model::validate::validate;

use super::{RubyConfig, RubyGenerator};
use crate::codegen::OutputFile;
use crate::package::{ArtifactKind, PackageContext};
use crate::platform::{BinarySet, NativeBinary, Platform};
use crate::targets::Target;

/// An interface, a callback interface, a record and an error code with
/// fields named like the methods records and errors rely on, types named
/// like constants the bindings use, members named like wrapper methods, and
/// a cancellable function with a `cancel` parameter.
const FIXTURE: &str = r#"
version: "0.12.0"
modules:
  - name: shop
    errors:
      - name: Error
        codes:
          - { name: Broken, code: 1, message: "broken", fields: [{ name: code, type: i32 }, { name: message, type: string }] }
    structs:
      - name: Data
        fields:
          - { name: hash, type: i64 }
          - { name: end, type: i32 }
    interfaces:
      - name: Cart
        constructors:
          - { name: allocate, params: [] }
        methods:
          - { name: close, params: [], return: bool }
          - { name: initialize, params: [] }
          - { name: name, params: [], return: string }
        statics:
          - { name: new, params: [], return: Cart }
          - { name: label, params: [], return: string }
    callback_interfaces:
      - name: Watcher
        methods:
          - { name: hash, params: [{ name: end, type: i32 }], return: i64 }
    functions:
      - { name: name, params: [], return: string }
      - { name: watch, params: [{ name: watcher, type: Watcher }] }
      - { name: wait, params: [{ name: cancel, type: i64 }], return: i64, async: true, cancellable: true }
      - { name: fix, params: [{ name: d, type: Data }], return: Data, throws: Error }
"#;

fn model() -> Model {
    let api: Api = serde_yaml_ng::from_str(FIXTURE).unwrap();
    validate(&api, &Identity::named("shop_kit"), None).unwrap()
}

fn generate(config: &RubyConfig) -> Vec<OutputFile> {
    RubyGenerator::from(config.clone()).render(&model())
}

fn file<'a>(files: &'a [OutputFile], path: &str) -> &'a str {
    &files
        .iter()
        .find(|f| f.path.as_str() == path)
        .unwrap_or_else(|| {
            panic!(
                "no {path} in {:?}",
                files.iter().map(|f| &f.path).collect::<Vec<_>>()
            )
        })
        .contents
}

fn bindings() -> String {
    file(&generate(&RubyConfig::default()), "lib/shop_kit.rb").to_string()
}

#[track_caller]
fn assert_has(src: &str, needle: &str) {
    assert!(src.contains(needle), "missing {needle:?} in:\n{src}");
}

#[test]
fn layout_follows_the_identity() {
    let files = generate(&RubyConfig::default());
    let paths: Vec<&str> = files.iter().map(|f| f.path.as_str()).collect();
    assert_eq!(
        paths,
        [
            "lib/shop_kit.rb",
            "lib/shop_kit/runtime.rb",
            "shop_kit.gemspec",
            "README.md",
        ]
    );
    let spec = file(&files, "shop_kit.gemspec");
    assert_has(spec, "s.name        = 'shop_kit'");
    assert_has(spec, "s.required_ruby_version = '>= 3.2'");
    let src = file(&files, "lib/shop_kit.rb");
    assert_has(src, "require_relative 'shop_kit/runtime'");
    assert_has(src, "module ShopKit\n");
    // Nothing but the generated-file banner mentions WeaveFFI.
    for f in &files {
        for line in f.contents.lines().filter(|l| {
            !l.contains("Generated by WeaveFFI") && !l.contains("To regenerate: weaveffi generate")
        }) {
            assert!(
                !line.to_ascii_lowercase().contains("weaveffi"),
                "branded line in {}: {line}",
                f.path
            );
        }
    }
}

#[test]
fn config_overrides_gem_and_module_names() {
    let config = RubyConfig {
        name: Some("acme-shop".into()),
        module_name: Some("Acme".into()),
    };
    let files = generate(&config);
    assert_has(
        file(&files, "acme-shop.gemspec"),
        "s.name        = 'acme-shop'",
    );
    // The require path stays the identity prefix.
    assert_has(file(&files, "lib/shop_kit.rb"), "module Acme\n");
    let rt = file(&files, "lib/shop_kit/runtime.rb");
    assert_has(rt, "module Acme\n");
    assert_has(rt, "raise Acme::LoadError,");
}

#[test]
fn runtime_substitutes_the_identity_and_abi_revision() {
    let rt = file(&generate(&RubyConfig::default()), "lib/shop_kit/runtime.rb").to_string();
    assert_has(&rt, "ENV.fetch('SHOP_KIT_LIBRARY', '')");
    assert_has(&rt, "'libshop_kit.dylib'");
    assert_has(&rt, "'libshop_kit.so'");
    assert_has(&rt, "'shop_kit.dll'");
    assert_eq!(crate::cabi::ABI_VERSION, 5);
    assert_has(&rt, "ABI_VERSION = 5\n");
    assert_has(
        &rt,
        "attach_function :shop_kit_error_set, [:pointer, :int32, :pointer, :size_t], :void",
    );
    assert!(!rt.contains("{{"), "an unsubstituted placeholder:\n{rt}");
}

#[test]
fn only_the_idiomatic_api_is_public() {
    let src = bindings();
    // Every C function is attached inside the private Native module, and
    // no wrapper defines a helper of its own.
    let native_start = src.find("  module Native\n").expect("a Native module");
    let native_end = native_start + src[native_start..].find("\n  end\n").unwrap();
    for (at, _) in src.match_indices("attach_function") {
        assert!(
            (native_start..native_end).contains(&at),
            "attach_function outside Native:\n{src}"
        );
    }
    assert!(!src.contains("def self._wv"), "a public helper:\n{src}");
    assert!(
        !src.contains("FFI::Struct"),
        "a per-interface struct:\n{src}"
    );
}

#[test]
fn names_never_replace_what_the_bindings_rely_on() {
    let src = bindings();
    for needle in [
        // Types named like constants the bindings use.
        "class Error_ < Error\n",
        "Data_ = Data.define(:hash_, :end)\n",
        "Bridge.record(Data_, hash_: :i64, end: :i32)\n",
        // Error fields named like Error's own methods.
        "attr_reader :code_\n",
        "attr_reader :message_\n",
        "Bridge.record(Error_::Broken, code_: :i32, message_: :string)\n",
        // Members named like the wrapper's or the class's own methods.
        "def self.allocate_\n",
        "def close_\n",
        "def initialize_\n",
        "def name\n",
        "def self.new_\n",
        "def self.label\n",
        // A module function named like Module#name.
        "def self.name_\n",
        // A callback method named like Object#hash.
        "def hash_(end_)\n",
        ".hash_(end_)",
        // A parameter named like the cancellable keyword.
        "def self.wait(cancel_, cancel: nil)\n",
    ] {
        assert_has(&src, needle);
    }
}

#[test]
fn rendering_is_deterministic() {
    assert_eq!(bindings(), bindings());
}

#[test]
fn package_skips_platforms_without_a_gem_string() {
    let model = model();
    let mut binaries = BinarySet::new("shop_kit");
    for (platform, path) in [
        (Platform::MacosArm64, "/tmp/darwin-arm64/libshop_kit.dylib"),
        (Platform::AndroidArm64, "/tmp/android-arm64/libshop_kit.so"),
        (Platform::Wasm32, "/tmp/wasm32/shop_kit.wasm"),
    ] {
        binaries.insert(NativeBinary::new(platform, path));
    }
    let ctx = PackageContext::new(&binaries);
    let artifacts = RubyGenerator::from(RubyConfig::default())
        .package(&model, &ctx)
        .expect("ruby supports packaging");
    assert_eq!(artifacts.len(), 1, "{artifacts:?}");
    let gem = &artifacts[0];
    assert_eq!(gem.path, "ruby/shop_kit-0.1.0-arm64-darwin.gem");
    let ArtifactKind::Gem(spec) = &gem.kind else {
        panic!("a gem");
    };
    assert_eq!(spec.platform, "arm64-darwin");
    assert_eq!(spec.required_ruby_version, ">= 3.2");
    assert_eq!(
        spec.dependencies,
        [("ffi".to_string(), "~> 1.16".to_string())]
    );
    let paths: Vec<&str> = gem.files.iter().map(|f| f.path.as_str()).collect();
    assert_eq!(
        paths,
        [
            "lib/shop_kit.rb",
            "lib/shop_kit/runtime.rb",
            "lib/native/libshop_kit.dylib",
            "README.md",
        ]
    );
}
