//! Snapshot tests covering every generator against a small, feature-complete
//! IDL corpus.
//!
//! Four fixtures cover the whole IDL surface between them: `kitchen_sink`
//! (every scalar and composite type, borrowed params, handles, an interface,
//! callbacks and a listener, an error domain, iterators, async and
//! cancellable functions, deprecation, and a nested submodule), `shapes`
//! (rich enums and the full numeric primitive set), `nested_modules` (a
//! three-deep module tree with cross-module references), and
//! `docs_everywhere` (doc comments on every declaration kind). One test per
//! generator runs it over all four fixtures into a fresh tempdir, walks the
//! resulting files in sorted order, and snapshots each file under
//! `tests/snapshots/`. Regressions in any generator's output fail the
//! affected `cargo insta test` job; behavioral regressions are the
//! conformance harness's job.

use std::fs;
use std::path::{Path, PathBuf};

use camino::Utf8Path;
use weaveffi_core::codegen::{ConfiguredBackend, Target};
use weaveffi_core::resolved::ResolvedApi;
use weaveffi_core::validate::validate_api;
use weaveffi_gen_android::{AndroidConfig, AndroidGenerator};
use weaveffi_gen_c::{CConfig, CGenerator};
use weaveffi_gen_cpp::{CppConfig, CppGenerator};
use weaveffi_gen_dart::{DartConfig, DartGenerator};
use weaveffi_gen_dotnet::{DotnetConfig, DotnetGenerator};
use weaveffi_gen_go::{GoConfig, GoGenerator};
use weaveffi_gen_node::{NodeConfig, NodeGenerator};
use weaveffi_gen_python::{PythonConfig, PythonGenerator};
use weaveffi_gen_ruby::{RubyConfig, RubyGenerator};
use weaveffi_gen_swift::{SwiftConfig, SwiftGenerator};
use weaveffi_gen_wasm::{WasmConfig, WasmGenerator};
use weaveffi_ir::parse::parse_api_str;

const FIXTURES: [&str; 4] = [
    "kitchen_sink",
    "shapes",
    "nested_modules",
    "docs_everywhere",
];

fn load_api(stem: &str) -> ResolvedApi {
    let path = Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("tests/fixtures")
        .join(format!("{stem}.yml"));
    let contents = fs::read_to_string(&path)
        .unwrap_or_else(|e| panic!("read fixture {}: {e}", path.display()));
    let api = parse_api_str(&contents, "yaml")
        .unwrap_or_else(|e| panic!("parse fixture {}: {e}", path.display()));
    validate_api(api, None).unwrap_or_else(|e| panic!("validate fixture {}: {e}", path.display()))
}

fn collect_files_sorted(root: &Path) -> Vec<PathBuf> {
    fn walk(dir: &Path, out: &mut Vec<PathBuf>) {
        let Ok(entries) = fs::read_dir(dir) else {
            return;
        };
        for entry in entries.flatten() {
            let path = entry.path();
            if path.is_dir() {
                walk(&path, out);
            } else if path.is_file() {
                out.push(path);
            }
        }
    }
    let mut out = Vec::new();
    walk(root, &mut out);
    out.sort();
    out
}

fn sanitize(rel: &Path) -> String {
    rel.to_string_lossy().replace(['/', '\\', '.', '-'], "_")
}

/// Replace the concrete crate version in every WeaveFFI prelude
/// (`Generated by WeaveFFI 0.21.0 from ...`) with a stable `[VERSION]`
/// placeholder so a release bump does not invalidate every snapshot.
fn redact_version(s: &str) -> String {
    const MARKER: &str = "Generated by WeaveFFI ";
    let mut out = String::with_capacity(s.len());
    let mut rest = s;
    while let Some(idx) = rest.find(MARKER) {
        out.push_str(&rest[..idx + MARKER.len()]);
        rest = &rest[idx + MARKER.len()..];
        let end = rest.find(char::is_whitespace).unwrap_or(rest.len());
        out.push_str("[VERSION]");
        rest = &rest[end..];
    }
    out.push_str(rest);
    out
}

/// Every generated file embeds the standard WeaveFFI prelude markers in its
/// first five lines. JSON files (which cannot carry comments) embed these
/// markers via the `"//"` key convention.
fn assert_prelude_present(contents: &str, file: &Path) {
    let head: String = contents.lines().take(5).collect::<Vec<_>>().join("\n");
    for marker in ["Generated by WeaveFFI", "DO NOT EDIT"] {
        assert!(
            head.contains(marker),
            "{} is missing '{marker}' in the first 5 lines:\n{head}",
            file.display(),
        );
    }
}

fn run_snapshots(target: &dyn Target) {
    for stem in FIXTURES {
        let api = load_api(stem);
        let tmp = tempfile::tempdir().expect("create tempdir");
        let out_dir = Utf8Path::from_path(tmp.path()).expect("utf8 tempdir");
        target.generate(&api, out_dir).expect("generator failed");

        let root = out_dir.join(target.name());
        let files = collect_files_sorted(root.as_std_path());
        assert!(
            !files.is_empty(),
            "generator {} produced no files for fixture {stem}",
            target.name(),
        );

        insta::with_settings!({
            snapshot_path => "snapshots",
            prepend_module_to_snapshot => false,
            omit_expression => true,
        }, {
            for file in files {
                let rel = file
                    .strip_prefix(root.as_std_path())
                    .expect("file under generator root");
                let name = format!("{}_{stem}__{}", target.name(), sanitize(rel));
                let contents = fs::read_to_string(&file)
                    .unwrap_or_else(|e| panic!("read {}: {e}", file.display()));
                insta::assert_snapshot!(name, redact_version(&contents));
                assert_prelude_present(&contents, &file);
            }
        });
    }
}

macro_rules! snapshot_tests {
    ($( $fn_name:ident => $gen:expr, $cfg:ty; )*) => {
        $(
            #[test]
            fn $fn_name() {
                run_snapshots(&ConfiguredBackend::new($gen, <$cfg>::default()));
            }
        )*
    };
}

snapshot_tests! {
    snapshot_c => CGenerator, CConfig;
    snapshot_cpp => CppGenerator, CppConfig;
    snapshot_swift => SwiftGenerator, SwiftConfig;
    snapshot_android => AndroidGenerator, AndroidConfig;
    snapshot_node => NodeGenerator, NodeConfig;
    snapshot_wasm => WasmGenerator, WasmConfig;
    snapshot_python => PythonGenerator, PythonConfig;
    snapshot_dotnet => DotnetGenerator, DotnetConfig;
    snapshot_dart => DartGenerator, DartConfig;
    snapshot_go => GoGenerator, GoConfig;
    snapshot_ruby => RubyGenerator, RubyConfig;
}
