//! Snapshot tests covering every generator against a representative IDL corpus.
//!
//! Each test parses a fixture, runs a single generator into a fresh tempdir,
//! walks the resulting files in sorted order, and snapshots their contents
//! one-file-per-snapshot under `tests/snapshots/`. Regressions in any
//! generator's output cause the affected `cargo insta test` job to fail.

use std::fs;
use std::path::{Path, PathBuf};

use camino::Utf8Path;
use weaveffi_core::codegen::{ConfiguredGenerator, DynGenerator, Generator};
use weaveffi_core::validate::validate_api;
use weaveffi_gen_android::{AndroidConfig, AndroidGenerator};
use weaveffi_gen_c::{CConfig, CGenerator};
use weaveffi_gen_cpp::{CppConfig, CppGenerator};
use weaveffi_gen_dart::{DartConfig, DartGenerator};
use weaveffi_gen_dotnet::{DotnetConfig, DotnetGenerator};
use weaveffi_gen_go::{GoConfig, GoGenerator};
use weaveffi_gen_node::{NodeConfig, NodeGenerator};
use weaveffi_gen_python::{PythonConfig, PythonGenerator};
use weaveffi_gen_ruby::{RubyConfig, RubyGenerator};
use weaveffi_gen_swift::{SwiftConfig, SwiftGenerator};
use weaveffi_gen_wasm::{WasmConfig, WasmGenerator};
use weaveffi_ir::ir::Api;
use weaveffi_ir::parse::parse_api_str;

fn fixture_path(file: &str) -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("tests/fixtures")
        .join(file)
}

fn load_api(file: &str) -> Api {
    let path = fixture_path(file);
    let contents = fs::read_to_string(&path)
        .unwrap_or_else(|e| panic!("read fixture {}: {e}", path.display()));
    let mut api = parse_api_str(&contents, "yaml")
        .unwrap_or_else(|e| panic!("parse fixture {}: {e}", path.display()));
    validate_api(&mut api, None)
        .unwrap_or_else(|e| panic!("validate fixture {}: {e}", path.display()));
    api
}

fn collect_files_sorted(root: &Path) -> Vec<PathBuf> {
    let mut out = Vec::new();
    walk(root, &mut out);
    out.sort();
    out
}

fn walk(dir: &Path, out: &mut Vec<PathBuf>) {
    let entries = match fs::read_dir(dir) {
        Ok(e) => e,
        Err(_) => return,
    };
    for entry in entries.flatten() {
        let path = entry.path();
        if path.is_dir() {
            walk(&path, out);
        } else if path.is_file() {
            out.push(path);
        }
    }
}

fn sanitize(rel: &Path) -> String {
    rel.to_string_lossy().replace(['/', '\\', '.', '-'], "_")
}

/// Replace the concrete crate version in every WeaveFFI prelude
/// (`Generated by WeaveFFI 0.5.0 from ...`) with a stable `[VERSION]`
/// placeholder. Without this, bumping the crate version invalidates all
/// 300+ generator snapshots even though no generated logic changed.
fn redact_version(s: &str) -> String {
    const MARKER: &str = "Generated by WeaveFFI ";
    let mut out = String::with_capacity(s.len());
    let mut rest = s;
    while let Some(idx) = rest.find(MARKER) {
        out.push_str(&rest[..idx + MARKER.len()]);
        rest = &rest[idx + MARKER.len()..];
        let end = rest.find(char::is_whitespace).unwrap_or(rest.len());
        out.push_str("[VERSION]");
        rest = &rest[end..];
    }
    out.push_str(rest);
    out
}

fn run_snapshot<G: Generator>(gen: &G, fixture_stem: &str, fixture_file: &str)
where
    G::Config: Default,
{
    let api = load_api(fixture_file);
    let tmp = tempfile::tempdir().expect("create tempdir");
    let out_dir = Utf8Path::from_path(tmp.path()).expect("utf8 tempdir");
    let config = G::Config::default();
    gen.generate(&api, out_dir, &config)
        .expect("generator failed");

    let gen_root = out_dir.join(gen.name());
    let files = collect_files_sorted(gen_root.as_std_path());
    assert!(
        !files.is_empty(),
        "generator {} produced no files for fixture {}",
        gen.name(),
        fixture_file,
    );

    insta::with_settings!({
        snapshot_path => "snapshots",
        prepend_module_to_snapshot => false,
        omit_expression => true,
    }, {
        for file in files {
            let rel = file
                .strip_prefix(gen_root.as_std_path())
                .expect("file under gen root");
            let name = format!("{}_{}__{}", gen.name(), fixture_stem, sanitize(rel));
            let contents = fs::read_to_string(&file)
                .unwrap_or_else(|e| panic!("read {}: {e}", file.display()));
            // Snapshot the version-redacted form so a release bump (e.g.
            // 0.5.0 → 0.6.0) does not invalidate every snapshot; assert the
            // real prelude (with the concrete version) against the original.
            insta::assert_snapshot!(name, redact_version(&contents));
            assert_prelude_present(&contents, &file);
        }
    });
}

/// Asserts every generated file embeds the standard WeaveFFI prelude markers
/// in its first five lines. JSON files (which cannot carry comments) embed
/// these markers via the `"//"` key convention.
fn assert_prelude_present(contents: &str, file: &Path) {
    let head: String = contents.lines().take(5).collect::<Vec<_>>().join("\n");
    assert!(
        head.contains("Generated by WeaveFFI"),
        "{} is missing 'Generated by WeaveFFI' in the first 5 lines:\n{head}",
        file.display(),
    );
    assert!(
        head.contains("DO NOT EDIT"),
        "{} is missing 'DO NOT EDIT' in the first 5 lines:\n{head}",
        file.display(),
    );
}

macro_rules! snapshot_test {
    ($fn_name:ident, $gen_expr:expr, $fixture_stem:literal, $fixture_file:literal) => {
        #[test]
        fn $fn_name() {
            run_snapshot(&$gen_expr, $fixture_stem, $fixture_file);
        }
    };
}

snapshot_test!(
    snapshot_c_calculator,
    CGenerator,
    "calculator",
    "01_calculator.yml"
);
snapshot_test!(
    snapshot_c_contacts,
    CGenerator,
    "contacts",
    "02_contacts.yml"
);
snapshot_test!(
    snapshot_c_inventory,
    CGenerator,
    "inventory",
    "03_inventory.yml"
);
snapshot_test!(
    snapshot_c_async_demo,
    CGenerator,
    "async_demo",
    "04_async_demo.yml"
);
snapshot_test!(snapshot_c_events, CGenerator, "events", "05_events.yml");
snapshot_test!(
    snapshot_c_kitchen_sink,
    CGenerator,
    "kitchen_sink",
    "06_kitchen_sink.yml"
);
snapshot_test!(
    snapshot_c_docs_everywhere,
    CGenerator,
    "docs_everywhere",
    "07_docs_everywhere.yml"
);
snapshot_test!(snapshot_c_kvstore, CGenerator, "kvstore", "08_kvstore.yml");
snapshot_test!(
    snapshot_c_nested_modules,
    CGenerator,
    "nested_modules",
    "09_nested_modules.yml"
);

snapshot_test!(
    snapshot_cpp_calculator,
    CppGenerator,
    "calculator",
    "01_calculator.yml"
);
snapshot_test!(
    snapshot_cpp_contacts,
    CppGenerator,
    "contacts",
    "02_contacts.yml"
);
snapshot_test!(
    snapshot_cpp_inventory,
    CppGenerator,
    "inventory",
    "03_inventory.yml"
);
snapshot_test!(
    snapshot_cpp_async_demo,
    CppGenerator,
    "async_demo",
    "04_async_demo.yml"
);
snapshot_test!(snapshot_cpp_events, CppGenerator, "events", "05_events.yml");
snapshot_test!(
    snapshot_cpp_kitchen_sink,
    CppGenerator,
    "kitchen_sink",
    "06_kitchen_sink.yml"
);
snapshot_test!(
    snapshot_cpp_docs_everywhere,
    CppGenerator,
    "docs_everywhere",
    "07_docs_everywhere.yml"
);
snapshot_test!(
    snapshot_cpp_kvstore,
    CppGenerator,
    "kvstore",
    "08_kvstore.yml"
);
snapshot_test!(
    snapshot_cpp_nested_modules,
    CppGenerator,
    "nested_modules",
    "09_nested_modules.yml"
);

snapshot_test!(
    snapshot_swift_calculator,
    SwiftGenerator,
    "calculator",
    "01_calculator.yml"
);
snapshot_test!(
    snapshot_swift_contacts,
    SwiftGenerator,
    "contacts",
    "02_contacts.yml"
);
snapshot_test!(
    snapshot_swift_inventory,
    SwiftGenerator,
    "inventory",
    "03_inventory.yml"
);
snapshot_test!(
    snapshot_swift_async_demo,
    SwiftGenerator,
    "async_demo",
    "04_async_demo.yml"
);
snapshot_test!(
    snapshot_swift_events,
    SwiftGenerator,
    "events",
    "05_events.yml"
);
snapshot_test!(
    snapshot_swift_kitchen_sink,
    SwiftGenerator,
    "kitchen_sink",
    "06_kitchen_sink.yml"
);
snapshot_test!(
    snapshot_swift_docs_everywhere,
    SwiftGenerator,
    "docs_everywhere",
    "07_docs_everywhere.yml"
);
snapshot_test!(
    snapshot_swift_kvstore,
    SwiftGenerator,
    "kvstore",
    "08_kvstore.yml"
);
snapshot_test!(
    snapshot_swift_nested_modules,
    SwiftGenerator,
    "nested_modules",
    "09_nested_modules.yml"
);

snapshot_test!(
    snapshot_android_calculator,
    AndroidGenerator,
    "calculator",
    "01_calculator.yml"
);
snapshot_test!(
    snapshot_android_contacts,
    AndroidGenerator,
    "contacts",
    "02_contacts.yml"
);
snapshot_test!(
    snapshot_android_inventory,
    AndroidGenerator,
    "inventory",
    "03_inventory.yml"
);
snapshot_test!(
    snapshot_android_async_demo,
    AndroidGenerator,
    "async_demo",
    "04_async_demo.yml"
);
snapshot_test!(
    snapshot_android_events,
    AndroidGenerator,
    "events",
    "05_events.yml"
);
snapshot_test!(
    snapshot_android_kitchen_sink,
    AndroidGenerator,
    "kitchen_sink",
    "06_kitchen_sink.yml"
);
snapshot_test!(
    snapshot_android_docs_everywhere,
    AndroidGenerator,
    "docs_everywhere",
    "07_docs_everywhere.yml"
);
snapshot_test!(
    snapshot_android_kvstore,
    AndroidGenerator,
    "kvstore",
    "08_kvstore.yml"
);
snapshot_test!(
    snapshot_android_nested_modules,
    AndroidGenerator,
    "nested_modules",
    "09_nested_modules.yml"
);

snapshot_test!(
    snapshot_node_calculator,
    NodeGenerator,
    "calculator",
    "01_calculator.yml"
);
snapshot_test!(
    snapshot_node_contacts,
    NodeGenerator,
    "contacts",
    "02_contacts.yml"
);
snapshot_test!(
    snapshot_node_inventory,
    NodeGenerator,
    "inventory",
    "03_inventory.yml"
);
snapshot_test!(
    snapshot_node_async_demo,
    NodeGenerator,
    "async_demo",
    "04_async_demo.yml"
);
snapshot_test!(
    snapshot_node_events,
    NodeGenerator,
    "events",
    "05_events.yml"
);
snapshot_test!(
    snapshot_node_kitchen_sink,
    NodeGenerator,
    "kitchen_sink",
    "06_kitchen_sink.yml"
);
snapshot_test!(
    snapshot_node_docs_everywhere,
    NodeGenerator,
    "docs_everywhere",
    "07_docs_everywhere.yml"
);
snapshot_test!(
    snapshot_node_kvstore,
    NodeGenerator,
    "kvstore",
    "08_kvstore.yml"
);
snapshot_test!(
    snapshot_node_nested_modules,
    NodeGenerator,
    "nested_modules",
    "09_nested_modules.yml"
);

snapshot_test!(
    snapshot_wasm_calculator,
    WasmGenerator,
    "calculator",
    "01_calculator.yml"
);
snapshot_test!(
    snapshot_wasm_contacts,
    WasmGenerator,
    "contacts",
    "02_contacts.yml"
);
snapshot_test!(
    snapshot_wasm_inventory,
    WasmGenerator,
    "inventory",
    "03_inventory.yml"
);
snapshot_test!(
    snapshot_wasm_async_demo,
    WasmGenerator,
    "async_demo",
    "04_async_demo.yml"
);
snapshot_test!(
    snapshot_wasm_events,
    WasmGenerator,
    "events",
    "05_events.yml"
);
snapshot_test!(
    snapshot_wasm_kitchen_sink,
    WasmGenerator,
    "kitchen_sink",
    "06_kitchen_sink.yml"
);
snapshot_test!(
    snapshot_wasm_docs_everywhere,
    WasmGenerator,
    "docs_everywhere",
    "07_docs_everywhere.yml"
);
snapshot_test!(
    snapshot_wasm_kvstore,
    WasmGenerator,
    "kvstore",
    "08_kvstore.yml"
);
snapshot_test!(
    snapshot_wasm_nested_modules,
    WasmGenerator,
    "nested_modules",
    "09_nested_modules.yml"
);

snapshot_test!(
    snapshot_python_calculator,
    PythonGenerator,
    "calculator",
    "01_calculator.yml"
);
snapshot_test!(
    snapshot_python_contacts,
    PythonGenerator,
    "contacts",
    "02_contacts.yml"
);
snapshot_test!(
    snapshot_python_inventory,
    PythonGenerator,
    "inventory",
    "03_inventory.yml"
);
snapshot_test!(
    snapshot_python_async_demo,
    PythonGenerator,
    "async_demo",
    "04_async_demo.yml"
);
snapshot_test!(
    snapshot_python_events,
    PythonGenerator,
    "events",
    "05_events.yml"
);
snapshot_test!(
    snapshot_python_kitchen_sink,
    PythonGenerator,
    "kitchen_sink",
    "06_kitchen_sink.yml"
);
snapshot_test!(
    snapshot_python_docs_everywhere,
    PythonGenerator,
    "docs_everywhere",
    "07_docs_everywhere.yml"
);
snapshot_test!(
    snapshot_python_kvstore,
    PythonGenerator,
    "kvstore",
    "08_kvstore.yml"
);
snapshot_test!(
    snapshot_python_nested_modules,
    PythonGenerator,
    "nested_modules",
    "09_nested_modules.yml"
);

snapshot_test!(
    snapshot_dotnet_calculator,
    DotnetGenerator,
    "calculator",
    "01_calculator.yml"
);
snapshot_test!(
    snapshot_dotnet_contacts,
    DotnetGenerator,
    "contacts",
    "02_contacts.yml"
);
snapshot_test!(
    snapshot_dotnet_inventory,
    DotnetGenerator,
    "inventory",
    "03_inventory.yml"
);
snapshot_test!(
    snapshot_dotnet_async_demo,
    DotnetGenerator,
    "async_demo",
    "04_async_demo.yml"
);
snapshot_test!(
    snapshot_dotnet_events,
    DotnetGenerator,
    "events",
    "05_events.yml"
);
snapshot_test!(
    snapshot_dotnet_kitchen_sink,
    DotnetGenerator,
    "kitchen_sink",
    "06_kitchen_sink.yml"
);
snapshot_test!(
    snapshot_dotnet_docs_everywhere,
    DotnetGenerator,
    "docs_everywhere",
    "07_docs_everywhere.yml"
);
snapshot_test!(
    snapshot_dotnet_kvstore,
    DotnetGenerator,
    "kvstore",
    "08_kvstore.yml"
);
snapshot_test!(
    snapshot_dotnet_nested_modules,
    DotnetGenerator,
    "nested_modules",
    "09_nested_modules.yml"
);

snapshot_test!(
    snapshot_dart_calculator,
    DartGenerator,
    "calculator",
    "01_calculator.yml"
);
snapshot_test!(
    snapshot_dart_contacts,
    DartGenerator,
    "contacts",
    "02_contacts.yml"
);
snapshot_test!(
    snapshot_dart_inventory,
    DartGenerator,
    "inventory",
    "03_inventory.yml"
);
snapshot_test!(
    snapshot_dart_async_demo,
    DartGenerator,
    "async_demo",
    "04_async_demo.yml"
);
snapshot_test!(
    snapshot_dart_events,
    DartGenerator,
    "events",
    "05_events.yml"
);
snapshot_test!(
    snapshot_dart_kitchen_sink,
    DartGenerator,
    "kitchen_sink",
    "06_kitchen_sink.yml"
);
snapshot_test!(
    snapshot_dart_docs_everywhere,
    DartGenerator,
    "docs_everywhere",
    "07_docs_everywhere.yml"
);
snapshot_test!(
    snapshot_dart_kvstore,
    DartGenerator,
    "kvstore",
    "08_kvstore.yml"
);
snapshot_test!(
    snapshot_dart_nested_modules,
    DartGenerator,
    "nested_modules",
    "09_nested_modules.yml"
);

snapshot_test!(
    snapshot_go_calculator,
    GoGenerator,
    "calculator",
    "01_calculator.yml"
);
snapshot_test!(
    snapshot_go_contacts,
    GoGenerator,
    "contacts",
    "02_contacts.yml"
);
snapshot_test!(
    snapshot_go_inventory,
    GoGenerator,
    "inventory",
    "03_inventory.yml"
);
snapshot_test!(
    snapshot_go_async_demo,
    GoGenerator,
    "async_demo",
    "04_async_demo.yml"
);
snapshot_test!(snapshot_go_events, GoGenerator, "events", "05_events.yml");
snapshot_test!(
    snapshot_go_kitchen_sink,
    GoGenerator,
    "kitchen_sink",
    "06_kitchen_sink.yml"
);
snapshot_test!(
    snapshot_go_docs_everywhere,
    GoGenerator,
    "docs_everywhere",
    "07_docs_everywhere.yml"
);
snapshot_test!(
    snapshot_go_kvstore,
    GoGenerator,
    "kvstore",
    "08_kvstore.yml"
);
snapshot_test!(
    snapshot_go_nested_modules,
    GoGenerator,
    "nested_modules",
    "09_nested_modules.yml"
);

snapshot_test!(
    snapshot_ruby_calculator,
    RubyGenerator,
    "calculator",
    "01_calculator.yml"
);
snapshot_test!(
    snapshot_ruby_contacts,
    RubyGenerator,
    "contacts",
    "02_contacts.yml"
);
snapshot_test!(
    snapshot_ruby_inventory,
    RubyGenerator,
    "inventory",
    "03_inventory.yml"
);
snapshot_test!(
    snapshot_ruby_async_demo,
    RubyGenerator,
    "async_demo",
    "04_async_demo.yml"
);
snapshot_test!(
    snapshot_ruby_events,
    RubyGenerator,
    "events",
    "05_events.yml"
);
snapshot_test!(
    snapshot_ruby_kitchen_sink,
    RubyGenerator,
    "kitchen_sink",
    "06_kitchen_sink.yml"
);
snapshot_test!(
    snapshot_ruby_docs_everywhere,
    RubyGenerator,
    "docs_everywhere",
    "07_docs_everywhere.yml"
);
snapshot_test!(
    snapshot_ruby_kvstore,
    RubyGenerator,
    "kvstore",
    "08_kvstore.yml"
);
snapshot_test!(
    snapshot_ruby_nested_modules,
    RubyGenerator,
    "nested_modules",
    "09_nested_modules.yml"
);

// Rich (algebraic) enums + the expanded numeric primitives, across every
// backend (fixture 10). Locks the rich-enum wrapper surface (opaque object,
// per-variant constructors and field getters, tag reader, destructor) into the
// snapshot oracle for all 11 generators.
snapshot_test!(snapshot_c_shapes, CGenerator, "shapes", "10_shapes.yml");
snapshot_test!(snapshot_cpp_shapes, CppGenerator, "shapes", "10_shapes.yml");
snapshot_test!(
    snapshot_swift_shapes,
    SwiftGenerator,
    "shapes",
    "10_shapes.yml"
);
snapshot_test!(
    snapshot_android_shapes,
    AndroidGenerator,
    "shapes",
    "10_shapes.yml"
);
snapshot_test!(
    snapshot_node_shapes,
    NodeGenerator,
    "shapes",
    "10_shapes.yml"
);
snapshot_test!(
    snapshot_wasm_shapes,
    WasmGenerator,
    "shapes",
    "10_shapes.yml"
);
snapshot_test!(
    snapshot_python_shapes,
    PythonGenerator,
    "shapes",
    "10_shapes.yml"
);
snapshot_test!(
    snapshot_dotnet_shapes,
    DotnetGenerator,
    "shapes",
    "10_shapes.yml"
);
snapshot_test!(
    snapshot_dart_shapes,
    DartGenerator,
    "shapes",
    "10_shapes.yml"
);
snapshot_test!(snapshot_go_shapes, GoGenerator, "shapes", "10_shapes.yml");
snapshot_test!(
    snapshot_ruby_shapes,
    RubyGenerator,
    "shapes",
    "10_shapes.yml"
);

/// Phase 5 prelude coverage: every generator, every fixture, every output file
/// must carry the standard WeaveFFI prelude markers in its first five lines.
#[test]
fn prelude_present_in_every_generated_file() {
    let generators: Vec<Box<dyn DynGenerator>> = vec![
        Box::new(ConfiguredGenerator::new(CGenerator, CConfig::default())),
        Box::new(ConfiguredGenerator::new(CppGenerator, CppConfig::default())),
        Box::new(ConfiguredGenerator::new(
            SwiftGenerator,
            SwiftConfig::default(),
        )),
        Box::new(ConfiguredGenerator::new(
            AndroidGenerator,
            AndroidConfig::default(),
        )),
        Box::new(ConfiguredGenerator::new(
            NodeGenerator,
            NodeConfig::default(),
        )),
        Box::new(ConfiguredGenerator::new(
            WasmGenerator,
            WasmConfig::default(),
        )),
        Box::new(ConfiguredGenerator::new(
            PythonGenerator,
            PythonConfig::default(),
        )),
        Box::new(ConfiguredGenerator::new(
            DotnetGenerator,
            DotnetConfig::default(),
        )),
        Box::new(ConfiguredGenerator::new(
            DartGenerator,
            DartConfig::default(),
        )),
        Box::new(ConfiguredGenerator::new(GoGenerator, GoConfig::default())),
        Box::new(ConfiguredGenerator::new(
            RubyGenerator,
            RubyConfig::default(),
        )),
    ];
    let fixtures = [
        "01_calculator.yml",
        "02_contacts.yml",
        "03_inventory.yml",
        "04_async_demo.yml",
        "05_events.yml",
        "06_kitchen_sink.yml",
        "07_docs_everywhere.yml",
        "08_kvstore.yml",
        "09_nested_modules.yml",
        "10_shapes.yml",
    ];

    for fixture in fixtures {
        let api = load_api(fixture);
        for gen in &generators {
            let tmp = tempfile::tempdir().expect("create tempdir");
            let out_dir = Utf8Path::from_path(tmp.path()).expect("utf8 tempdir");
            gen.generate(&api, out_dir).expect("generator failed");
            let gen_root = out_dir.join(gen.name());
            let files = collect_files_sorted(gen_root.as_std_path());
            assert!(
                !files.is_empty(),
                "generator {} produced no files for fixture {fixture}",
                gen.name(),
            );
            for file in files {
                let contents = fs::read_to_string(&file)
                    .unwrap_or_else(|e| panic!("read {}: {e}", file.display()));
                assert_prelude_present(&contents, &file);
            }
        }
    }
}
