//! Snapshot tests covering every generator.
//!
//! Five fixtures cover the whole IDL surface between them: `kitchen_sink`
//! (every scalar and composite type, OptDirect and Slice values in every
//! position, an interface with objects in optional, list, iterator, and
//! record positions, two callback interfaces, two error domains, typed and
//! untyped `throws`, iterators, async and cancellable functions,
//! deprecation, and a nested submodule), `shapes` (rich enums and the full
//! numeric primitive set), `nested_modules` (a three-deep module tree with
//! cross-module references), `docs_everywhere` (doc comments on every
//! declaration kind), and `edge_cases` (identifiers that are reserved words
//! in some target, deeply nested composites, and every legal position of
//! interfaces and callback interfaces).
//!
//! Every target renders all five fixtures. Each rendered file must carry the
//! WeaveFFI prelude, and a file that shares its name with a C target output
//! (a target's copy of the C header) must be byte-equal to the C target's.
//! Only `kitchen_sink` is snapshotted, as full files, and only the files
//! that depend on the API: a file matching one of the target's
//! [`fixed_files`](weaveffi_cli::targets::Target::fixed_files) patterns
//! (fixed runtimes, package manifests, READMEs) isn't snapshotted at all.
//! The other fixtures are covered by the fixture compile checks
//! (`scripts/check-fixtures.sh`) and by targeted assertions in each target's
//! unit tests.
//!
//! Snapshots live under `tests/snapshots/` and are named
//! `{target}_kitchen_sink__{path}`.

use std::collections::{BTreeMap, BTreeSet};
use std::fs;
use std::path::Path;

use weaveffi_cli::targets::{self, Target, REGISTRY};
use weaveffi_model::model::Model;
use weaveffi_model::parse::parse_api_str;
use weaveffi_model::pkg::Identity;
use weaveffi_model::validate::validate;

const FIXTURES: [&str; 5] = [
    "kitchen_sink",
    "shapes",
    "nested_modules",
    "docs_everywhere",
    "edge_cases",
];

/// The one fixture whose outputs are snapshotted. It exercises every
/// feature, so it also emits every optional file (such as Kotlin's
/// `Async.kt`), and every fixed-file pattern must match one of its outputs,
/// so a renamed or removed file can't leave a stale entry behind.
const SNAPSHOTTED: &str = "kitchen_sink";

fn matches_pattern(pattern: &str, file_name: &str) -> bool {
    match pattern.strip_prefix('*') {
        Some(suffix) => file_name.ends_with(suffix),
        None => file_name == pattern,
    }
}

/// The C target's outputs for `api`, keyed by file name. Other targets copy
/// the C header verbatim, under the same file name.
fn c_outputs(model: &Model) -> BTreeMap<String, String> {
    targets::find("c")
        .expect("the C target")
        .build_default()
        .render(model)
        .into_iter()
        .map(|file| {
            let name = file.path.file_name().expect("file name").to_owned();
            (name, file.contents)
        })
        .collect()
}

fn load_model(stem: &str) -> Model {
    let path = Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("tests/fixtures")
        .join(format!("{stem}.yml"));
    let contents = fs::read_to_string(&path)
        .unwrap_or_else(|e| panic!("read fixture {}: {e}", path.display()));
    let api = parse_api_str(&contents, "yaml")
        .unwrap_or_else(|e| panic!("parse fixture {}: {e}", path.display()));
    validate(&api, &Identity::named(stem), None)
        .unwrap_or_else(|e| panic!("validate fixture {}: {e}", path.display()))
}

fn sanitize(rel: &Path) -> String {
    rel.to_string_lossy().replace(['/', '\\', '.', '-'], "_")
}

/// Replace the concrete crate version in every WeaveFFI prelude
/// (`Generated by WeaveFFI 0.21.0 from ...`) with a stable `[VERSION]`
/// placeholder so a release bump does not invalidate every snapshot.
fn redact_version(s: &str) -> String {
    const MARKER: &str = "Generated by WeaveFFI ";
    let mut out = String::with_capacity(s.len());
    let mut rest = s;
    while let Some(idx) = rest.find(MARKER) {
        out.push_str(&rest[..idx + MARKER.len()]);
        rest = &rest[idx + MARKER.len()..];
        let end = rest.find(char::is_whitespace).unwrap_or(rest.len());
        out.push_str("[VERSION]");
        rest = &rest[end..];
    }
    out.push_str(rest);
    out
}

/// Every generated file embeds the standard WeaveFFI prelude markers in its
/// first five lines. JSON files (which cannot carry comments) embed these
/// markers via the `"//"` key convention.
fn assert_prelude_present(contents: &str, file: &Path) {
    let head: String = contents.lines().take(5).collect::<Vec<_>>().join("\n");
    for marker in ["Generated by WeaveFFI", "DO NOT EDIT"] {
        assert!(
            head.contains(marker),
            "{} is missing '{marker}' in the first 5 lines:\n{head}",
            file.display(),
        );
    }
}

fn run_snapshots(target: &dyn Target) {
    let fixed = target.fixed_files();
    let mut unmatched: BTreeSet<&str> = fixed.iter().copied().collect();
    for stem in FIXTURES {
        let model = load_model(stem);
        let c_headers = if target.name() == "c" {
            BTreeMap::new()
        } else {
            c_outputs(&model)
        };
        let mut files = target.render(&model);
        files.sort_by(|a, b| a.path.cmp(&b.path));
        assert!(
            !files.is_empty(),
            "generator {} produced no files for fixture {stem}",
            target.name(),
        );

        insta::with_settings!({
            snapshot_path => "snapshots",
            prepend_module_to_snapshot => false,
            omit_expression => true,
        }, {
            for file in files {
                assert_prelude_present(&file.contents, file.path.as_std_path());
                let file_name = file.path.file_name().expect("file name");
                if let Some(header) = c_headers.get(file_name) {
                    assert!(
                        file.contents == *header,
                        "{} in fixture {stem} isn't a byte-equal copy of the C target's {file_name}",
                        file.path,
                    );
                    continue;
                }
                if stem != SNAPSHOTTED {
                    continue;
                }
                if let Some(pattern) = fixed.iter().find(|p| matches_pattern(p, file_name)) {
                    unmatched.remove(pattern);
                    continue;
                }
                let name = format!(
                    "{}_{stem}__{}",
                    target.name(),
                    sanitize(file.path.as_std_path())
                );
                insta::assert_snapshot!(name, redact_version(&file.contents));
            }
        });
    }
    assert!(
        unmatched.is_empty(),
        "fixed-file patterns for {} match no {SNAPSHOTTED} output: {unmatched:?}",
        target.name(),
    );
}

/// Every registered target, each with its default configuration.
#[test]
fn snapshot_every_target() {
    for desc in REGISTRY {
        run_snapshots(desc.build_default().as_ref());
    }
}
