//! Packaging output: `package.json` and `binding.gyp` manifests (dev and
//! packaged layouts), the packaged README, and the `types.d.ts` assembly.
//!
//! JSON manifests are built with [`manifest::JsonObject`] so quoting and
//! escaping are centralized; gyp's conventional inline spellings (one-line
//! arrays and condition rows) are spliced as [`JsonValue::Raw`] fragments to
//! keep the rendered files byte-identical to the established output.

use heck::ToLowerCamelCase;
use weaveffi_core::cache::CLI_VERSION;
use weaveffi_core::codegen::CodeWriter;
use weaveffi_core::errors::{type_name as error_type_name, ERROR_BRAND};
use weaveffi_core::manifest::{json_escape, JsonObject, JsonValue};
use weaveffi_core::model::{BindingModel, EnumBinding, ErrorBinding, InterfaceBinding};
use weaveffi_core::package::PackageContext;
use weaveffi_core::pkg::ResolvedPackage;
use weaveffi_core::platform::Platform;
use weaveffi_core::utils::{render_prelude, render_trailer, CommentStyle};

use crate::types::{
    emit_doc, emit_fn_doc, js_fn_name, js_param_name, ts_fn_tags, ts_params, ts_ret, ts_type_for,
};

/// Prepend the generated-file prelude entries (`//`, `//warning`,
/// `//regenerate`) npm tolerates at the top of `package.json`. Mirrors
/// [`render_json_prelude`](weaveffi_core::utils::render_json_prelude), whose
/// version constant ([`CLI_VERSION`]) it shares.
fn json_prelude_entries(obj: JsonObject, input_basename: &str) -> JsonObject {
    obj.str_entry(
        "//",
        format!("Generated by WeaveFFI {CLI_VERSION} from {input_basename}"),
    )
    .str_entry(
        "//warning",
        "DO NOT EDIT. Your changes will be overwritten.",
    )
    .str_entry(
        "//regenerate",
        format!("To regenerate: weaveffi generate {input_basename} -o <out>"),
    )
}

/// Append the optional npm metadata fields shared by the dev and packaged
/// `package.json` layouts. npm's `repository` shorthand keeps its inline
/// object spelling, with the URL escaped.
fn npm_metadata_entries(obj: JsonObject, package: &ResolvedPackage) -> JsonObject {
    let mut obj = obj
        .str_entry("name", &package.name)
        .str_entry("version", &package.version)
        .str_entry("description", package.description_or_default())
        .opt_str_entry("license", package.license.as_deref());
    if let Some(author) = package.authors.first() {
        obj = obj.str_entry("author", author);
    }
    obj = obj.opt_str_entry("homepage", package.homepage.as_deref());
    if let Some(repository) = &package.repository {
        obj = obj.entry(
            "repository",
            JsonValue::Raw(format!(
                "{{ \"type\": \"git\", \"url\": \"{}\" }}",
                json_escape(repository)
            )),
        );
    }
    obj
}

/// Append the fixed addon fields: entry points, the gyp flag, and the
/// install-time rebuild script.
fn addon_entries(obj: JsonObject) -> JsonObject {
    obj.str_entry("main", "index.js")
        .str_entry("types", "types.d.ts")
        .entry("gypfile", JsonValue::Bool(true))
        .entry(
            "scripts",
            JsonValue::Object(JsonObject::new().str_entry("install", "node-gyp rebuild")),
        )
}

/// Render the dev-layout `package.json`.
pub(crate) fn render_package_json(package: &ResolvedPackage, input_basename: &str) -> String {
    let obj = json_prelude_entries(JsonObject::new(), input_basename);
    addon_entries(npm_metadata_entries(obj, package)).render()
}

/// Render the main package's `package.json` with `optionalDependencies` on the
/// per-platform native packages.
pub(crate) fn render_packaged_package_json(
    package: &ResolvedPackage,
    platform_pkgs: &[(Platform, String)],
    input_basename: &str,
) -> String {
    let obj = json_prelude_entries(JsonObject::new(), input_basename);
    let mut deps = JsonObject::new();
    for (_, pkg_name) in platform_pkgs {
        deps = deps.str_entry(pkg_name, &package.version);
    }
    addon_entries(npm_metadata_entries(obj, package))
        .entry("optionalDependencies", JsonValue::Object(deps))
        .render()
}

/// Render a per-platform native package's `package.json`, gated by npm `os` and
/// `cpu` so npm installs only the matching one. The single-element `os` and
/// `cpu` arrays keep npm's conventional inline spelling.
pub(crate) fn render_platform_package_json(
    pkg_name: &str,
    version: &str,
    platform: Platform,
) -> String {
    let os = platform.node_os();
    let cpu = platform.node_cpu();
    JsonObject::new()
        .str_entry("name", pkg_name)
        .str_entry("version", version)
        .str_entry(
            "description",
            format!("Prebuilt WeaveFFI native library for {os}/{cpu}"),
        )
        .entry("os", JsonValue::Raw(format!("[\"{os}\"]")))
        .entry("cpu", JsonValue::Raw(format!("[\"{cpu}\"]")))
        .render()
}

/// The shared gyp target skeleton of both `binding.gyp` layouts. Source and
/// include lists keep gyp's conventional one-line array spelling.
fn gyp_target_base() -> JsonObject {
    JsonObject::new()
        .str_entry("target_name", "weaveffi")
        .entry(
            "sources",
            JsonValue::Raw("[\"weaveffi_addon.c\"]".to_string()),
        )
        .entry("include_dirs", JsonValue::Raw("[\"../c\"]".to_string()))
}

/// Render one `binding.gyp` document: hash-comment prelude, the object with
/// its `targets` list, a blank separator line, and the trailer.
fn render_gyp_document(body: JsonObject, input_basename: &str) -> String {
    let mut out = render_prelude(CommentStyle::Hash, input_basename);
    out.push_str(&body.render());
    out.push('\n');
    out.push_str(&render_trailer(CommentStyle::Hash, "binding.gyp"));
    out
}

/// Render the dev-layout `binding.gyp`: compile the addon against the
/// generated C header and link the locally built `weaveffi` library.
pub(crate) fn render_binding_gyp(input_basename: &str) -> String {
    let target =
        gyp_target_base().entry("libraries", JsonValue::Raw("[\"-lweaveffi\"]".to_string()));
    let body =
        JsonObject::new().entry("targets", JsonValue::Array(vec![JsonValue::Object(target)]));
    render_gyp_document(body, input_basename)
}

/// Render the packaged `binding.gyp`: it links the prebuilt library resolved
/// from the installed per-platform package (selected by npm `os`/`cpu`) and
/// sets an rpath so the addon finds it at runtime. The `<!(node -p ...)`
/// command expansion embeds unescaped quotes gyp expects verbatim, and the
/// condition rows keep gyp's one-line spelling, so both splice as raw
/// fragments.
pub(crate) fn render_packaged_binding_gyp(
    pkg_name: &str,
    lib: &str,
    input_basename: &str,
) -> String {
    let resolve = format!(
        "<!(node -p \"require('path').dirname(require.resolve('{pkg_name}-' + process.platform + '-' + process.arch + '/package.json'))\")"
    );
    let target = gyp_target_base()
        .entry(
            "library_dirs",
            JsonValue::Raw("[\"<(wv_native_dir)\"]".to_string()),
        )
        .entry("libraries", JsonValue::Raw(format!("[\"-l{lib}\"]")))
        .entry(
            "conditions",
            JsonValue::Array(vec![
                JsonValue::Raw(
                    "[\"OS=='mac'\", { \"xcode_settings\": { \"OTHER_LDFLAGS\": [\"-Wl,-rpath,<(wv_native_dir)\"] } }]"
                        .to_string(),
                ),
                JsonValue::Raw(
                    "[\"OS=='linux'\", { \"ldflags\": [\"-Wl,-rpath,<(wv_native_dir)\"] }]"
                        .to_string(),
                ),
            ]),
        );
    let body = JsonObject::new()
        .entry(
            "variables",
            JsonValue::Object(
                JsonObject::new().entry("wv_native_dir%", JsonValue::Raw(format!("\"{resolve}\""))),
            ),
        )
        .entry("targets", JsonValue::Array(vec![JsonValue::Object(target)]));
    render_gyp_document(body, input_basename)
}

/// README for a packaged Node artifact using `optionalDependencies`.
pub(crate) fn render_packaged_readme(
    package: &ResolvedPackage,
    ctx: &PackageContext,
    input_basename: &str,
) -> String {
    let prelude = render_prelude(CommentStyle::Xml, input_basename);
    let trailer = render_trailer(CommentStyle::Xml, "README.md");
    let name = &package.name;
    let platforms: Vec<String> = ctx
        .binaries
        .platforms()
        .map(|p| format!("- `{}-{}-{}`", name, p.node_os(), p.node_cpu()))
        .collect();
    let platform_list = platforms.join("\n");
    format!(
        r#"{prelude}# {name} (Node.js)

Auto-generated N-API bindings. The prebuilt native library is published as a set
of per-platform packages and selected automatically through
`optionalDependencies` (npm installs only the package matching the host
`os`/`cpu`):

{platform_list}

The thin N-API addon is compiled at install time (`node-gyp rebuild`) and links
the prebuilt library from the selected platform package, so no Rust toolchain is
needed. A C compiler and the generated C header (`../c`) are required to build
the addon.

{trailer}"#,
    )
}

/// `.d.ts` for a rich (algebraic) enum: a discriminated union with a string
/// `tag` property naming the active variant, plus the variant's fields.
/// Mirrors the tagged-union objects the loader's unpack function produces.
fn render_rich_enum_dts(out: &mut String, e: &EnumBinding) {
    emit_doc(out, &e.doc, "");
    out.push_str(&format!("export type {} =", e.name));
    for v in &e.variants {
        out.push('\n');
        if v.doc.is_some() {
            let mut d = String::new();
            emit_doc(&mut d, &v.doc, "  ");
            out.push_str(&d);
        }
        let fields: String = v
            .fields
            .iter()
            .map(|f| format!("; {}: {}", f.name, ts_type_for(&f.ty)))
            .collect();
        out.push_str(&format!("  | {{ tag: '{}'{fields} }}", v.name));
    }
    out.push_str(";\n");
}

/// `.d.ts` for one declaring module's error surface: the domain class
/// extending the generic brand plus one subclass per code carrying its
/// stable `CODE` and, for codes with structured payloads, the decoded
/// payload fields as readonly properties.
fn render_error_dts(out: &mut String, eb: &ErrorBinding) {
    let domain = &eb.type_name;
    out.push_str(&format!(
        "/** Typed errors reported by the `{}` module's throwing functions. */\n",
        eb.owner_path
    ));
    out.push_str(&format!("export class {domain} extends {ERROR_BRAND} {{\n"));
    out.push_str("  constructor(code: number, message: string);\n");
    out.push_str("}\n");
    for c in &eb.codes {
        let class = error_type_name(&c.name, "Error");
        emit_doc(out, &c.doc, "");
        out.push_str(&format!("export class {class} extends {domain} {{\n"));
        out.push_str(&format!("  static readonly CODE: {};\n", c.value));
        for field in &c.fields {
            emit_doc(out, &field.doc, "  ");
            out.push_str(&format!(
                "  readonly {}: {};\n",
                field.name,
                ts_type_for(&field.ty)
            ));
        }
        out.push_str("  constructor(message?: string);\n");
        out.push_str("}\n");
    }
}

/// `.d.ts` for one interface: a class whose canonical `new` constructor,
/// static factories, methods, and statics mirror the JS class in
/// [`render_interface_class_js`](crate::entities).
fn render_interface_dts(out: &mut String, i: &InterfaceBinding, error: Option<&ErrorBinding>) {
    let name = &i.name;
    let mut w = CodeWriter::two_space();
    {
        let mut d = String::new();
        emit_doc(&mut d, &i.doc, "");
        w.raw(d);
    }
    w.block(format!("export class {name} {{"), "}", |w| {
        let canonical = i
            .constructors
            .iter()
            .find(|c| c.name == "new" && !c.is_async);
        if let Some(c) = canonical {
            let mut d = String::new();
            emit_fn_doc(&mut d, &c.doc, &c.params, "  ", &ts_fn_tags(c, error));
            w.raw(d);
            w.line(format!("constructor({});", ts_params(c)));
        }
        for c in &i.constructors {
            if canonical.is_some_and(|canon| std::ptr::eq(canon, c)) {
                continue;
            }
            let mut d = String::new();
            emit_fn_doc(&mut d, &c.doc, &c.params, "  ", &ts_fn_tags(c, error));
            w.raw(d);
            let ret = if c.is_async {
                format!("Promise<{name}>")
            } else {
                name.to_string()
            };
            w.line(format!(
                "static {}({}): {ret};",
                c.name.to_lower_camel_case(),
                ts_params(c)
            ));
        }
        for f in &i.methods {
            let mut d = String::new();
            emit_fn_doc(&mut d, &f.doc, &f.params, "  ", &ts_fn_tags(f, error));
            w.raw(d);
            w.line(format!(
                "{}({}): {};",
                f.name.to_lower_camel_case(),
                ts_params(f),
                ts_ret(f)
            ));
        }
        for f in &i.statics {
            let mut d = String::new();
            emit_fn_doc(&mut d, &f.doc, &f.params, "  ", &ts_fn_tags(f, error));
            w.raw(d);
            w.line(format!(
                "static {}({}): {};",
                f.name.to_lower_camel_case(),
                ts_params(f),
                ts_ret(f)
            ));
        }
        w.line("/** Free the underlying native object. */");
        w.line("destroy(): void;");
    });
    out.push_str(&w.finish());
}

/// Render the TypeScript declarations (`types.d.ts`): the generic error
/// brand, then per module the typed error surface, record interfaces, enums
/// (numeric or tagged-union), interface classes, listener endpoints, and one
/// function signature per exported wrapper.
pub(crate) fn render_node_dts(
    model: &BindingModel,
    strip_module_prefix: bool,
    input_basename: &str,
) -> String {
    let mut out = render_prelude(CommentStyle::DoubleSlash, input_basename);
    out.push_str("// Generated types for WeaveFFI functions\n");
    out.push_str("/**\n");
    out.push_str(" * Base class of every error thrown by these bindings. Non-throwing\n");
    out.push_str(" * functions reject or throw it directly for panics and marshalling\n");
    out.push_str(" * failures; throwing functions surface a module domain subclass.\n");
    out.push_str(" */\n");
    out.push_str(&format!("export class {ERROR_BRAND} extends Error {{\n"));
    out.push_str("  /** The numeric ABI error code. */\n");
    out.push_str("  code: number;\n");
    out.push_str("  /** The raw producer message, without the code prefix. */\n");
    out.push_str("  errorMessage: string;\n");
    out.push_str("  constructor(code: number, message: string);\n");
    out.push_str("}\n");
    for m in &model.modules {
        if let Some(eb) = m.error.as_ref().filter(|e| e.declared_here) {
            render_error_dts(&mut out, eb);
        }
        // Records are plain value types: an interface with typed fields, no
        // handle wrapping, no builders, no destroy.
        for s in &m.structs {
            emit_doc(&mut out, &s.doc, "");
            out.push_str(&format!("export interface {} {{\n", s.name));
            for field in &s.fields {
                emit_doc(&mut out, &field.doc, "  ");
                out.push_str(&format!("  {}: {};\n", field.name, ts_type_for(&field.ty)));
            }
            out.push_str("}\n");
        }
        for e in &m.enums {
            // A rich (algebraic) enum is a tagged union, not a plain numeric
            // `enum`.
            if e.is_rich() {
                render_rich_enum_dts(&mut out, e);
                continue;
            }
            emit_doc(&mut out, &e.doc, "");
            out.push_str(&format!("export enum {} {{\n", e.name));
            for v in &e.variants {
                emit_doc(&mut out, &v.doc, "  ");
                out.push_str(&format!("  {} = {},\n", v.name, v.value));
            }
            out.push_str("}\n");
        }
        out.push_str(&format!("// module {}\n", m.path));
        for i in &m.interfaces {
            render_interface_dts(&mut out, i, m.error.as_ref());
        }
        for l in &m.listeners {
            let Some(cb) = m.callback(&l.event_callback) else {
                continue;
            };
            let cb_params: Vec<String> = cb
                .params
                .iter()
                .map(|p| format!("{}: {}", js_param_name(&p.name), ts_type_for(&p.ty)))
                .collect();
            let register = js_fn_name(
                &m.path,
                &format!("register_{}", l.name),
                strip_module_prefix,
            );
            let unregister = js_fn_name(
                &m.path,
                &format!("unregister_{}", l.name),
                strip_module_prefix,
            );
            emit_doc(&mut out, &l.doc, "");
            out.push_str(&format!(
                "export function {register}(callback: ({}) => void): number\n",
                cb_params.join(", ")
            ));
            out.push_str(&format!("export function {unregister}(id: number): void\n"));
        }
        for f in &m.functions {
            let ts_name = js_fn_name(&m.path, &f.name, strip_module_prefix);
            emit_fn_doc(
                &mut out,
                &f.doc,
                &f.params,
                "",
                &ts_fn_tags(f, m.error.as_ref()),
            );
            out.push_str(&format!(
                "export function {}({}): {}\n",
                ts_name,
                ts_params(f),
                ts_ret(f)
            ));
        }
    }
    out.push('\n');
    out.push_str(&render_trailer(CommentStyle::DoubleSlash, "types.d.ts"));
    out
}
