//! Project configuration: `weaveffi.toml` discovery and parsing, the
//! `cli_targets!` registry, and the per-target [`Targets`] struct it
//! generates.
//!
//! A project's identity, inputs, and generator options live in one TOML file
//! at the project root:
//!
//! ```toml
//! [project]
//! input = "src/lib.rs"          # or an IDL such as "kvstore.yml"
//! out = "bindings"
//! targets = ["c", "swift", "python"]
//!
//! [package]
//! name = "kvstore"
//! version = "1.2.0"
//! license = "MIT"
//!
//! [generators.swift]
//! module_name = "KVStore"
//! ```
//!
//! The API definition describes only the API surface. With a `[project]`
//! table, `weaveffi generate` (no arguments) works from any directory inside
//! the project, like `cargo build`. With an explicit input, the CLI finds the
//! nearest `weaveffi.toml` at or above the input's directory; `--config
//! <path>` names one explicitly.

use camino::{Utf8Path, Utf8PathBuf};
use miette::{IntoDiagnostic, Result, WrapErr};
use serde::Deserialize;
use weaveffi_gen::codegen::{ConfiguredBackend, Target};
use weaveffi_gen::targets::c::{CConfig, CGenerator};
use weaveffi_gen::targets::cpp::{CppConfig, CppGenerator};
use weaveffi_gen::targets::dart::{DartConfig, DartGenerator};
use weaveffi_gen::targets::dotnet::{DotnetConfig, DotnetGenerator};
use weaveffi_gen::targets::go::{GoConfig, GoGenerator};
use weaveffi_gen::targets::kotlin::{KotlinConfig, KotlinGenerator};
use weaveffi_gen::targets::node::{NodeConfig, NodeGenerator};
use weaveffi_gen::targets::python::{PythonConfig, PythonGenerator};
use weaveffi_gen::targets::ruby::{RubyConfig, RubyGenerator};
use weaveffi_gen::targets::swift::{SwiftConfig, SwiftGenerator};
use weaveffi_gen::targets::wasm::{WasmConfig, WasmGenerator};
use weaveffi_model::pkg::Package;

/// The file name `weaveffi generate` looks for when `--config` is absent.
pub(crate) const CONFIG_FILE_NAME: &str = "weaveffi.toml";

/// Declarative registry of every language target the CLI can drive.
///
/// This macro is the **single source of truth** for the target set. One
/// invocation (below) expands to:
///   * the [`Targets`] struct: one typed field per target, deserialized from
///     the `[generators.<target>]` tables;
///   * `build`: the ordered, object-safe target list;
///   * `stamp_input_basename` / `fan_strip_module_prefix`: the `finalize`
///     fan-outs.
///
/// Adding a language is therefore a one-line edit here (plus the generator
/// crate and its workspace dependency), keeping WeaveFFI's promise that a new
/// platform is a code-gen change, not a rewrite.
///
/// Per-entry syntax: `"<token>" => <field>: <Config> via <Generator> [, strip]`.
/// The trailing `strip` tags targets whose config honors
/// `global.strip_module_prefix`.
macro_rules! cli_targets {
    (
        $( $key:literal => $field:ident : $cfg:ident via $gen:ident $(, $strip:ident)? ),* $(,)?
    ) => {
        /// Per-target generator options, one field per registered language.
        /// Each field is the generator crate's own `Config` type, so adding a
        /// knob to a generator only requires changing that generator's crate.
        /// Generated by `cli_targets!`.
        #[derive(Debug, Default, Clone, Deserialize)]
        #[serde(default, deny_unknown_fields)]
        pub(crate) struct Targets {
            $( pub(crate) $field: $cfg, )*
        }

        impl Targets {
            /// Every registered target name, in registry order.
            pub(crate) const NAMES: &'static [&'static str] = &[ $( $key, )* ];

            /// Build the heterogeneous list of object-safe targets that the
            /// orchestrator and dry-run paths share. Order matches the entry
            /// order in the `cli_targets!` invocation for stable output.
            pub(crate) fn build(&self) -> Vec<Box<dyn Target>> {
                vec![
                    $( Box::new(ConfiguredBackend::new($gen, self.$field.clone())), )*
                ]
            }

            /// Stamp the IDL basename onto every per-target config.
            fn stamp_input_basename(&mut self, input_basename: Option<String>) {
                $( self.$field.input_basename = input_basename.clone(); )*
            }

            /// Fan `global.strip_module_prefix` out to every target whose
            /// config honors it (those tagged `strip` in `cli_targets!`).
            fn fan_strip_module_prefix(&mut self, value: bool) {
                $( $( cli_targets!(@strip self, $field, value, $strip); )? )*
            }
        }
    };
    (@strip $self:ident, $field:ident, $value:ident, strip) => {
        $self.$field.strip_module_prefix = $value;
    };
}

cli_targets! {
    "c"       => c:       CConfig       via CGenerator,
    "cpp"     => cpp:     CppConfig     via CppGenerator,
    "swift"   => swift:   SwiftConfig   via SwiftGenerator,   strip,
    "kotlin"  => kotlin:  KotlinConfig  via KotlinGenerator,  strip,
    "node"    => node:    NodeConfig    via NodeGenerator,
    "wasm"    => wasm:    WasmConfig    via WasmGenerator,
    "python"  => python:  PythonConfig  via PythonGenerator,  strip,
    "dotnet"  => dotnet:  DotnetConfig  via DotnetGenerator,  strip,
    "dart"    => dart:    DartConfig    via DartGenerator,    strip,
    "go"      => go:      GoConfig      via GoGenerator,      strip,
    "ruby"    => ruby:    RubyConfig    via RubyGenerator,    strip,
}

/// Knobs that affect multiple generators or the orchestrator itself
/// (the `[global]` table).
#[derive(Debug, Default, Clone, Deserialize)]
#[serde(default, deny_unknown_fields)]
pub(crate) struct GlobalConfig {
    /// Shorthand: sets `strip_module_prefix` on every per-target config that
    /// supports it. Stripping is the default, so `strip_module_prefix =
    /// false` here restores module-prefixed wrapper names everywhere at
    /// once. When set, this overrides per-target sections; omit it to
    /// control targets individually.
    pub(crate) strip_module_prefix: Option<bool>,
    /// Shell command executed once before any generator runs.
    pub(crate) pre_generate: Option<String>,
    /// Shell command executed once after every generator succeeds.
    pub(crate) post_generate: Option<String>,
}

/// The `[project]` table: what to generate from, where to, and for which
/// targets, so a configured project needs no command-line arguments. Paths
/// are relative to the directory containing `weaveffi.toml`.
#[derive(Debug, Default, Clone, Deserialize)]
#[serde(default, deny_unknown_fields)]
pub(crate) struct ProjectTable {
    /// The API definition: annotated Rust source or an IDL document.
    pub(crate) input: Option<Utf8PathBuf>,
    /// The output directory for `generate` and `diff` (default `generated`).
    pub(crate) out: Option<Utf8PathBuf>,
    /// The targets to generate when `--target` is not given (default: all).
    pub(crate) targets: Option<Vec<String>>,
}

/// The whole `weaveffi.toml`: project paths, package identity, global knobs,
/// and per-target generator options.
#[derive(Debug, Default, Clone, Deserialize)]
#[serde(default, deny_unknown_fields)]
pub(crate) struct ProjectConfig {
    /// The `[project]` table.
    pub(crate) project: ProjectTable,
    /// The `[package]` table: distribution identity shared by every
    /// generated manifest.
    pub(crate) package: Package,
    /// The `[global]` table.
    pub(crate) global: GlobalConfig,
    /// The `[generators.<target>]` tables.
    pub(crate) generators: Targets,
    /// Where the config was loaded from, when it came from a file.
    #[serde(skip)]
    pub(crate) source: Option<Utf8PathBuf>,
}

impl ProjectConfig {
    /// Load the project config: the file named by `explicit` when given,
    /// otherwise the nearest `weaveffi.toml` at or above the input file's
    /// directory, otherwise the defaults.
    ///
    /// # Errors
    ///
    /// Returns an error when an explicitly named file cannot be read, or when
    /// any located file fails to parse.
    pub(crate) fn load(explicit: Option<&str>, input: &Utf8Path) -> Result<Self> {
        let path = match explicit {
            Some(p) => Some(Utf8PathBuf::from(p)),
            None => discover(input),
        };
        match path {
            Some(p) => Self::from_file(&p),
            None => Ok(Self::default()),
        }
    }

    /// Parse the config file at `path`.
    ///
    /// # Errors
    ///
    /// Returns an error when the file cannot be read or is not a valid
    /// `weaveffi.toml`.
    pub(crate) fn from_file(path: &Utf8Path) -> Result<Self> {
        let contents = std::fs::read_to_string(path.as_std_path())
            .into_diagnostic()
            .wrap_err_with(|| format!("failed to read config file: {path}"))?;
        let mut cfg: Self = toml::from_str(&contents)
            .into_diagnostic()
            .wrap_err_with(|| format!("failed to parse config file: {path}"))?;
        cfg.source = Some(path.to_path_buf());
        Ok(cfg)
    }

    /// Fan `global.strip_module_prefix` out to every per-target config that
    /// honors it, then stamp the IDL `input_basename` on every per-target
    /// config.
    pub(crate) fn finalize(&mut self, input_basename: Option<String>) {
        if let Some(v) = self.global.strip_module_prefix {
            self.generators.fan_strip_module_prefix(v);
        }
        self.generators.stamp_input_basename(input_basename);
    }

    /// Resolve the project for a command: the config (explicit, discovered
    /// from `input`, or discovered from the current directory) and the input
    /// file (the argument, else `[project] input`), finalized against the
    /// input.
    ///
    /// # Errors
    ///
    /// Returns an error when no input is given and no discovered config
    /// names one, or when a config file cannot be read or parsed.
    pub(crate) fn locate(
        explicit: Option<&str>,
        input: Option<&str>,
    ) -> Result<(Self, Utf8PathBuf)> {
        let (mut cfg, input) = match input {
            Some(i) => (
                Self::load(explicit, Utf8Path::new(i))?,
                Utf8PathBuf::from(i),
            ),
            None => {
                let path = match explicit {
                    Some(p) => Utf8PathBuf::from(p),
                    None => current_dir()
                        .ok()
                        .and_then(|cwd| discover(&cwd.join(CONFIG_FILE_NAME)))
                        .ok_or_else(|| {
                            miette::miette!(
                                "no input given and no {CONFIG_FILE_NAME} found in this directory \
                             or any parent; pass an input file or run `weaveffi init`"
                            )
                        })?,
                };
                let cfg = Self::from_file(&path)?;
                let Some(rel) = cfg.project.input.clone() else {
                    miette::bail!(
                        "no input given and {path} has no `[project] input`; pass an input \
                         file or set `input` in the [project] table"
                    );
                };
                let input = cfg.relative_to_config(&rel);
                (cfg, input)
            }
        };
        cfg.finalize(input.file_name().map(str::to_string));
        Ok((cfg, input))
    }

    /// Resolve `path` against the directory holding the config file (or the
    /// current directory when there is no file).
    pub(crate) fn relative_to_config(&self, path: &Utf8Path) -> Utf8PathBuf {
        match self.source.as_deref().and_then(Utf8Path::parent) {
            Some(dir) if path.is_relative() && !dir.as_str().is_empty() => dir.join(path),
            _ => path.to_path_buf(),
        }
    }

    /// The output directory: `out` if given on the command line, else
    /// `[project] out`, else `./generated`.
    pub(crate) fn out_dir(&self, out: Option<&str>) -> Utf8PathBuf {
        match (out, &self.project.out) {
            (Some(o), _) => Utf8PathBuf::from(o),
            (None, Some(o)) => self.relative_to_config(o),
            (None, None) => Utf8PathBuf::from("./generated"),
        }
    }

    /// Build every registered target, keeping only those named in the
    /// comma-separated `filter`, else those listed in `[project] targets`,
    /// else all of them.
    ///
    /// # Errors
    ///
    /// Returns an error naming any filter entry that is not a registered
    /// target, so a typo in `--target` fails instead of silently generating
    /// nothing.
    pub(crate) fn select_targets(&self, filter: Option<&str>) -> Result<Vec<Box<dyn Target>>> {
        let wanted: Option<Vec<&str>> = match filter {
            Some(t) => Some(
                t.split(',')
                    .map(str::trim)
                    .filter(|s| !s.is_empty())
                    .collect(),
            ),
            None => self
                .project
                .targets
                .as_ref()
                .map(|ts| ts.iter().map(String::as_str).collect()),
        };
        if let Some(names) = &wanted {
            let unknown: Vec<&str> = names
                .iter()
                .copied()
                .filter(|n| !Targets::NAMES.contains(n))
                .collect();
            if !unknown.is_empty() {
                miette::bail!(
                    "unknown target(s): {}; expected any of: {}",
                    unknown.join(", "),
                    Targets::NAMES.join(", ")
                );
            }
        }
        Ok(self
            .generators
            .build()
            .into_iter()
            .filter(|g| wanted.as_ref().is_none_or(|ts| ts.contains(&g.name())))
            .collect())
    }
}

/// The current directory as a UTF-8 path.
fn current_dir() -> std::io::Result<Utf8PathBuf> {
    Utf8PathBuf::from_path_buf(std::env::current_dir()?)
        .map_err(|_| std::io::Error::other("current directory is not valid UTF-8"))
}

/// Walk from the input file's directory up to the filesystem root and return
/// the first `weaveffi.toml` found.
fn discover(input: &Utf8Path) -> Option<Utf8PathBuf> {
    let start = input
        .parent()
        .filter(|p| !p.as_str().is_empty())
        .map(Utf8Path::to_path_buf)
        .unwrap_or_else(|| Utf8PathBuf::from("."));
    let mut dir = Some(start.as_path());
    while let Some(d) = dir {
        let candidate = d.join(CONFIG_FILE_NAME);
        if candidate.is_file() {
            return Some(candidate);
        }
        dir = d.parent().filter(|p| !p.as_str().is_empty());
    }
    None
}

#[cfg(test)]
mod tests {
    use super::*;

    fn write(dir: &std::path::Path, name: &str, contents: &str) -> Utf8PathBuf {
        let p = dir.join(name);
        std::fs::write(&p, contents).unwrap();
        Utf8PathBuf::from_path_buf(p).unwrap()
    }

    #[test]
    fn parses_package_global_and_generator_tables() {
        let dir = tempfile::tempdir().unwrap();
        let cfg_path = write(
            dir.path(),
            CONFIG_FILE_NAME,
            concat!(
                "[package]\n",
                "name = \"kvstore\"\n",
                "version = \"1.2.0\"\n",
                "[global]\n",
                "strip_module_prefix = true\n",
                "[generators.swift]\n",
                "module_name = \"MyApp\"\n",
                "[generators.kotlin]\n",
                "package = \"com.example.myapp\"\n",
            ),
        );
        let mut cfg = ProjectConfig::from_file(&cfg_path).unwrap();
        assert_eq!(cfg.package.name.as_deref(), Some("kvstore"));
        assert_eq!(cfg.package.version.as_deref(), Some("1.2.0"));
        assert_eq!(cfg.generators.swift.module_name.as_deref(), Some("MyApp"));
        assert_eq!(cfg.generators.kotlin.package(), Some("com.example.myapp"));
        assert_eq!(cfg.global.strip_module_prefix, Some(true));
        assert_eq!(cfg.source.as_deref(), Some(cfg_path.as_path()));

        cfg.finalize(Some("api.yml".into()));
        assert!(cfg.generators.python.strip_module_prefix);
        assert_eq!(
            cfg.generators.swift.input_basename.as_deref(),
            Some("api.yml")
        );
    }

    #[test]
    fn unknown_top_level_keys_are_errors() {
        let dir = tempfile::tempdir().unwrap();
        let cfg_path = write(
            dir.path(),
            CONFIG_FILE_NAME,
            "[swift]\nmodule_name = \"X\"\n",
        );
        let err = ProjectConfig::from_file(&cfg_path).unwrap_err();
        assert!(format!("{err:?}").contains("swift"), "{err:?}");
    }

    #[test]
    fn discovery_walks_up_from_the_input() {
        let dir = tempfile::tempdir().unwrap();
        let nested = dir.path().join("idl").join("deep");
        std::fs::create_dir_all(&nested).unwrap();
        write(
            dir.path(),
            CONFIG_FILE_NAME,
            "[package]\nname = \"found\"\n",
        );
        let input = write(&nested, "api.yml", "version: \"0.10.0\"\nmodules: []\n");

        let cfg = ProjectConfig::load(None, &input).unwrap();
        assert_eq!(cfg.package.name.as_deref(), Some("found"));
    }

    #[test]
    fn defaults_when_no_config_exists() {
        let dir = tempfile::tempdir().unwrap();
        let input = write(dir.path(), "api.yml", "version: \"0.10.0\"\nmodules: []\n");
        let cfg = ProjectConfig::load(None, &input).unwrap();
        assert!(cfg.source.is_none(), "unexpected config: {:?}", cfg.source);
        assert_eq!(cfg.global.strip_module_prefix, None);
        assert!(cfg.package.name.is_none());
    }

    #[test]
    fn explicit_missing_config_is_an_error() {
        let err = ProjectConfig::load(Some("/nonexistent/weaveffi.toml"), Utf8Path::new("x.yml"))
            .unwrap_err();
        assert!(format!("{err:?}").contains("failed to read config file"));
    }

    #[test]
    fn target_filter_rejects_unknown_names() {
        let cfg = ProjectConfig::default();
        let err = match cfg.select_targets(Some("swift,rustlang")) {
            Ok(_) => panic!("unknown target should be rejected"),
            Err(e) => e,
        };
        assert!(format!("{err}").contains("rustlang"), "{err}");
        let ok = cfg.select_targets(Some("swift, c")).unwrap();
        let names: Vec<&str> = ok.iter().map(|g| g.name()).collect();
        assert_eq!(names, vec!["c", "swift"]);
        assert_eq!(
            cfg.select_targets(None).unwrap().len(),
            Targets::NAMES.len()
        );
    }

    #[test]
    fn project_table_supplies_input_out_and_targets() {
        let dir = tempfile::tempdir().unwrap();
        let cfg_path = write(
            dir.path(),
            CONFIG_FILE_NAME,
            "[project]\ninput = \"api.yml\"\nout = \"bindings\"\ntargets = [\"c\", \"python\"]\n",
        );
        write(dir.path(), "api.yml", "version: \"0.10.0\"\nmodules: []\n");
        let (cfg, input) = ProjectConfig::locate(Some(cfg_path.as_str()), None).unwrap();
        let root = cfg_path.parent().unwrap();
        assert_eq!(input, root.join("api.yml"));
        assert_eq!(cfg.out_dir(None), root.join("bindings"));
        assert_eq!(cfg.out_dir(Some("x")), Utf8PathBuf::from("x"));
        let names: Vec<&str> = cfg
            .select_targets(None)
            .unwrap()
            .iter()
            .map(|t| t.name())
            .collect();
        assert_eq!(names, ["c", "python"]);
        assert_eq!(cfg.select_targets(Some("go")).unwrap().len(), 1);

        let bare = write(dir.path(), "other.toml", "[package]\nname = \"x\"\n");
        let err = ProjectConfig::locate(Some(bare.as_str()), None).unwrap_err();
        assert!(format!("{err}").contains("[project] input"), "{err}");
    }

    /// Every registered target's *declared* [`TargetCapabilities`] must match
    /// the documented feature matrix. This pins the declarations so a backend
    /// cannot silently claim (or drop) a gated feature: the matrix here, the
    /// generator's `capabilities()`, and `docs/src/generators/README.md` are
    /// changed together or this test fails.
    ///
    /// Declaration accuracy is only half the contract. The companion guard in
    /// `tests/no_silent_stubs.rs` proves a *declared* feature is actually
    /// emitted (no `unimplemented!`/`todo!` source, no stub markers in output),
    /// and the conformance harness proves it runs.
    #[test]
    fn declared_capabilities_match_documented_matrix() {
        use std::collections::BTreeMap;
        use weaveffi_gen::capabilities::TargetCapabilities;

        // Every target is full. Wasm delivers callbacks/listeners
        // synchronously through function-table trampolines in its standard
        // loader (Emscripten mode stubs them, mirroring its async stubs).
        let expected: Vec<(&str, TargetCapabilities)> = Targets::NAMES
            .iter()
            .map(|n| (*n, TargetCapabilities::full()))
            .collect();

        let targets = Targets::default().build();
        let actual: BTreeMap<&str, TargetCapabilities> = targets
            .iter()
            .map(|g| (g.name(), g.capabilities()))
            .collect();

        assert_eq!(actual.len(), expected.len());
        for (name, caps) in expected {
            let got = actual
                .get(name)
                .unwrap_or_else(|| panic!("target '{name}' is missing from the registry"));
            assert_eq!(
                *got, caps,
                "declared capabilities for '{name}' drifted from the documented matrix",
            );
        }
    }
}
