//! Project configuration: `weaveffi.toml` discovery and parsing, the
//! `cli_targets!` registry, and the per-target [`Targets`] struct it
//! generates.
//!
//! A project's identity, inputs, build settings, and generator options live
//! in one TOML file at the project root:
//!
//! ```toml
//! [project]
//! input = "."                   # the producer crate, or an IDL such as "kvstore.yml"
//! out = "bindings"
//! targets = ["c", "swift", "python"]
//!
//! [package]
//! name = "kvstore"
//! version = "1.2.0"
//! license = "MIT"
//! dist = "dist"
//!
//! [build]
//! platforms = ["darwin-arm64", "ios-arm64", "ios-sim-arm64"]
//!
//! [generators.swift]
//! name = "KVStore"
//! ```
//!
//! The API definition describes only the API surface. With a `[project]`
//! table, `weaveffi generate` (no arguments) works from any directory inside
//! the project, like `cargo build`. With an explicit input, the CLI finds the
//! nearest `weaveffi.toml` at or above the input's directory; `--config
//! <path>` names one explicitly.

use crate::build::BuildSettings;
use crate::codegen::{ConfiguredBackend, Target};
use crate::targets::c::{CConfig, CGenerator};
use crate::targets::cpp::{CppConfig, CppGenerator};
use crate::targets::dart::{DartConfig, DartGenerator};
use crate::targets::dotnet::{DotnetConfig, DotnetGenerator};
use crate::targets::go::{GoConfig, GoGenerator};
use crate::targets::kotlin::{KotlinConfig, KotlinGenerator};
use crate::targets::node::{NodeConfig, NodeGenerator};
use crate::targets::python::{PythonConfig, PythonGenerator};
use crate::targets::ruby::{RubyConfig, RubyGenerator};
use crate::targets::swift::{SwiftConfig, SwiftGenerator};
use crate::targets::wasm::{WasmConfig, WasmGenerator};
use camino::{Utf8Path, Utf8PathBuf};
use miette::{IntoDiagnostic, Result, WrapErr};
use serde::{Deserialize, Deserializer};
use weaveffi_model::pkg::Package;

/// The file name `weaveffi generate` looks for when `--config` is absent.
pub const CONFIG_FILE_NAME: &str = "weaveffi.toml";

/// Declarative registry of every language target the CLI can drive.
///
/// This macro is the **single source of truth** for the target set. One
/// invocation (below) expands to:
///   * the [`Targets`] struct: one typed field per target, deserialized from
///     the `[generators.<target>]` tables;
///   * `build`: the ordered, object-safe target list.
///
/// Adding a language is therefore a one-line edit here (plus the generator
/// crate and its workspace dependency), keeping WeaveFFI's promise that a new
/// platform is a code-gen change, not a rewrite.
///
/// Per-entry syntax: `"<token>" => <field>: <Config> via <Generator>`.
macro_rules! cli_targets {
    (
        $( $key:literal => $field:ident : $cfg:ident via $gen:ident ),* $(,)?
    ) => {
        /// Per-target generator options, one field per registered language.
        /// Each field is the generator crate's own `Config` type, so adding a
        /// knob to a generator only requires changing that generator's crate.
        /// Generated by `cli_targets!`.
        #[derive(Debug, Default, Clone, Deserialize)]
        #[serde(default, deny_unknown_fields)]
        pub struct Targets {
            $(
                #[doc = concat!("The `[generators.", $key, "]` table.")]
                pub $field: $cfg,
            )*
        }

        impl Targets {
            /// Every registered target name, in registry order.
            pub const NAMES: &'static [&'static str] = &[ $( $key, )* ];

            /// Build the heterogeneous list of object-safe targets that the
            /// orchestrator and dry-run paths share. Order matches the entry
            /// order in the `cli_targets!` invocation for stable output.
            pub fn build(&self) -> Vec<Box<dyn Target>> {
                vec![
                    $( Box::new(ConfiguredBackend::new($gen, self.$field.clone())), )*
                ]
            }
        }
    };
}

cli_targets! {
    "c"       => c:       CConfig       via CGenerator,
    "cpp"     => cpp:     CppConfig     via CppGenerator,
    "swift"   => swift:   SwiftConfig   via SwiftGenerator,
    "kotlin"  => kotlin:  KotlinConfig  via KotlinGenerator,
    "node"    => node:    NodeConfig    via NodeGenerator,
    "wasm"    => wasm:    WasmConfig    via WasmGenerator,
    "python"  => python:  PythonConfig  via PythonGenerator,
    "dotnet"  => dotnet:  DotnetConfig  via DotnetGenerator,
    "dart"    => dart:    DartConfig    via DartGenerator,
    "go"      => go:      GoConfig      via GoGenerator,
    "ruby"    => ruby:    RubyConfig    via RubyGenerator,
}

/// The `[package]` table: the distribution identity shared by every
/// generated manifest, plus where `weaveffi package` writes its artifacts.
#[derive(Debug, Default, Clone)]
pub struct PackageTable {
    /// The identity keys (`name`, `version`, `license`, ...).
    pub identity: Package,
    /// The dist directory for `weaveffi package` (default `dist`).
    pub dist: Option<Utf8PathBuf>,
}

impl<'de> Deserialize<'de> for PackageTable {
    /// Split `dist` off and parse the remaining keys as the identity, which
    /// keeps rejecting unknown keys.
    fn deserialize<D: Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        use serde::de::Error;
        let mut table = toml::Table::deserialize(deserializer)?;
        let dist = table
            .remove("dist")
            .map(|v| v.try_into::<Utf8PathBuf>())
            .transpose()
            .map_err(D::Error::custom)?;
        let identity = toml::Value::Table(table)
            .try_into::<Package>()
            .map_err(D::Error::custom)?;
        Ok(Self { identity, dist })
    }
}

/// The `[build]` table: how `weaveffi build` (and `weaveffi package`)
/// compile a Rust producer.
#[derive(Debug, Clone, Deserialize)]
#[serde(default, deny_unknown_fields)]
pub struct BuildTable {
    /// The producer crate's `Cargo.toml` (default: the project's crate,
    /// else `Cargo.toml` next to `weaveffi.toml`).
    pub manifest: Option<Utf8PathBuf>,
    /// The platform ids to build when `--platforms` isn't given (default:
    /// the host).
    pub platforms: Option<Vec<String>>,
    /// Build with the release profile.
    pub release: bool,
    /// `MACOSX_DEPLOYMENT_TARGET` for macOS builds.
    pub macos_deployment_target: String,
    /// `IPHONEOS_DEPLOYMENT_TARGET` for iOS builds.
    pub ios_deployment_target: String,
    /// The minimum Android API level, which selects the NDK compiler.
    pub android_api: u32,
}

impl Default for BuildTable {
    fn default() -> Self {
        let settings = BuildSettings::default();
        Self {
            manifest: None,
            platforms: None,
            release: settings.release,
            macos_deployment_target: settings.macos_deployment_target,
            ios_deployment_target: settings.ios_deployment_target,
            android_api: settings.android_api,
        }
    }
}

impl BuildTable {
    /// The build settings, in debug when `debug` overrides `release`.
    pub fn settings(&self, debug: bool) -> BuildSettings {
        BuildSettings {
            release: self.release && !debug,
            macos_deployment_target: self.macos_deployment_target.clone(),
            ios_deployment_target: self.ios_deployment_target.clone(),
            android_api: self.android_api,
        }
    }
}

/// The `[project]` table: what to generate from, where to, and for which
/// targets, so a configured project needs no command-line arguments. Paths
/// are relative to the directory containing `weaveffi.toml`.
#[derive(Debug, Default, Clone, Deserialize)]
#[serde(default, deny_unknown_fields)]
pub struct ProjectTable {
    /// The API definition: a Rust producer crate (its directory, usually
    /// `"."`, or its `Cargo.toml`) or an IDL document.
    pub input: Option<Utf8PathBuf>,
    /// The output directory for `generate` and `diff` (default `bindings`).
    pub out: Option<Utf8PathBuf>,
    /// The targets to generate when `--target` is not given (default: all).
    pub targets: Option<Vec<String>>,
}

/// The whole `weaveffi.toml`: project paths, package identity, build
/// settings, and per-target generator options.
#[derive(Debug, Default, Clone, Deserialize)]
#[serde(default, deny_unknown_fields)]
pub struct ProjectConfig {
    /// The `[project]` table.
    pub project: ProjectTable,
    /// The `[package]` table.
    pub package: PackageTable,
    /// The `[build]` table.
    pub build: BuildTable,
    /// The `[generators.<target>]` tables.
    pub generators: Targets,
    /// Where the config was loaded from, when it came from a file.
    #[serde(skip)]
    pub source: Option<Utf8PathBuf>,
}

impl ProjectConfig {
    /// Load the project config: the file named by `explicit` when given,
    /// otherwise the nearest `weaveffi.toml` at or above the input file's
    /// directory, otherwise the defaults.
    ///
    /// # Errors
    ///
    /// Returns an error when an explicitly named file cannot be read, or when
    /// any located file fails to parse.
    pub fn load(explicit: Option<&str>, input: &Utf8Path) -> Result<Self> {
        let path = match explicit {
            Some(p) => Some(Utf8PathBuf::from(p)),
            None => discover(input),
        };
        match path {
            Some(p) => Self::from_file(&p),
            None => Ok(Self::default()),
        }
    }

    /// Parse the config file at `path`.
    ///
    /// # Errors
    ///
    /// Returns an error when the file cannot be read or is not a valid
    /// `weaveffi.toml`.
    pub fn from_file(path: &Utf8Path) -> Result<Self> {
        let contents = std::fs::read_to_string(path.as_std_path())
            .into_diagnostic()
            .wrap_err_with(|| format!("failed to read config file: {path}"))?;
        let mut cfg: Self = toml::from_str(&contents)
            .into_diagnostic()
            .wrap_err_with(|| format!("failed to parse config file: {path}"))?;
        cfg.source = Some(path.to_path_buf());
        Ok(cfg)
    }

    /// Resolve the project for a command: the config (explicit, discovered
    /// from `input`, or discovered from the current directory) and the input
    /// file (the argument, else `[project] input`).
    ///
    /// # Errors
    ///
    /// Returns an error when no input is given and no discovered config
    /// names one, or when a config file cannot be read or parsed.
    pub fn locate(explicit: Option<&str>, input: Option<&str>) -> Result<(Self, Utf8PathBuf)> {
        let (cfg, input) = match input {
            Some(i) => (
                Self::load(explicit, Utf8Path::new(i))?,
                Utf8PathBuf::from(i),
            ),
            None => {
                let path = match explicit {
                    Some(p) => Utf8PathBuf::from(p),
                    None => current_dir()
                        .ok()
                        .and_then(|cwd| discover(&cwd.join(CONFIG_FILE_NAME)))
                        .ok_or_else(|| {
                            miette::miette!(
                                "no input given and no {CONFIG_FILE_NAME} found in this directory \
                             or any parent; pass an input file or run `weaveffi init`"
                            )
                        })?,
                };
                let cfg = Self::from_file(&path)?;
                let Some(rel) = cfg.project.input.clone() else {
                    miette::bail!(
                        "no input given and {path} has no `[project] input`; pass an input \
                         file or set `input` in the [project] table"
                    );
                };
                let input = cfg.relative_to_config(&rel);
                (cfg, input)
            }
        };
        Ok((cfg, input))
    }

    /// Resolve `path` against the directory holding the config file (or the
    /// current directory when there is no file).
    pub fn relative_to_config(&self, path: &Utf8Path) -> Utf8PathBuf {
        match self.source.as_deref().and_then(Utf8Path::parent) {
            Some(dir) if path.is_relative() && !dir.as_str().is_empty() => dir.join(path),
            _ => path.to_path_buf(),
        }
    }

    /// The output directory: `out` if given on the command line, else
    /// `[project] out`, else `bindings` next to `weaveffi.toml`.
    pub fn out_dir(&self, out: Option<&str>) -> Utf8PathBuf {
        match (out, &self.project.out) {
            (Some(o), _) => Utf8PathBuf::from(o),
            (None, Some(o)) => self.relative_to_config(o),
            (None, None) => self.relative_to_config(Utf8Path::new("bindings")),
        }
    }

    /// The dist directory for `weaveffi package`: `out` if given on the
    /// command line, else `[package] dist`, else `dist` next to
    /// `weaveffi.toml`.
    pub fn dist_dir(&self, out: Option<&str>) -> Utf8PathBuf {
        match (out, &self.package.dist) {
            (Some(o), _) => Utf8PathBuf::from(o),
            (None, Some(d)) => self.relative_to_config(d),
            (None, None) => self.relative_to_config(Utf8Path::new("dist")),
        }
    }

    /// Build every registered target, keeping only those named in the
    /// comma-separated `filter`, else those listed in `[project] targets`,
    /// else all of them.
    ///
    /// # Errors
    ///
    /// Returns an error naming any filter entry that is not a registered
    /// target, so a typo in `--target` fails instead of silently generating
    /// nothing.
    pub fn select_targets(&self, filter: Option<&str>) -> Result<Vec<Box<dyn Target>>> {
        let wanted: Option<Vec<&str>> = match filter {
            Some(t) => Some(
                t.split(',')
                    .map(str::trim)
                    .filter(|s| !s.is_empty())
                    .collect(),
            ),
            None => self
                .project
                .targets
                .as_ref()
                .map(|ts| ts.iter().map(String::as_str).collect()),
        };
        if let Some(names) = &wanted {
            let unknown: Vec<&str> = names
                .iter()
                .copied()
                .filter(|n| !Targets::NAMES.contains(n))
                .collect();
            if !unknown.is_empty() {
                miette::bail!(
                    "unknown target(s): {}; expected any of: {}",
                    unknown.join(", "),
                    Targets::NAMES.join(", ")
                );
            }
        }
        Ok(self
            .generators
            .build()
            .into_iter()
            .filter(|g| wanted.as_ref().is_none_or(|ts| ts.contains(&g.name())))
            .collect())
    }
}

/// The current directory as a UTF-8 path.
fn current_dir() -> std::io::Result<Utf8PathBuf> {
    Utf8PathBuf::from_path_buf(std::env::current_dir()?)
        .map_err(|_| std::io::Error::other("current directory is not valid UTF-8"))
}

/// Walk from the input file's directory up to the filesystem root and return
/// the first `weaveffi.toml` found.
pub(crate) fn discover(input: &Utf8Path) -> Option<Utf8PathBuf> {
    let start = input
        .parent()
        .filter(|p| !p.as_str().is_empty())
        .map(Utf8Path::to_path_buf)
        .unwrap_or_else(|| Utf8PathBuf::from("."));
    let mut dir = Some(start.as_path());
    while let Some(d) = dir {
        let candidate = d.join(CONFIG_FILE_NAME);
        if candidate.is_file() {
            return Some(candidate);
        }
        dir = d.parent().filter(|p| !p.as_str().is_empty());
    }
    None
}

#[cfg(test)]
mod tests {
    use super::*;

    fn write(dir: &std::path::Path, name: &str, contents: &str) -> Utf8PathBuf {
        let p = dir.join(name);
        std::fs::write(&p, contents).unwrap();
        Utf8PathBuf::from_path_buf(p).unwrap()
    }

    #[test]
    fn parses_package_build_and_generator_tables() {
        let dir = tempfile::tempdir().unwrap();
        let cfg_path = write(
            dir.path(),
            CONFIG_FILE_NAME,
            concat!(
                "[package]\n",
                "name = \"kvstore\"\n",
                "version = \"1.2.0\"\n",
                "dist = \"out/dist\"\n",
                "[build]\n",
                "platforms = [\"darwin-arm64\", \"ios-arm64\"]\n",
                "release = false\n",
                "macos_deployment_target = \"12.0\"\n",
                "android_api = 24\n",
                "[generators.swift]\n",
                "name = \"MyApp\"\n",
                "min_ios = \"15.0\"\n",
                "[generators.kotlin]\n",
                "name = \"com.example.myapp\"\n",
                "min_sdk = 24\n",
                "[generators.python]\n",
                "requires_python = \">=3.10\"\n",
                "[generators.node]\n",
                "node_engine = \">=20\"\n",
                "[generators.dart]\n",
                "sdk = \">=3.5.0 <4.0.0\"\n",
            ),
        );
        let cfg = ProjectConfig::from_file(&cfg_path).unwrap();
        assert_eq!(cfg.package.identity.name.as_deref(), Some("kvstore"));
        assert_eq!(cfg.package.identity.version.as_deref(), Some("1.2.0"));
        let root = cfg_path.parent().unwrap();
        assert_eq!(cfg.dist_dir(None), root.join("out/dist"));
        assert_eq!(
            cfg.dist_dir(Some("elsewhere")),
            Utf8PathBuf::from("elsewhere")
        );
        assert_eq!(
            cfg.build.platforms.as_deref(),
            Some(&["darwin-arm64".to_string(), "ios-arm64".to_string()][..])
        );
        let settings = cfg.build.settings(false);
        assert!(!settings.release);
        assert_eq!(settings.macos_deployment_target, "12.0");
        assert_eq!(settings.ios_deployment_target, "13.0");
        assert_eq!(settings.android_api, 24);
        assert_eq!(cfg.generators.swift.name.as_deref(), Some("MyApp"));
        assert_eq!(cfg.generators.swift.min_ios, "15.0");
        assert_eq!(cfg.generators.swift.min_macos, "11.0");
        assert_eq!(cfg.generators.kotlin.package(), Some("com.example.myapp"));
        assert_eq!(
            (
                cfg.generators.kotlin.min_sdk,
                cfg.generators.kotlin.compile_sdk
            ),
            (24, 35)
        );
        assert_eq!(cfg.generators.python.requires_python, ">=3.10");
        assert_eq!(cfg.generators.node.node_engine, ">=20");
        assert_eq!(cfg.generators.dart.sdk, ">=3.5.0 <4.0.0");
        assert_eq!(cfg.source.as_deref(), Some(cfg_path.as_path()));
    }

    #[test]
    fn build_and_package_defaults() {
        let cfg = ProjectConfig::default();
        let settings = cfg.build.settings(false);
        assert!(settings.release);
        assert_eq!(settings.macos_deployment_target, "11.0");
        assert_eq!(settings.ios_deployment_target, "13.0");
        assert_eq!(settings.android_api, 21);
        assert!(!cfg.build.settings(true).release);
        assert_eq!(cfg.dist_dir(None), Utf8PathBuf::from("dist"));
        assert_eq!(cfg.out_dir(None), Utf8PathBuf::from("bindings"));
    }

    #[test]
    fn removed_and_unknown_keys_are_errors() {
        let dir = tempfile::tempdir().unwrap();
        for (contents, needle) in [
            ("[global]\npre_generate = \"true\"\n", "global"),
            ("[package]\nname = \"x\"\ndistdir = \"d\"\n", "distdir"),
            ("[build]\nplatform = [\"linux-x64\"]\n", "platform"),
            ("[generators.swift]\nmodule_name = \"X\"\n", "module_name"),
            ("[generators.kotlin]\npackage = \"x\"\n", "package"),
            ("[generators.node]\npackage_name = \"x\"\n", "package_name"),
            ("[generators.go]\nmodule_path = \"x\"\n", "module_path"),
            ("[generators.dotnet]\nnamespace = \"X\"\n", "namespace"),
        ] {
            let cfg_path = write(dir.path(), CONFIG_FILE_NAME, contents);
            let err = ProjectConfig::from_file(&cfg_path).unwrap_err();
            assert!(format!("{err:?}").contains(needle), "{contents}: {err:?}");
        }
    }

    #[test]
    fn removed_strip_module_prefix_keys_are_errors() {
        let dir = tempfile::tempdir().unwrap();
        for table in ["[package]", "[generators.python]"] {
            let cfg_path = write(
                dir.path(),
                CONFIG_FILE_NAME,
                &format!("{table}\nstrip_module_prefix = false\n"),
            );
            let err = ProjectConfig::from_file(&cfg_path).unwrap_err();
            assert!(
                format!("{err:?}").contains("strip_module_prefix"),
                "{err:?}"
            );
        }
    }

    #[test]
    fn unknown_top_level_keys_are_errors() {
        let dir = tempfile::tempdir().unwrap();
        let cfg_path = write(
            dir.path(),
            CONFIG_FILE_NAME,
            "[swift]\nmodule_name = \"X\"\n",
        );
        let err = ProjectConfig::from_file(&cfg_path).unwrap_err();
        assert!(format!("{err:?}").contains("swift"), "{err:?}");
    }

    #[test]
    fn discovery_walks_up_from_the_input() {
        let dir = tempfile::tempdir().unwrap();
        let nested = dir.path().join("idl").join("deep");
        std::fs::create_dir_all(&nested).unwrap();
        write(
            dir.path(),
            CONFIG_FILE_NAME,
            "[package]\nname = \"found\"\n",
        );
        let input = write(&nested, "api.yml", "version: \"0.11.0\"\nmodules: []\n");

        let cfg = ProjectConfig::load(None, &input).unwrap();
        assert_eq!(cfg.package.identity.name.as_deref(), Some("found"));
    }

    #[test]
    fn defaults_when_no_config_exists() {
        let dir = tempfile::tempdir().unwrap();
        let input = write(dir.path(), "api.yml", "version: \"0.11.0\"\nmodules: []\n");
        let cfg = ProjectConfig::load(None, &input).unwrap();
        assert!(cfg.source.is_none(), "unexpected config: {:?}", cfg.source);
        assert!(cfg.package.identity.name.is_none());
    }

    #[test]
    fn explicit_missing_config_is_an_error() {
        let err = ProjectConfig::load(Some("/nonexistent/weaveffi.toml"), Utf8Path::new("x.yml"))
            .unwrap_err();
        assert!(format!("{err:?}").contains("failed to read config file"));
    }

    #[test]
    fn target_filter_rejects_unknown_names() {
        let cfg = ProjectConfig::default();
        let err = match cfg.select_targets(Some("swift,rustlang")) {
            Ok(_) => panic!("unknown target should be rejected"),
            Err(e) => e,
        };
        assert!(format!("{err}").contains("rustlang"), "{err}");
        let ok = cfg.select_targets(Some("swift, c")).unwrap();
        let names: Vec<&str> = ok.iter().map(|g| g.name()).collect();
        assert_eq!(names, vec!["c", "swift"]);
        assert_eq!(
            cfg.select_targets(None).unwrap().len(),
            Targets::NAMES.len()
        );
    }

    #[test]
    fn project_table_supplies_input_out_and_targets() {
        let dir = tempfile::tempdir().unwrap();
        let cfg_path = write(
            dir.path(),
            CONFIG_FILE_NAME,
            "[project]\ninput = \"api.yml\"\nout = \"bindings\"\ntargets = [\"c\", \"python\"]\n",
        );
        write(dir.path(), "api.yml", "version: \"0.11.0\"\nmodules: []\n");
        let (cfg, input) = ProjectConfig::locate(Some(cfg_path.as_str()), None).unwrap();
        let root = cfg_path.parent().unwrap();
        assert_eq!(input, root.join("api.yml"));
        assert_eq!(cfg.out_dir(None), root.join("bindings"));
        assert_eq!(cfg.out_dir(Some("x")), Utf8PathBuf::from("x"));
        let names: Vec<&str> = cfg
            .select_targets(None)
            .unwrap()
            .iter()
            .map(|t| t.name())
            .collect();
        assert_eq!(names, ["c", "python"]);
        assert_eq!(cfg.select_targets(Some("go")).unwrap().len(), 1);

        let bare = write(dir.path(), "other.toml", "[package]\nname = \"x\"\n");
        let err = ProjectConfig::locate(Some(bare.as_str()), None).unwrap_err();
        assert!(format!("{err}").contains("[project] input"), "{err}");
    }
}
