//! CLI configuration: the `cli_targets!` registry, the per-target
//! [`CliConfig`] struct it generates, [`GlobalConfig`], and the inline-IDL
//! `generators:` merge logic.

use miette::{IntoDiagnostic, Result, WrapErr};
use serde::Deserialize;
use std::collections::BTreeMap;
use weaveffi_core::codegen::{ConfiguredGenerator, DynGenerator, OrchestratorHooks};
use weaveffi_gen_android::{AndroidConfig, AndroidGenerator};
use weaveffi_gen_c::{CConfig, CGenerator};
use weaveffi_gen_cpp::{CppConfig, CppGenerator};
use weaveffi_gen_dart::{DartConfig, DartGenerator};
use weaveffi_gen_dotnet::{DotnetConfig, DotnetGenerator};
use weaveffi_gen_go::{GoConfig, GoGenerator};
use weaveffi_gen_node::{NodeConfig, NodeGenerator};
use weaveffi_gen_python::{PythonConfig, PythonGenerator};
use weaveffi_gen_ruby::{RubyConfig, RubyGenerator};
use weaveffi_gen_swift::{SwiftConfig, SwiftGenerator};
use weaveffi_gen_wasm::{WasmConfig, WasmGenerator};

/// Declarative registry of every language target the CLI can drive.
///
/// This macro is the **single source of truth** for the target set. One
/// invocation (below) expands to:
///   * the `CliConfig` struct: one typed field per target;
///   * `build_generators`: the ordered generator list;
///   * `apply_inline_target`: inline-IDL `generators.<target>` dispatch;
///   * `stamp_input_basename` / `fan_strip_module_prefix`: the `finalize`
///     fan-outs.
///
/// Adding a language is therefore a one-line edit here (plus the generator
/// crate and its workspace dependency), keeping WeaveFFI's promise that a new
/// platform is a code-gen change, not a rewrite.
///
/// Per-entry syntax: `"<token>" => <field>: <Config> via <Generator> [, strip]`.
/// The trailing `strip` tags targets whose config honors
/// `global.strip_module_prefix`.
macro_rules! cli_targets {
    (
        $( $key:literal => $field:ident : $cfg:ident via $gen:ident $(, $strip:ident)? ),* $(,)?
    ) => {
        /// Top-level configuration loaded from `--config <toml>`. Each
        /// per-language field is the generator crate's own `Config` type, so
        /// adding a knob to a generator only requires changing that
        /// generator's crate. Inline `api.generators` overrides from the IDL
        /// are merged on top after loading. Generated by `cli_targets!`.
        #[derive(Debug, Default, Deserialize)]
        #[serde(default)]
        pub(crate) struct CliConfig {
            $( pub(crate) $field: $cfg, )*
            /// Global knobs that apply across all generators. The TOML file
            /// may use `[global]` or `[weaveffi]` as the section name.
            #[serde(alias = "weaveffi")]
            pub(crate) global: GlobalConfig,
        }

        impl CliConfig {
            /// Build the heterogeneous list of object-safe generators that the
            /// orchestrator and dry-run paths share. Order matches the entry
            /// order in the `cli_targets!` invocation for stable test output.
            pub(crate) fn build_generators(&self) -> Vec<Box<dyn DynGenerator>> {
                vec![
                    $( Box::new(ConfiguredGenerator::new($gen, self.$field.clone())), )*
                ]
            }

            /// Deserialize one inline `generators.<target>` table into the
            /// matching per-target config, replacing it. Returns `false` for
            /// unknown target names so the caller can ignore them.
            fn apply_inline_target(&mut self, target: &str, table: toml::Value) -> bool {
                match target {
                    $( $key => {
                        if let Ok(cfg) = <$cfg>::deserialize(table) {
                            self.$field = cfg;
                        }
                        true
                    } )*
                    _ => false,
                }
            }

            /// Stamp the IDL basename onto every per-target config.
            fn stamp_input_basename(&mut self, input_basename: Option<String>) {
                $( self.$field.input_basename = input_basename.clone(); )*
            }

            /// Fan `global.strip_module_prefix` out to every target whose
            /// config honors it (those tagged `strip` in `cli_targets!`).
            /// Stripping is the default, so the useful direction is `false`:
            /// one `[global]` line restores module-prefixed wrapper names
            /// across every supporting target.
            fn fan_strip_module_prefix(&mut self, value: bool) {
                $( $( cli_targets!(@strip self, $field, value, $strip); )? )*
            }

            /// Fan the resolved global C ABI `prefix` out to every per-target
            /// config that has not set its own. The C symbol prefix is global
            /// by nature: every consumer must call the identical exported
            /// symbols, so a single `[global] c_prefix` (or `[c] prefix`)
            /// reaches all eleven languages.
            fn fan_c_prefix(&mut self, resolved: Option<String>) {
                let Some(p) = resolved else { return };
                $(
                    if self.$field.prefix.is_none() {
                        self.$field.prefix = Some(p.clone());
                    }
                )*
            }
        }
    };
    (@strip $self:ident, $field:ident, $value:ident, strip) => {
        $self.$field.strip_module_prefix = $value;
    };
}

cli_targets! {
    "c"       => c:       CConfig       via CGenerator,
    "cpp"     => cpp:     CppConfig     via CppGenerator,
    "swift"   => swift:   SwiftConfig   via SwiftGenerator,   strip,
    "android" => android: AndroidConfig via AndroidGenerator, strip,
    "node"    => node:    NodeConfig    via NodeGenerator,    strip,
    "wasm"    => wasm:    WasmConfig    via WasmGenerator,
    "python"  => python:  PythonConfig  via PythonGenerator,  strip,
    "dotnet"  => dotnet:  DotnetConfig  via DotnetGenerator,  strip,
    "dart"    => dart:    DartConfig    via DartGenerator,    strip,
    "go"      => go:      GoConfig      via GoGenerator,      strip,
    "ruby"    => ruby:    RubyConfig    via RubyGenerator,    strip,
}

/// Knobs that affect multiple generators or the orchestrator itself.
#[derive(Debug, Default, Clone, Deserialize)]
#[serde(default)]
pub(crate) struct GlobalConfig {
    /// Shorthand: sets `strip_module_prefix` on every per-target config that
    /// supports it. Stripping is the default, so `strip_module_prefix =
    /// false` here restores module-prefixed wrapper names everywhere at
    /// once. When set, this overrides per-target sections; omit it to
    /// control targets individually.
    pub(crate) strip_module_prefix: Option<bool>,
    /// Global C ABI symbol prefix (default `"weaveffi"`). Applies to every
    /// target so generated consumers across all languages call the identical
    /// exported symbols. A per-target `prefix` overrides this for that target.
    pub(crate) c_prefix: Option<String>,
    /// Shell command executed once before any generator runs.
    pub(crate) pre_generate: Option<String>,
    /// Shell command executed once after every generator succeeds.
    pub(crate) post_generate: Option<String>,
}

impl CliConfig {
    pub(crate) fn load(path: Option<&str>) -> Result<Self> {
        match path {
            Some(p) => {
                let contents = std::fs::read_to_string(p)
                    .into_diagnostic()
                    .wrap_err_with(|| format!("failed to read config file: {}", p))?;
                toml::from_str(&contents)
                    .into_diagnostic()
                    .wrap_err_with(|| format!("failed to parse config file: {}", p))
            }
            None => Ok(Self::default()),
        }
    }

    /// Fan `global.strip_module_prefix` out to every per-target config that
    /// honors it, propagate the C symbol prefix to the C++ wrapper config
    /// when it was only set on `[c]`, then stamp the IDL `input_basename`
    /// on every per-target config. Must run after [`merge_inline_generators`]
    /// so per-target overrides can disable a flag or override the propagated
    /// prefix.
    pub(crate) fn finalize(&mut self, input_basename: Option<String>) {
        if let Some(v) = self.global.strip_module_prefix {
            self.fan_strip_module_prefix(v);
        }
        // The C ABI prefix is global: every backend must call the exact same
        // `extern "C"` symbols. Resolve it once (`[global] c_prefix` wins, then
        // `[c] prefix`) and fan it out to every per-target config so a custom
        // prefix is honored across all eleven languages, not just C/C++.
        let resolved_prefix = self
            .global
            .c_prefix
            .clone()
            .or_else(|| self.c.prefix.clone());
        self.fan_c_prefix(resolved_prefix);
        self.stamp_input_basename(input_basename);
    }

    pub(crate) fn hooks(&self) -> OrchestratorHooks {
        OrchestratorHooks {
            pre_generate: self.global.pre_generate.clone(),
            post_generate: self.global.post_generate.clone(),
        }
    }

    /// The C ABI prefix passed to the Rust scaffold generator. Mirrors the
    /// C generator's `prefix` so the scaffold's `#[no_mangle]` symbols line
    /// up with what the C/C++ wrappers call.
    pub(crate) fn scaffold_prefix(&self) -> String {
        self.c.prefix().to_string()
    }
}

/// Apply per-target overrides from the IDL's `generators:` block to the
/// loaded [`CliConfig`].
///
/// Inline IDL values **override** anything supplied via `--config <toml>`,
/// because the IDL is project-local and committed alongside the API
/// definition while a TOML file is typically per-environment.
///
/// For each per-target section (`swift`, `c`, `cpp`, …) the body is
/// deserialized directly into that target's `Config` struct, overwriting any
/// fields the user set. The special `weaveffi`/`global` section maps to
/// [`GlobalConfig`].
///
/// Unknown target names and unknown keys are silently ignored so that older
/// CLIs can read newer IDL files without crashing.
pub(crate) fn merge_inline_generators(
    config: &mut CliConfig,
    generators: &BTreeMap<String, toml::Value>,
) {
    for (target, value) in generators {
        let Some(table) = value.as_table() else {
            continue;
        };
        let table_value = toml::Value::Table(table.clone());

        match target.as_str() {
            "global" | "weaveffi" => {
                if let Ok(g) = GlobalConfig::deserialize(table_value) {
                    config.global = g;
                }
            }
            // Per-target sections dispatch through the `cli_targets!`-generated
            // table; unknown names return `false` and are silently ignored so
            // older CLIs can read newer IDL files.
            other => {
                config.apply_inline_target(other, table_value);
            }
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn config_file_parsed() {
        let dir = tempfile::tempdir().unwrap();
        let cfg_path = dir.path().join("weaveffi.toml");
        std::fs::write(
            &cfg_path,
            concat!(
                "[swift]\n",
                "module_name = \"MyApp\"\n",
                "[android]\n",
                "package = \"com.example.myapp\"\n",
                "[global]\n",
                "strip_module_prefix = true\n",
            ),
        )
        .unwrap();

        let cfg = CliConfig::load(Some(cfg_path.to_str().unwrap())).unwrap();
        assert_eq!(cfg.swift.module_name(), "MyApp");
        assert_eq!(cfg.android.package(), "com.example.myapp");
        assert_eq!(cfg.global.strip_module_prefix, Some(true));
        assert_eq!(cfg.c.prefix(), "weaveffi");
    }

    #[test]
    fn inline_generator_config() {
        let yaml = concat!(
            "version: \"0.5.0\"\n",
            "modules:\n",
            "  - name: math\n",
            "    functions:\n",
            "      - name: add\n",
            "        params:\n",
            "          - { name: a, type: i32 }\n",
            "          - { name: b, type: i32 }\n",
            "        return: i32\n",
            "generators:\n",
            "  swift:\n",
            "    module_name: MySwiftModule\n",
        );
        let api: weaveffi_ir::ir::Api = serde_yaml::from_str(yaml).unwrap();
        assert!(api.generators.is_some());

        let mut config = CliConfig::default();
        merge_inline_generators(&mut config, api.generators.as_ref().unwrap());
        assert_eq!(config.swift.module_name(), "MySwiftModule");
    }

    #[test]
    fn inline_dart_package_name_merges() {
        let yaml = concat!(
            "version: \"0.5.0\"\n",
            "modules:\n",
            "  - name: m\n",
            "    functions: []\n",
            "generators:\n",
            "  dart:\n",
            "    package_name: my_dart_pkg\n",
        );
        let api: weaveffi_ir::ir::Api = serde_yaml::from_str(yaml).unwrap();
        let mut config = CliConfig::default();
        merge_inline_generators(&mut config, api.generators.as_ref().unwrap());
        assert_eq!(config.dart.package_name(), "my_dart_pkg");
    }

    #[test]
    fn inline_go_module_path_merges() {
        let yaml = concat!(
            "version: \"0.5.0\"\n",
            "modules:\n",
            "  - name: m\n",
            "    functions: []\n",
            "generators:\n",
            "  go:\n",
            "    module_path: github.com/me/myffi\n",
        );
        let api: weaveffi_ir::ir::Api = serde_yaml::from_str(yaml).unwrap();
        let mut config = CliConfig::default();
        merge_inline_generators(&mut config, api.generators.as_ref().unwrap());
        assert_eq!(config.go.module_path(), "github.com/me/myffi");
    }

    #[test]
    fn inline_ruby_module_name_merges() {
        let yaml = concat!(
            "version: \"0.5.0\"\n",
            "modules:\n",
            "  - name: m\n",
            "    functions: []\n",
            "generators:\n",
            "  ruby:\n",
            "    module_name: MyRubyMod\n",
        );
        let api: weaveffi_ir::ir::Api = serde_yaml::from_str(yaml).unwrap();
        let mut config = CliConfig::default();
        merge_inline_generators(&mut config, api.generators.as_ref().unwrap());
        assert_eq!(config.ruby.module_name(), "MyRubyMod");
    }

    #[test]
    fn inline_ruby_gem_name_merges() {
        let yaml = concat!(
            "version: \"0.5.0\"\n",
            "modules:\n",
            "  - name: m\n",
            "    functions: []\n",
            "generators:\n",
            "  ruby:\n",
            "    gem_name: my_ruby_gem\n",
        );
        let api: weaveffi_ir::ir::Api = serde_yaml::from_str(yaml).unwrap();
        let mut config = CliConfig::default();
        merge_inline_generators(&mut config, api.generators.as_ref().unwrap());
        assert_eq!(config.ruby.gem_name(), "my_ruby_gem");
    }

    #[test]
    fn inline_global_strip_module_prefix_merges() {
        let yaml = concat!(
            "version: \"0.5.0\"\n",
            "modules:\n",
            "  - name: m\n",
            "    functions: []\n",
            "generators:\n",
            "  weaveffi:\n",
            "    strip_module_prefix: true\n",
        );
        let api: weaveffi_ir::ir::Api = serde_yaml::from_str(yaml).unwrap();
        let mut config = CliConfig::default();
        assert_eq!(config.global.strip_module_prefix, None);
        merge_inline_generators(&mut config, api.generators.as_ref().unwrap());
        config.finalize(None);
        assert_eq!(config.global.strip_module_prefix, Some(true));
        assert!(
            config.python.strip_module_prefix,
            "finalize should fan strip_module_prefix out to python"
        );
        assert!(
            config.swift.strip_module_prefix,
            "finalize should fan strip_module_prefix out to swift"
        );
    }

    #[test]
    fn inline_global_pre_generate_merges() {
        let yaml = concat!(
            "version: \"0.5.0\"\n",
            "modules:\n",
            "  - name: m\n",
            "    functions: []\n",
            "generators:\n",
            "  global:\n",
            "    pre_generate: \"echo hi\"\n",
        );
        let api: weaveffi_ir::ir::Api = serde_yaml::from_str(yaml).unwrap();
        let mut config = CliConfig::default();
        merge_inline_generators(&mut config, api.generators.as_ref().unwrap());
        assert_eq!(config.global.pre_generate.as_deref(), Some("echo hi"));
    }

    #[test]
    fn inline_unknown_target_silently_ignored() {
        let yaml = concat!(
            "version: \"0.5.0\"\n",
            "modules:\n",
            "  - name: m\n",
            "    functions: []\n",
            "generators:\n",
            "  rustlang:\n",
            "    crate_name: future_target\n",
            "  swift:\n",
            "    module_name: KeptSwift\n",
        );
        let api: weaveffi_ir::ir::Api = serde_yaml::from_str(yaml).unwrap();
        let mut config = CliConfig::default();
        merge_inline_generators(&mut config, api.generators.as_ref().unwrap());
        assert_eq!(config.swift.module_name(), "KeptSwift");
    }

    #[test]
    fn inline_unknown_key_silently_ignored() {
        let yaml = concat!(
            "version: \"0.5.0\"\n",
            "modules:\n",
            "  - name: m\n",
            "    functions: []\n",
            "generators:\n",
            "  swift:\n",
            "    module_name: KeptSwift\n",
            "    unrecognized_future_key: \"some value\"\n",
        );
        let api: weaveffi_ir::ir::Api = serde_yaml::from_str(yaml).unwrap();
        let mut config = CliConfig::default();
        merge_inline_generators(&mut config, api.generators.as_ref().unwrap());
        assert_eq!(config.swift.module_name(), "KeptSwift");
    }

    #[test]
    fn inline_generator_config_overrides_file() {
        let yaml = concat!(
            "version: \"0.5.0\"\n",
            "modules:\n",
            "  - name: math\n",
            "    functions:\n",
            "      - name: add\n",
            "        params:\n",
            "          - { name: a, type: i32 }\n",
            "          - { name: b, type: i32 }\n",
            "        return: i32\n",
            "generators:\n",
            "  swift:\n",
            "    module_name: FromIDL\n",
            "  android:\n",
            "    package: com.idl.app\n",
        );
        let api: weaveffi_ir::ir::Api = serde_yaml::from_str(yaml).unwrap();

        let mut config = CliConfig {
            swift: SwiftConfig {
                module_name: Some("FromFile".into()),
                ..SwiftConfig::default()
            },
            android: AndroidConfig {
                package: Some("com.file.app".into()),
                ..AndroidConfig::default()
            },
            ..CliConfig::default()
        };
        merge_inline_generators(&mut config, api.generators.as_ref().unwrap());
        assert_eq!(config.swift.module_name(), "FromIDL");
        assert_eq!(config.android.package(), "com.idl.app");
    }

    #[test]
    fn config_default_when_no_file() {
        let cfg = CliConfig::load(None).unwrap();
        assert_eq!(cfg.swift.module_name(), "WeaveFFI");
        assert_eq!(cfg.android.package(), "com.weaveffi");
        assert_eq!(cfg.global.strip_module_prefix, None);
    }

    /// Every registered target's *declared* [`TargetCapabilities`] must match
    /// the documented feature matrix. This pins the declarations so a backend
    /// cannot silently claim (or drop) a gated feature: the matrix here, the
    /// generator's `capabilities()`, and `docs/src/generators/README.md` are
    /// changed together or this test fails.
    ///
    /// Declaration accuracy is only half the contract. The companion guard in
    /// `tests/no_silent_stubs.rs` proves a *declared* feature is actually
    /// emitted (no `unimplemented!`/`todo!` source, no stub markers in output),
    /// and the conformance harness proves it runs. Together they make "declared
    /// capabilities match reality" enforceable rather than aspirational.
    #[test]
    fn declared_capabilities_match_documented_matrix() {
        use std::collections::BTreeMap;
        use weaveffi_core::capabilities::TargetCapabilities;

        // Every target is full. Wasm delivers callbacks/listeners
        // synchronously through function-table trampolines in its standard
        // loader (Emscripten mode stubs them, mirroring its async stubs).
        let expected: &[(&str, TargetCapabilities)] = &[
            ("c", TargetCapabilities::full()),
            ("cpp", TargetCapabilities::full()),
            ("swift", TargetCapabilities::full()),
            ("android", TargetCapabilities::full()),
            ("node", TargetCapabilities::full()),
            ("wasm", TargetCapabilities::full()),
            ("python", TargetCapabilities::full()),
            ("dotnet", TargetCapabilities::full()),
            ("dart", TargetCapabilities::full()),
            ("go", TargetCapabilities::full()),
            ("ruby", TargetCapabilities::full()),
        ];

        let generators = CliConfig::default().build_generators();
        let actual: BTreeMap<&str, TargetCapabilities> = generators
            .iter()
            .map(|g| (g.name(), g.capabilities()))
            .collect();

        assert_eq!(
            actual.len(),
            expected.len(),
            "registry has {} targets but the matrix lists {}; add the new \
             target to the matrix (and the docs feature table)",
            actual.len(),
            expected.len(),
        );
        for (name, caps) in expected {
            let got = actual.get(name).unwrap_or_else(|| {
                panic!("target '{name}' is missing from the generator registry")
            });
            assert_eq!(
                got, caps,
                "declared capabilities for '{name}' drifted from the documented \
                 matrix; reconcile the generator's capabilities(), this table, and \
                 docs/src/generators/README.md",
            );
        }
    }
}
