//! Shared text helpers for the generators: the standard generated-file
//! prelude and trailer.
//!
//! These are the small string-building routines every backend reaches for
//! when stamping the "generated by WeaveFFI" banner onto a file. Centralizing
//! them keeps the banner identical across all of the language generators.

/// Comment syntax used to emit the standard prelude/trailer in generated files.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum CommentStyle {
    /// `// ...` line comments (C, C++, Swift, Kotlin, JS/TS, C#, Dart, Go).
    DoubleSlash,
    /// `# ...` line comments (Python, Ruby, YAML, TOML, CMake, GYP, gradle.properties).
    Hash,
    /// `<!-- ... -->` block comments (XML, HTML, Markdown).
    Xml,
}

impl CommentStyle {
    fn open(self) -> &'static str {
        match self {
            Self::DoubleSlash => "// ",
            Self::Hash => "# ",
            Self::Xml => "<!-- ",
        }
    }

    fn close(self) -> &'static str {
        match self {
            Self::Xml => " -->",
            _ => "",
        }
    }
}

/// Renders the standard `Generated by WeaveFFI {VERSION}` prelude followed
/// by the `DO NOT EDIT` warning and the regenerate command. Trailing blank
/// line included so generators can append their content directly.
pub fn render_prelude(style: CommentStyle) -> String {
    let version = env!("CARGO_PKG_VERSION");
    let o = style.open();
    let c = style.close();
    format!(
        "{o}Generated by WeaveFFI {version}{c}\n\
         {o}DO NOT EDIT. Your changes will be overwritten.{c}\n\
         {o}To regenerate: weaveffi generate{c}\n\n"
    )
}

/// Renders the closing `END {filename}` marker. Caller is responsible for any
/// preceding newline; the returned string ends with `\n`.
pub fn render_trailer(style: CommentStyle, filename: &str) -> String {
    let o = style.open();
    let c = style.close();
    format!("{o}END {filename}{c}\n")
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn prelude_double_slash_carries_required_phrases() {
        let p = render_prelude(CommentStyle::DoubleSlash);
        assert!(p.starts_with("// Generated by WeaveFFI "));
        assert!(p.contains("// DO NOT EDIT"));
        assert!(p.contains("// To regenerate: weaveffi generate\n"));
        assert!(p.ends_with("\n\n"));
    }

    #[test]
    fn prelude_hash_uses_hash_marker() {
        let p = render_prelude(CommentStyle::Hash);
        assert!(p.starts_with("# Generated by WeaveFFI "));
        assert!(p.contains("# DO NOT EDIT"));
        assert!(p.contains("# To regenerate: weaveffi generate\n"));
    }

    #[test]
    fn prelude_xml_wraps_lines_in_brackets() {
        let p = render_prelude(CommentStyle::Xml);
        assert!(p.starts_with("<!-- Generated by WeaveFFI "));
        assert!(p.contains(" -->\n<!-- DO NOT EDIT"));
        assert!(p.contains("<!-- DO NOT EDIT"));
        assert!(p.contains("Your changes will be overwritten. -->"));
    }

    #[test]
    fn trailer_has_correct_marker_per_style() {
        assert_eq!(
            render_trailer(CommentStyle::DoubleSlash, "lib.rs"),
            "// END lib.rs\n"
        );
        assert_eq!(
            render_trailer(CommentStyle::Hash, "build.toml"),
            "# END build.toml\n"
        );
        assert_eq!(
            render_trailer(CommentStyle::Xml, "package.csproj"),
            "<!-- END package.csproj -->\n"
        );
    }
}
