use anyhow::Result;
use camino::Utf8Path;
use heck::ToUpperCamelCase;
use weaveffi_core::codegen::Generator;
use weaveffi_core::utils::c_symbol_name;
use weaveffi_ir::ir::{Api, EnumDef, Function, Module, Param, StructDef, StructField, TypeRef};

pub struct DotnetGenerator;

impl Generator for DotnetGenerator {
    fn name(&self) -> &'static str {
        "dotnet"
    }

    fn generate(&self, api: &Api, out_dir: &Utf8Path) -> Result<()> {
        let dir = out_dir.join("dotnet");
        std::fs::create_dir_all(&dir)?;
        std::fs::write(dir.join("WeaveFFI.cs"), render_csharp(api))?;
        Ok(())
    }

    fn output_files(&self, _api: &Api, out_dir: &Utf8Path) -> Vec<String> {
        vec![out_dir.join("dotnet/WeaveFFI.cs").to_string()]
    }
}

fn cs_type(ty: &TypeRef) -> String {
    match ty {
        TypeRef::I32 => "int".into(),
        TypeRef::U32 => "uint".into(),
        TypeRef::I64 => "long".into(),
        TypeRef::F64 => "double".into(),
        TypeRef::Bool => "bool".into(),
        TypeRef::StringUtf8 => "string".into(),
        TypeRef::Handle => "ulong".into(),
        TypeRef::Bytes => "byte[]".into(),
        TypeRef::Struct(name) | TypeRef::Enum(name) => name.clone(),
        TypeRef::Optional(inner) => match inner.as_ref() {
            TypeRef::I32 => "int?".into(),
            TypeRef::U32 => "uint?".into(),
            TypeRef::I64 => "long?".into(),
            TypeRef::F64 => "double?".into(),
            TypeRef::Bool => "bool?".into(),
            TypeRef::Handle => "ulong?".into(),
            TypeRef::Enum(name) => format!("{name}?"),
            _ => format!("{}?", cs_type(inner)),
        },
        TypeRef::List(inner) => format!("{}[]", cs_type(inner)),
        TypeRef::Map(k, v) => format!("Dictionary<{}, {}>", cs_type(k), cs_type(v)),
    }
}

fn render_csharp(api: &Api) -> String {
    let mut out = String::new();
    out.push_str("// Auto-generated by WeaveFFI — do not edit.\n");
    out.push_str("using System;\nusing System.Collections.Generic;\nusing System.Runtime.InteropServices;\n\n");
    out.push_str("namespace WeaveFFI\n{\n");

    render_exception_class(&mut out);
    render_error_struct(&mut out);

    for m in &api.modules {
        render_module(&mut out, m);
    }

    out.push_str("}\n");
    out
}

fn render_module(out: &mut String, m: &Module) {
    for e in &m.enums {
        render_enum(out, e);
    }
    for s in &m.structs {
        render_struct(out, s);
    }
    render_native_methods(out, m);
    render_wrapper_class(out, m);
}

fn render_enum(out: &mut String, e: &EnumDef) {
    if let Some(doc) = &e.doc {
        out.push_str(&format!("    /// <summary>{doc}</summary>\n"));
    }
    out.push_str(&format!("    public enum {}\n    {{\n", e.name));
    for v in &e.variants {
        out.push_str(&format!("        {} = {},\n", v.name, v.value));
    }
    out.push_str("    }\n\n");
}

fn render_struct(out: &mut String, s: &StructDef) {
    if let Some(doc) = &s.doc {
        out.push_str(&format!("    /// <summary>{doc}</summary>\n"));
    }
    out.push_str(&format!("    public class {}\n    {{\n", s.name));
    for field in &s.fields {
        render_struct_property(out, field);
    }
    out.push_str("    }\n\n");
}

fn render_struct_property(out: &mut String, field: &StructField) {
    let cs = cs_type(&field.ty);
    let prop_name = field.name.to_upper_camel_case();
    out.push_str(&format!(
        "        public {cs} {prop_name} {{ get; set; }}\n"
    ));
}

fn render_native_methods(out: &mut String, m: &Module) {
    out.push_str(&format!(
        "    internal static class {}Native\n    {{\n",
        m.name.to_upper_camel_case()
    ));
    out.push_str("        private const string LibName = \"weaveffi\";\n\n");

    for f in &m.functions {
        render_pinvoke(out, &m.name, f);
    }

    out.push_str("    }\n\n");
}

fn render_pinvoke(out: &mut String, module_name: &str, f: &Function) {
    let c_sym = c_symbol_name(module_name, &f.name);
    out.push_str(&format!(
        "        [DllImport(LibName, EntryPoint = \"{c_sym}\", CallingConvention = CallingConvention.Cdecl)]\n"
    ));

    let ret_cs = f
        .returns
        .as_ref()
        .map(pinvoke_type)
        .unwrap_or_else(|| "void".into());

    let mut params: Vec<String> = f
        .params
        .iter()
        .map(|p| format!("{} {}", pinvoke_type(&p.ty), p.name))
        .collect();
    params.push("ref WeaveffiError err".into());

    out.push_str(&format!(
        "        internal static extern {ret_cs} {c_sym}({});\n\n",
        params.join(", ")
    ));
}

fn pinvoke_type(ty: &TypeRef) -> String {
    match ty {
        TypeRef::I32 => "int".into(),
        TypeRef::U32 => "uint".into(),
        TypeRef::I64 => "long".into(),
        TypeRef::F64 => "double".into(),
        TypeRef::Bool => "int".into(),
        TypeRef::StringUtf8 => "IntPtr".into(),
        TypeRef::Handle => "ulong".into(),
        TypeRef::Bytes => "IntPtr".into(),
        TypeRef::Struct(_) => "IntPtr".into(),
        TypeRef::Enum(_) => "int".into(),
        TypeRef::Optional(inner) => match inner.as_ref() {
            TypeRef::StringUtf8 | TypeRef::Struct(_) | TypeRef::Bytes => "IntPtr".into(),
            _ => pinvoke_type(inner),
        },
        TypeRef::List(_) => "IntPtr".into(),
        TypeRef::Map(_, _) => "IntPtr".into(),
    }
}

fn render_wrapper_class(out: &mut String, m: &Module) {
    let class_name = m.name.to_upper_camel_case();
    out.push_str(&format!("    public static class {class_name}\n    {{\n"));

    for f in &m.functions {
        render_wrapper_method(out, m, f);
    }

    out.push_str("    }\n\n");
}

fn render_wrapper_method(out: &mut String, m: &Module, f: &Function) {
    let method_name = f.name.to_upper_camel_case();
    let ret_cs = f
        .returns
        .as_ref()
        .map(cs_type)
        .unwrap_or_else(|| "void".into());

    let params_sig: Vec<String> = f
        .params
        .iter()
        .map(|p| format!("{} {}", cs_type(&p.ty), safe_cs_name(&p.name)))
        .collect();

    out.push_str(&format!(
        "        public static {ret_cs} {method_name}({})\n        {{\n",
        params_sig.join(", ")
    ));

    let c_sym = c_symbol_name(&m.name, &f.name);
    let native_class = format!("{}Native", m.name.to_upper_camel_case());

    out.push_str("            var err = new WeaveffiError();\n");

    let call_args = build_call_args(&f.params);
    if f.returns.is_some() {
        out.push_str(&format!(
            "            var result = {native_class}.{c_sym}({call_args}, ref err);\n"
        ));
    } else {
        out.push_str(&format!(
            "            {native_class}.{c_sym}({call_args}, ref err);\n"
        ));
    }

    out.push_str("            WeaveffiError.Check(err);\n");

    if let Some(ret_ty) = &f.returns {
        render_return_conversion(out, ret_ty);
    }

    out.push_str("        }\n\n");
}

fn build_call_args(params: &[Param]) -> String {
    params
        .iter()
        .map(|p| {
            let name = safe_cs_name(&p.name);
            match &p.ty {
                TypeRef::Bool => format!("{name} ? 1 : 0"),
                TypeRef::Enum(_) => format!("(int){name}"),
                _ => name,
            }
        })
        .collect::<Vec<_>>()
        .join(", ")
}

fn render_return_conversion(out: &mut String, ty: &TypeRef) {
    match ty {
        TypeRef::Bool => {
            out.push_str("            return result != 0;\n");
        }
        TypeRef::StringUtf8 => {
            out.push_str("            return Marshal.PtrToStringAnsi(result);\n");
        }
        TypeRef::Enum(name) => {
            out.push_str(&format!("            return ({name})result;\n"));
        }
        _ => {
            out.push_str("            return result;\n");
        }
    }
}

fn safe_cs_name(name: &str) -> String {
    match name {
        "string" | "int" | "long" | "double" | "float" | "bool" | "byte" | "object" | "class"
        | "struct" | "enum" | "event" | "delegate" | "namespace" | "ref" | "out" | "in"
        | "params" | "is" | "as" | "new" | "this" | "base" | "null" | "true" | "false"
        | "return" | "void" | "if" | "else" | "for" | "while" | "do" | "switch" | "case"
        | "break" | "continue" | "try" | "catch" | "finally" | "throw" | "using" | "static"
        | "const" | "readonly" | "override" | "virtual" | "abstract" | "sealed" | "public"
        | "private" | "protected" | "internal" => format!("@{name}"),
        _ => name.to_string(),
    }
}

fn render_error_struct(out: &mut String) {
    out.push_str("    [StructLayout(LayoutKind.Sequential)]\n");
    out.push_str("    internal struct WeaveffiError\n    {\n");
    out.push_str("        public int Code;\n");
    out.push_str("        public IntPtr Message;\n\n");
    out.push_str("        internal static void Check(WeaveffiError err)\n");
    out.push_str("        {\n");
    out.push_str("            if (err.Code != 0)\n");
    out.push_str("            {\n");
    out.push_str("                var msg = Marshal.PtrToStringAnsi(err.Message) ?? \"\";\n");
    out.push_str("                throw new WeaveffiException(err.Code, msg);\n");
    out.push_str("            }\n");
    out.push_str("        }\n");
    out.push_str("    }\n\n");
}

fn render_exception_class(out: &mut String) {
    out.push_str("    public class WeaveffiException : Exception\n    {\n");
    out.push_str("        public int Code { get; }\n\n");
    out.push_str("        public WeaveffiException(int code, string message) : base(message)\n");
    out.push_str("        {\n");
    out.push_str("            Code = code;\n");
    out.push_str("        }\n");
    out.push_str("    }\n\n");
}

#[cfg(test)]
mod tests {
    use super::*;
    use weaveffi_ir::ir::{EnumDef, EnumVariant, Function, Module, Param, StructDef, StructField};

    fn make_api(modules: Vec<Module>) -> Api {
        Api {
            version: "0.1.0".into(),
            modules,
        }
    }

    fn simple_module(functions: Vec<Function>) -> Module {
        Module {
            name: "math".into(),
            functions,
            structs: vec![],
            enums: vec![],
            errors: None,
        }
    }

    #[test]
    fn generator_name_is_dotnet() {
        assert_eq!(DotnetGenerator.name(), "dotnet");
    }

    #[test]
    fn output_files_lists_csharp_file() {
        let api = make_api(vec![]);
        let out = Utf8Path::new("/tmp/out");
        let files = DotnetGenerator.output_files(&api, out);
        assert_eq!(files, vec!["/tmp/out/dotnet/WeaveFFI.cs"]);
    }

    #[test]
    fn generate_creates_output_file() {
        let api = make_api(vec![simple_module(vec![Function {
            name: "add".into(),
            params: vec![
                Param {
                    name: "a".into(),
                    ty: TypeRef::I32,
                },
                Param {
                    name: "b".into(),
                    ty: TypeRef::I32,
                },
            ],
            returns: Some(TypeRef::I32),
            doc: None,
            r#async: false,
        }])]);

        let tmp = std::env::temp_dir().join("weaveffi_test_dotnet_gen_output");
        let _ = std::fs::remove_dir_all(&tmp);
        std::fs::create_dir_all(&tmp).unwrap();
        let out_dir = Utf8Path::from_path(&tmp).expect("valid UTF-8");

        DotnetGenerator.generate(&api, out_dir).unwrap();

        let cs = std::fs::read_to_string(tmp.join("dotnet/WeaveFFI.cs")).unwrap();
        assert!(cs.contains("namespace WeaveFFI"));
        assert!(cs.contains("DllImport"));
        assert!(cs.contains("weaveffi_math_add"));

        let _ = std::fs::remove_dir_all(&tmp);
    }

    #[test]
    fn cs_type_mapping() {
        assert_eq!(cs_type(&TypeRef::I32), "int");
        assert_eq!(cs_type(&TypeRef::U32), "uint");
        assert_eq!(cs_type(&TypeRef::I64), "long");
        assert_eq!(cs_type(&TypeRef::F64), "double");
        assert_eq!(cs_type(&TypeRef::Bool), "bool");
        assert_eq!(cs_type(&TypeRef::StringUtf8), "string");
        assert_eq!(cs_type(&TypeRef::Handle), "ulong");
        assert_eq!(cs_type(&TypeRef::Bytes), "byte[]");
        assert_eq!(cs_type(&TypeRef::Struct("Foo".into())), "Foo");
        assert_eq!(cs_type(&TypeRef::Enum("Bar".into())), "Bar");
        assert_eq!(cs_type(&TypeRef::Optional(Box::new(TypeRef::I32))), "int?");
        assert_eq!(cs_type(&TypeRef::List(Box::new(TypeRef::I32))), "int[]");
        assert_eq!(
            cs_type(&TypeRef::Map(
                Box::new(TypeRef::StringUtf8),
                Box::new(TypeRef::I32)
            )),
            "Dictionary<string, int>"
        );
    }

    #[test]
    fn simple_i32_function() {
        let api = make_api(vec![simple_module(vec![Function {
            name: "add".into(),
            params: vec![
                Param {
                    name: "a".into(),
                    ty: TypeRef::I32,
                },
                Param {
                    name: "b".into(),
                    ty: TypeRef::I32,
                },
            ],
            returns: Some(TypeRef::I32),
            doc: None,
            r#async: false,
        }])]);

        let cs = render_csharp(&api);
        assert!(cs.contains("namespace WeaveFFI"), "missing namespace: {cs}");
        assert!(cs.contains("DllImport"), "missing DllImport: {cs}");
        assert!(cs.contains("weaveffi_math_add"), "missing C symbol: {cs}");
        assert!(
            cs.contains("CallingConvention.Cdecl"),
            "missing Cdecl: {cs}"
        );
        assert!(
            cs.contains("public static int Add("),
            "missing wrapper method: {cs}"
        );
        assert!(
            cs.contains("WeaveffiError.Check(err)"),
            "missing error check: {cs}"
        );
    }

    #[test]
    fn void_function() {
        let api = make_api(vec![simple_module(vec![Function {
            name: "reset".into(),
            params: vec![],
            returns: None,
            doc: None,
            r#async: false,
        }])]);

        let cs = render_csharp(&api);
        assert!(
            cs.contains("public static void Reset()"),
            "missing void wrapper: {cs}"
        );
        assert!(
            cs.contains("static extern void weaveffi_math_reset"),
            "missing void P/Invoke: {cs}"
        );
    }

    #[test]
    fn bool_uses_int_marshaling() {
        let api = make_api(vec![simple_module(vec![Function {
            name: "is_valid".into(),
            params: vec![Param {
                name: "flag".into(),
                ty: TypeRef::Bool,
            }],
            returns: Some(TypeRef::Bool),
            doc: None,
            r#async: false,
        }])]);

        let cs = render_csharp(&api);
        assert!(
            cs.contains("flag ? 1 : 0"),
            "missing bool-to-int conversion: {cs}"
        );
        assert!(
            cs.contains("result != 0"),
            "missing int-to-bool conversion: {cs}"
        );
    }

    #[test]
    fn enum_generation() {
        let api = make_api(vec![Module {
            name: "paint".into(),
            functions: vec![Function {
                name: "mix".into(),
                params: vec![Param {
                    name: "a".into(),
                    ty: TypeRef::Enum("Color".into()),
                }],
                returns: Some(TypeRef::Enum("Color".into())),
                doc: None,
                r#async: false,
            }],
            structs: vec![],
            enums: vec![EnumDef {
                name: "Color".into(),
                doc: Some("Primary colors".into()),
                variants: vec![
                    EnumVariant {
                        name: "Red".into(),
                        value: 0,
                        doc: None,
                    },
                    EnumVariant {
                        name: "Green".into(),
                        value: 1,
                        doc: None,
                    },
                    EnumVariant {
                        name: "Blue".into(),
                        value: 2,
                        doc: None,
                    },
                ],
            }],
            errors: None,
        }]);

        let cs = render_csharp(&api);
        assert!(cs.contains("public enum Color"), "missing enum: {cs}");
        assert!(cs.contains("Red = 0"), "missing Red: {cs}");
        assert!(cs.contains("Green = 1"), "missing Green: {cs}");
        assert!(cs.contains("Blue = 2"), "missing Blue: {cs}");
        assert!(
            cs.contains("<summary>Primary colors</summary>"),
            "missing doc: {cs}"
        );
        assert!(cs.contains("(int)a"), "missing enum-to-int cast: {cs}");
        assert!(
            cs.contains("(Color)result"),
            "missing int-to-enum cast: {cs}"
        );
    }

    #[test]
    fn struct_generation() {
        let api = make_api(vec![Module {
            name: "contacts".into(),
            functions: vec![],
            structs: vec![StructDef {
                name: "Contact".into(),
                doc: Some("A contact record".into()),
                fields: vec![
                    StructField {
                        name: "first_name".into(),
                        ty: TypeRef::StringUtf8,
                        doc: None,
                    },
                    StructField {
                        name: "age".into(),
                        ty: TypeRef::I32,
                        doc: None,
                    },
                ],
            }],
            enums: vec![],
            errors: None,
        }]);

        let cs = render_csharp(&api);
        assert!(cs.contains("public class Contact"), "missing class: {cs}");
        assert!(
            cs.contains("<summary>A contact record</summary>"),
            "missing doc: {cs}"
        );
        assert!(
            cs.contains("public string FirstName { get; set; }"),
            "missing FirstName: {cs}"
        );
        assert!(
            cs.contains("public int Age { get; set; }"),
            "missing Age: {cs}"
        );
    }

    #[test]
    fn string_function() {
        let api = make_api(vec![Module {
            name: "text".into(),
            functions: vec![Function {
                name: "echo".into(),
                params: vec![Param {
                    name: "msg".into(),
                    ty: TypeRef::StringUtf8,
                }],
                returns: Some(TypeRef::StringUtf8),
                doc: None,
                r#async: false,
            }],
            structs: vec![],
            enums: vec![],
            errors: None,
        }]);

        let cs = render_csharp(&api);
        assert!(
            cs.contains("Marshal.PtrToStringAnsi(result)"),
            "missing string marshaling: {cs}"
        );
    }

    #[test]
    fn safe_cs_name_escapes_keywords() {
        assert_eq!(safe_cs_name("string"), "@string");
        assert_eq!(safe_cs_name("class"), "@class");
        assert_eq!(safe_cs_name("return"), "@return");
        assert_eq!(safe_cs_name("name"), "name");
        assert_eq!(safe_cs_name("id"), "id");
    }

    #[test]
    fn native_class_naming() {
        let api = make_api(vec![simple_module(vec![Function {
            name: "add".into(),
            params: vec![],
            returns: Some(TypeRef::I32),
            doc: None,
            r#async: false,
        }])]);

        let cs = render_csharp(&api);
        assert!(
            cs.contains("internal static class MathNative"),
            "missing native class: {cs}"
        );
        assert!(
            cs.contains("public static class Math"),
            "missing wrapper class: {cs}"
        );
    }

    #[test]
    fn pinvoke_has_error_param() {
        let api = make_api(vec![simple_module(vec![Function {
            name: "add".into(),
            params: vec![
                Param {
                    name: "a".into(),
                    ty: TypeRef::I32,
                },
                Param {
                    name: "b".into(),
                    ty: TypeRef::I32,
                },
            ],
            returns: Some(TypeRef::I32),
            doc: None,
            r#async: false,
        }])]);

        let cs = render_csharp(&api);
        assert!(
            cs.contains("ref WeaveffiError err"),
            "missing error param in P/Invoke: {cs}"
        );
    }

    #[test]
    fn header_has_using_statements() {
        let api = make_api(vec![]);
        let cs = render_csharp(&api);
        assert!(cs.contains("using System;"), "missing System: {cs}");
        assert!(
            cs.contains("using System.Runtime.InteropServices;"),
            "missing InteropServices: {cs}"
        );
        assert!(
            cs.contains("using System.Collections.Generic;"),
            "missing Collections.Generic: {cs}"
        );
    }

    #[test]
    fn optional_types() {
        assert_eq!(cs_type(&TypeRef::Optional(Box::new(TypeRef::I32))), "int?");
        assert_eq!(
            cs_type(&TypeRef::Optional(Box::new(TypeRef::Bool))),
            "bool?"
        );
        assert_eq!(
            cs_type(&TypeRef::Optional(Box::new(TypeRef::StringUtf8))),
            "string?"
        );
        assert_eq!(
            cs_type(&TypeRef::Optional(Box::new(TypeRef::Enum("Foo".into())))),
            "Foo?"
        );
    }

    #[test]
    fn comprehensive_contacts_api() {
        let api = make_api(vec![Module {
            name: "contacts".into(),
            enums: vec![EnumDef {
                name: "ContactType".into(),
                doc: None,
                variants: vec![
                    EnumVariant {
                        name: "Personal".into(),
                        value: 0,
                        doc: None,
                    },
                    EnumVariant {
                        name: "Work".into(),
                        value: 1,
                        doc: None,
                    },
                ],
            }],
            structs: vec![StructDef {
                name: "Contact".into(),
                doc: None,
                fields: vec![
                    StructField {
                        name: "id".into(),
                        ty: TypeRef::I64,
                        doc: None,
                    },
                    StructField {
                        name: "first_name".into(),
                        ty: TypeRef::StringUtf8,
                        doc: None,
                    },
                    StructField {
                        name: "email".into(),
                        ty: TypeRef::Optional(Box::new(TypeRef::StringUtf8)),
                        doc: None,
                    },
                    StructField {
                        name: "contact_type".into(),
                        ty: TypeRef::Enum("ContactType".into()),
                        doc: None,
                    },
                ],
            }],
            functions: vec![
                Function {
                    name: "create_contact".into(),
                    params: vec![
                        Param {
                            name: "first_name".into(),
                            ty: TypeRef::StringUtf8,
                        },
                        Param {
                            name: "email".into(),
                            ty: TypeRef::Optional(Box::new(TypeRef::StringUtf8)),
                        },
                        Param {
                            name: "contact_type".into(),
                            ty: TypeRef::Enum("ContactType".into()),
                        },
                    ],
                    returns: Some(TypeRef::Handle),
                    doc: None,
                    r#async: false,
                },
                Function {
                    name: "get_contact".into(),
                    params: vec![Param {
                        name: "id".into(),
                        ty: TypeRef::Handle,
                    }],
                    returns: Some(TypeRef::Struct("Contact".into())),
                    doc: None,
                    r#async: false,
                },
                Function {
                    name: "count_contacts".into(),
                    params: vec![],
                    returns: Some(TypeRef::I32),
                    doc: None,
                    r#async: false,
                },
            ],
            errors: None,
        }]);

        let tmp = std::env::temp_dir().join("weaveffi_test_dotnet_contacts");
        let _ = std::fs::remove_dir_all(&tmp);
        std::fs::create_dir_all(&tmp).unwrap();
        let out_dir = Utf8Path::from_path(&tmp).expect("valid UTF-8");

        DotnetGenerator.generate(&api, out_dir).unwrap();

        let cs = std::fs::read_to_string(tmp.join("dotnet/WeaveFFI.cs")).unwrap();

        assert!(cs.contains("public enum ContactType"));
        assert!(cs.contains("Personal = 0"));
        assert!(cs.contains("Work = 1"));

        assert!(cs.contains("public class Contact"));
        assert!(cs.contains("public long Id { get; set; }"));
        assert!(cs.contains("public string FirstName { get; set; }"));

        assert!(cs.contains("weaveffi_contacts_create_contact"));
        assert!(cs.contains("weaveffi_contacts_get_contact"));
        assert!(cs.contains("weaveffi_contacts_count_contacts"));

        assert!(cs.contains("public static class Contacts"));
        assert!(cs.contains("public static ulong CreateContact("));
        assert!(cs.contains("CallingConvention.Cdecl"));

        let _ = std::fs::remove_dir_all(&tmp);
    }
}
